/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Wednesday the eleventh of March, 1998, 2:29:25 am CST. */
#include <eclipse.h>

clObject cl1MINUS_FUNC(clProto), clAtom(clProto), clCar(clProto),
  clCdr(clProto), clCompare(clProto), clEndp(clProto), clEq(clProto),
  clExtraArgs(clProto), clFuncall(clProto), clHighlow(clProto),
  clKeyItem(clProto), clMinusp(clProto), clMissingArgs(clProto),
  clQuicksortList(clProto), clRplaca(clProto), clRplacd(clProto),
  clValues(clProto);

extern clObject clCOMPARE, clFIND_LIST_EQ_END, clHIGHLOW, clLIST,
  clNREVERSE_LIST, clQUICKSORT_LIST;

static clObject I_1, I_2, I_3, I_4, I_5, I_536870911, I_6;

clObject clFindListEqEnd clVdecl(_ap)
{ clObject item, list, end, key;
  { clBeginParse(_ap);
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(end,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(key, (_clVp(_ap) ? clVpop(_ap) : clNIL));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject elt, L_g47;
    clSetq(elt, clNIL);
    clSetq(L_g47, list);
    { clObject L_g48;
      clSetq(L_g48, (clTrue(end) ? end : I_536870911));
      clLabel(NEXT_LOOP);
      if (clTrue(clEndp(L_g47, clEOA))) goto END_LOOP;
      clSetq(elt, clCar(L_g47, clEOA));
      { clObject L_0;
        clSetq(L_0, L_g47);
        clSetq(L_g47, clCdr(L_0, clEOA)); }
      { clObject L_test;
        { clObject L_0;
          { clObject L_0__R1;
            clSetq(L_0__R1, L_g48);
            clSetq(L_0,
                   clSetq(L_g48, cl1MINUS_FUNC(L_0__R1, clEOA))); }
          clSetq(L_test, clMinusp(L_0, clEOA)); }
        if (clTrue(L_test)) goto END_LOOP; }
      { clObject L_test;
        { clObject L_1;
          { clObject L_1__R1, L_0__R1;
            clSetq(L_0__R1, key);
            clSetq(L_1__R1, elt);
            clSetq(L_1, clKeyItem(L_0__R1, L_1__R1, clEOA)); }
          clSetq(L_test, clEq(item, L_1, clEOA)); }
        if (clTrue(L_test)) return(clValues1(item)); }
      goto NEXT_LOOP;
      clLabel(END_LOOP);
      return(clValues1(clNIL)); } } }

clObject clNreverseList clVdecl(_ap)
{ clObject sequence;
  { clBeginParse(_ap);
    clSetq(sequence,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject tail, CL_new, sub;
    clSetq(tail, clCdr(sequence, clEOA));
    clSetq(CL_new, clNIL);
    clSetq(sub, sequence);
    clLabel(l_ITERATE1333);
    if (clTrue(clAtom(sub, clEOA))) return(clValues1(CL_new));
    clRplacd(sub, CL_new, clEOA);
    { clObject L_value1334, L_value1335, L_value1336;
      clSetq(L_value1334, clCdr(tail, clEOA));
      clSetq(L_value1335, sub);
      clSetq(L_value1336, tail);
      clSetq(tail, L_value1334);
      clSetq(CL_new, L_value1335);
      clSetq(sub, L_value1336); }
    goto l_ITERATE1333; } }

clObject clCompare clVdecl(_ap)
{ clObject x, y, pred, key;
  { clBeginParse(_ap);
    clSetq(x, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(y, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(pred,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(key,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    clSetq(L_1, clKeyItem(key, x, clEOA));
    return(clFuncall(pred, L_1, clKeyItem(key, y, clEOA), clEOA)); } }

clObject clHighlow clVdecl(_ap)
{ clObject list, item, high, low, pred, key;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(high,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(low,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    clSetq(pred,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_5, clEOA)));
    clSetq(key,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_6, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(list))
    { clObject L_form1337, first, rest;
      clSetq(L_form1337, list);
      if (clTrue(L_form1337))
        { clObject L_top1338;
          clSetq(L_top1338, clCar(L_form1337, clEOA));
          { clObject L_0;
            clSetq(L_0, L_form1337);
            clSetq(L_form1337, clCdr(L_0, clEOA)); }
          clSetq(first, L_top1338); }
      else clSetq(first, clMissingArgs(I_1, clEOA));
      clSetq(rest, L_form1337);
      (clRplaca(list, first, clEOA), first);
      if (clTrue(clCompare(first, item, pred, key, clEOA)))
        { clObject L_3;
          clSetq(L_3, clRplacd(list, low, clEOA));
          return(clHighlow(rest, item, high, L_3, pred, key, clEOA)); }
      else
        { clObject L_2;
          clSetq(L_2, clRplacd(list, high, clEOA));
          return(clHighlow(rest,
                           item,
                           L_2,
                           low,
                           pred,
                           key,
                           clEOA)); } }
  else return(clValues(high, low, clEOA)); }

clObject clQuicksortList clVdecl(_ap)
{ clObject list, sorted, pred, key;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(sorted,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(pred,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(key,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(list))
    { clObject L_form1341, item, unsorted;
      clSetq(L_form1341, list);
      if (clTrue(L_form1341))
        { clObject L_top1342;
          clSetq(L_top1342, clCar(L_form1341, clEOA));
          { clObject L_0;
            clSetq(L_0, L_form1341);
            clSetq(L_form1341, clCdr(L_0, clEOA)); }
          clSetq(item, L_top1342); }
      else clSetq(item, clMissingArgs(I_1, clEOA));
      clSetq(unsorted, L_form1341);
      { clObject L_values1343, high, low;
        { clMultipleValueCall(MVC);
          clSetq(MVC, clSymbolFunctionValue(clLIST));
          clHighlow(unsorted, item, clNIL, clNIL, pred, key, clEOA);
          clAccumulateValues(MVC);
          clSetq(L_values1343, clMultipleValueFuncall(MVC)); }
        clSetq(high, clCar(L_values1343, clEOA));
        { clObject L_0;
          { clObject L_0__R1;
            clSetq(L_0__R1, L_values1343);
            clSetq(L_0, clSetq(L_values1343, clCdr(L_0__R1, clEOA))); }
          clSetq(low, clCar(L_0, clEOA)); }
        (clRplaca(list, item, clEOA), item);
        { clObject L_g1347;
          clSetq(L_g1347,
                 clQuicksortList(high, sorted, pred, key, clEOA));
          clRplacd(list, L_g1347, clEOA);
          (void) L_g1347; }
        return(clQuicksortList(low, list, pred, key, clEOA)); } }
  else return(clValues1(sorted)); }

void clInitClosSeq __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(I_3, clIntFixnum(3));
  clSetq(I_536870911, clIntFixnum(536870911));
  clSetq(I_4, clIntFixnum(4));
  clSetq(I_5, clIntFixnum(5));
  clSetq(I_6, clIntFixnum(6));

  clSetSymbolFunctionValue(clFIND_LIST_EQ_END,
                           clMakeClosure(0,
                                         clFindListEqEnd,
                                         clNULL_HOOK));
  (void) clFIND_LIST_EQ_END;
  clSetSymbolFunctionValue(clNREVERSE_LIST,
                           clMakeClosure(0,
                                         clNreverseList,
                                         clNULL_HOOK));
  (void) clNREVERSE_LIST;
  clSetSymbolFunctionValue(clCOMPARE,
                           clMakeClosure(0, clCompare, clNULL_HOOK));
  (void) clCOMPARE;
  clSetSymbolFunctionValue(clHIGHLOW,
                           clMakeClosure(0, clHighlow, clNULL_HOOK));
  (void) clHIGHLOW;
  clSetSymbolFunctionValue(clQUICKSORT_LIST,
                           clMakeClosure(0,
                                         clQuicksortList,
                                         clNULL_HOOK));
  (void) clQUICKSORT_LIST;
  clUnwind(4); }
