/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Tuesday the twenty-sixth of May, 1998, 3:33:48 pm CDT. */
#include <eclipse.h>

clObject clAppend(clProto), clApply(clProto), clCar(clProto),
  clCarEq(clProto), clCdr(clProto), clCons(clProto), clEndp(clProto),
  clExtraArgs(clProto), clFindDeclarations(clProto),
  clFindPackage(clProto), clIntern(clProto), clList(clProto),
  clListSTAR(clProto), cl_SETF_MacroFunction(clProto),
  clMakeSymbol(clProto), clMakeSymbols(clProto), clMapc(clProto),
  clMapcar(clProto), clMissingArgs(clProto), clNot(clProto),
  clRplacd(clProto), cl_SETF_SetfExpander(clProto), clString(clProto),
  clStringp(clProto), clSymbolName(clProto), clValues(clProto);

extern clObject clDECLARE, clINLINE, clLET, cl1plussymbol, cl1_symbol,
  clBQ_LIST, clBQ_QUOTE, clENCLOSING_ENVIRONMENT, clFIND_DECLARATIONS,
  clFIXNUM_INDEX, clFORMAT, clFUNCALLABLE_STANDARD_INSTANCE_ACCESS,
  clINSTANCE, clLIST, clLOCATION, clMAKE_BINDING_LIST, clMAKE_NAME,
  clMAKE_NAME_IN_PACKAGE, clMAKE_SYMBOL, clPROCLAIM, clREBINDING,
  clSET_SLOT, clSTANDARD_INSTANCE_ACCESS, clSTANDARD_INSTANCE_SLOTS,
  clVALUE, clWITH_UNIQUE_NAMES, clXOR;

static clObject CONS_0, CONS_1, CONS_10, CONS_2, CONS_3, CONS_4,
  CONS_5, CONS_6, CONS_7, CONS_8, CONS_9, I_1, I_2, I_3;

clObject clWithUniqueNames clVdecl(_ap)
{ clObject L_form, L_ignored, vars, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top397;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top397, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(vars, L_top397); }
    else clSetq(vars, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    { clObject var, L_g0;
      clSetq(var, clNIL);
      clSetq(L_g0, vars);
      { clObject L_g1, L_g2;
        clSetq(L_g1, clList(clNIL, clEOA));
        clSetq(L_g2, L_g1);
        clLabel(NEXT_LOOP);
        if (clTrue(clEndp(L_g0, clEOA))) goto END_LOOP;
        clSetq(var, clCar(L_g0, clEOA));
        { clObject L_0__R1;
          clSetq(L_0__R1, L_g0);
          clSetq(L_g0, clCdr(L_0__R1, clEOA)); }
        { clObject L_1__R1, L_0__R1;
          clSetq(L_0__R1, L_g2);
          { clObject L_0__R2;
            { clObject L_1__R2, L_0__R3;
              clSetq(L_0__R3, var);
              { clObject L_1__R3;
                { clObject L_0__R5;
                  clSetq(L_0__R5, var);
                  clSetq(L_1__R3, clSymbolName(L_0__R5, clEOA)); }
                clSetq(L_1__R2,
                       clList(clMAKE_SYMBOL, L_1__R3, clEOA)); }
              clSetq(L_0__R2, clList(L_0__R3, L_1__R2, clEOA)); }
            clSetq(L_1__R1, clSetq(L_g2, clList(L_0__R2, clEOA))); }
          clRplacd(L_0__R1, L_1__R1, clEOA); }
        goto NEXT_LOOP;
        clLabel(END_LOOP);
        clSetq(L_1, clCdr(L_g1, clEOA));
        clLocalReturn(NIL);
        clSetq(L_1, clNIL);
        clBlockEnd(NIL); } }
    return(clListSTAR(clLET, L_1, body, clEOA)); } }

clObject clRebinding clVdecl(_ap)
{ clObject L_form, L_ignored, vars, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top400;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top400, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(vars, L_top400); }
    else clSetq(vars, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject var, L_g3;
    clSetq(var, clNIL);
    clSetq(L_g3, vars);
    { clObject name;
      clSetq(name, clNIL);
      { clObject L_g4, L_g5, renames;
        clSetq(L_g4, clList(clNIL, clEOA));
        clSetq(L_g5, L_g4);
        clSetq(renames, clNIL);
        { clObject L_g6, L_g7, temps;
          clSetq(L_g6, clList(clNIL, clEOA));
          clSetq(L_g7, L_g6);
          clSetq(temps, clNIL);
          clLabel(NEXT_LOOP);
          if (clTrue(clEndp(L_g3, clEOA))) goto END_LOOP;
          clSetq(var, clCar(L_g3, clEOA));
          { clObject L_0;
            clSetq(L_0, L_g3);
            clSetq(L_g3, clCdr(L_0, clEOA)); }
          { clObject L_0;
            { clObject L_0__R1;
              clSetq(L_0__R1, var);
              clSetq(L_0, clSymbolName(L_0__R1, clEOA)); }
            clSetq(name, clMakeSymbol(L_0, clEOA)); }
          { clObject L_1, L_0;
            clSetq(L_0, L_g5);
            { clObject L_0__R1;
              { clObject L_1__R1, L_0__R2;
                clSetq(L_0__R2, name);
                clSetq(L_1__R1, var);
                clSetq(L_0__R1, clList(L_0__R2, L_1__R1, clEOA)); }
              clSetq(L_1, clSetq(L_g5, clList(L_0__R1, clEOA))); }
            clRplacd(L_0, L_1, clEOA); }
          clSetq(renames, clCdr(L_g4, clEOA));
          { clObject L_1, L_0;
            clSetq(L_0, L_g7);
            { clObject L_0__R1;
              { clObject L_2, L_1__R1;
                clSetq(L_1__R1, var);
                clSetq(L_2, name);
                clSetq(L_0__R1,
                       clList(clBQ_LIST, L_1__R1, L_2, clEOA)); }
              clSetq(L_1, clSetq(L_g7, clList(L_0__R1, clEOA))); }
            clRplacd(L_0, L_1, clEOA); }
          clSetq(temps, clCdr(L_g6, clEOA));
          goto NEXT_LOOP;
          clLabel(END_LOOP);
          { clObject L_2, L_1;
            clSetq(L_1, renames);
            { clObject L_2__R1, L_1__R1;
              clSetq(L_1__R1, vars);
              { clObject L_2__R2;
                { clObject L_1__R3;
                  clSetq(L_1__R3, temps);
                  clSetq(L_2__R2,
                         clListSTAR(clBQ_LIST, L_1__R3, clEOA)); }
                clSetq(L_2__R1,
                       clListSTAR(clBQ_LIST,
                                  CONS_6,
                                  L_2__R2,
                                  body,
                                  clEOA)); }
              clSetq(L_2,
                     clList(clWITH_UNIQUE_NAMES,
                            L_1__R1,
                            L_2__R1,
                            clEOA)); }
            return(clList(clLET, L_1, L_2, clEOA)); }
          return(clValues1(clNIL)); } } } } }

clObject clMakeName clVdecl(_ap)
{ clObject format, args;
  { clBeginParse(_ap);
    clSetq(format,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(args, clVargs(_ap));
    clEndParse(_ap); }
  { clObject L_0;
    { clObject L_2, L_0__R1;
      clSetq(L_0__R1, clSymbolFunctionValue(clFORMAT));
      { clObject L_0__R2;
        clSetq(L_0__R2, format);
        clSetq(L_2, clString(L_0__R2, clEOA)); }
      clSetq(L_0, clApply(L_0__R1, clNIL, L_2, args, clEOA)); }
    return(clIntern(L_0, clEOA)); } }

clObject clMakeNameInPackage clVdecl(_ap)
{ clObject pkg, format, args;
  { clBeginParse(_ap);
    clSetq(pkg,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(format,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(args, clVargs(_ap));
    clEndParse(_ap); }
  { clObject STARpackageSTAR;
    { clObject L_0;
      clSetq(L_0, pkg);
      clSetq(STARpackageSTAR, clFindPackage(L_0, clEOA)); }
    clDbind(clstarPACKAGEstar);
    clSetSymbolValueValue(clstarPACKAGEstar, STARpackageSTAR);
    { clObject L_1, L_0;
      clSetq(L_0, clSymbolFunctionValue(clMAKE_NAME));
      clSetq(L_1, format);
      clUnwindReturn(clApply(L_0, L_1, args, clEOA), 1); } } }

clObject clMakeBindingList clVdecl(_ap)
{ clObject names, inits;
  { clBeginParse(_ap);
    clSetq(names,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(inits,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_2, L_1, L_0;
    clSetq(L_0, clSymbolFunctionValue(clLIST));
    clSetq(L_1, names);
    clSetq(L_2, inits);
    return(clMapcar(L_0, L_1, L_2, clEOA)); } }

clObject clFindDeclarations clVdecl(_ap)
{ clObject body, ignore_docQUESTION;
  { clBeginParse(_ap);
    clSetq(body,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(ignore_docQUESTION,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_test;
    { clObject L_0;
      clSetq(L_0, body);
      clSetq(L_test, clEndp(L_0, clEOA)); }
    if (clTrue(L_test))
      return(clValues(clNIL, clNIL, clNIL, clEOA));
    else
      { clObject d;
        { clObject L_0;
          clSetq(L_0, body);
          clSetq(d, clCar(L_0, clEOA)); }
        { clObject L_test__R1;
          if (clTrue(clStringp(d, clEOA)))
            { clObject L_test__R3;
              { clObject L_0;
                clSetq(L_0, ignore_docQUESTION);
                clSetq(L_test__R3, clNot(L_0, clEOA)); }
              if (clTrue(L_test__R3))
                { clObject L_0;
                  clSetq(L_0, body);
                  clSetq(L_test__R1, clCdr(L_0, clEOA)); }
              else clSetq(L_test__R1, clNIL); }
          else clSetq(L_test__R1, clNIL);
          if (clTrue(L_test__R1))
            { clObject L_values401, decls, b;
              { clMultipleValueCall(MVC);
                clSetq(MVC, clSymbolFunctionValue(clLIST));
                { clObject L_0;
                  { clObject L_0__R1;
                    clSetq(L_0__R1, body);
                    clSetq(L_0, clCdr(L_0__R1, clEOA)); }
                  clFindDeclarations(L_0, clT, clEOA); }
                clAccumulateValues(MVC);
                clSetq(L_values401, clMultipleValueFuncall(MVC)); }
              clSetq(decls, clCar(L_values401, clEOA));
              { clObject L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, L_values401);
                  clSetq(L_0,
                         clSetq(L_values401, clCdr(L_0__R1, clEOA))); }
                clSetq(b, clCar(L_0, clEOA)); }
              return(clValues(decls, b, d, clEOA)); }
          else if (clTrue(clCarEq(d, clDECLARE, clEOA)))
            { clObject L_values402, decls, b, doc;
              { clMultipleValueCall(MVC__r1);
                clSetq(MVC__r1, clSymbolFunctionValue(clLIST));
                { clObject L_1, L_0;
                  { clObject L_0__R1;
                    clSetq(L_0__R1, body);
                    clSetq(L_0, clCdr(L_0__R1, clEOA)); }
                  clSetq(L_1, ignore_docQUESTION);
                  clFindDeclarations(L_0, L_1, clEOA); }
                clAccumulateValues(MVC__r1);
                clSetq(L_values402, clMultipleValueFuncall(MVC__r1)); }
              clSetq(decls, clCar(L_values402, clEOA));
              { clObject L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, L_values402);
                  clSetq(L_0,
                         clSetq(L_values402, clCdr(L_0__R1, clEOA))); }
                clSetq(b, clCar(L_0, clEOA)); }
              { clObject L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, L_values402);
                  clSetq(L_0,
                         clSetq(L_values402, clCdr(L_0__R1, clEOA))); }
                clSetq(doc, clCar(L_0, clEOA)); }
              { clObject L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, clCdr(d, clEOA));
                  clSetq(L_0, clAppend(L_0__R1, decls, clEOA)); }
                return(clValues(L_0, b, doc, clEOA)); } }
          else
            { clObject L_1;
              clSetq(L_1, body);
              return(clValues(clNIL, L_1, clNIL, clEOA)); } } } } }

static clObject clLambda_Lambda clVdecl(_ap)
{ clObject instance, location, value;
  { clBeginParse(_ap);
    clSetq(instance,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(location,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(value,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_3, L_2, L_1;
    { clObject L_1__R1;
      clSetq(L_1__R1, instance);
      clSetq(L_1, clList(clSTANDARD_INSTANCE_SLOTS, L_1__R1, clEOA)); }
    { clObject L_1__R1;
      clSetq(L_1__R1, location);
      clSetq(L_2, clList(clFIXNUM_INDEX, L_1__R1, clEOA)); }
    clSetq(L_3, value);
    return(clList(clSET_SLOT, L_1, L_2, L_3, clEOA)); } }

static clObject clLambda clVdecl(_ap)
{ clObject L_form, L_ignored, instance, location;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top405;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top405, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(instance, L_top405); }
    else clSetq(instance, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top406;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top406, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(location, L_top406); }
    else clSetq(location, clMissingArgs(I_2, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  { clObject CL_temps, CL_store_temps, CL_setter;
    clSetq(CL_temps, clMakeSymbols(CONS_8, clEOA));
    clSetq(CL_store_temps, clMakeSymbols(CONS_10, clEOA));
    { clObject L_0;
      clSetq(L_0, clMakeClosure(0, clLambda_Lambda, clNULL_HOOK));
      clSetq(CL_setter,
             clApply(L_0, clAppend(CL_temps, CL_store_temps, clEOA),
                     clEOA)); }
    { clObject L_1;
      { clObject L_1__R1, L_0__R1;
        clSetq(L_0__R1, instance);
        clSetq(L_1__R1, location);
        clSetq(L_1, clList(L_0__R1, L_1__R1, clEOA)); }
      return(clValues(CL_temps,
                      L_1,
                      CL_store_temps,
                      CL_setter,
                      clCons(clSTANDARD_INSTANCE_ACCESS,
                             CL_temps,
                             clEOA),
                      clEOA)); } } }

static clObject clLambda_r1_Lambda clVdecl(_ap)
{ clObject instance, location, value;
  { clBeginParse(_ap);
    clSetq(instance,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(location,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(value,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_3, L_2, L_1;
    { clObject L_1__R1;
      clSetq(L_1__R1, instance);
      clSetq(L_1, clList(clSTANDARD_INSTANCE_SLOTS, L_1__R1, clEOA)); }
    { clObject L_1__R1;
      clSetq(L_1__R1, location);
      clSetq(L_2, clList(clFIXNUM_INDEX, L_1__R1, clEOA)); }
    clSetq(L_3, value);
    return(clList(clSET_SLOT, L_1, L_2, L_3, clEOA)); } }

static clObject clLambda_r1 clVdecl(_ap)
{ clObject L_form, L_ignored, instance, location;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top409;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top409, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(instance, L_top409); }
    else clSetq(instance, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top410;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top410, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(location, L_top410); }
    else clSetq(location, clMissingArgs(I_2, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  { clObject CL_temps, CL_store_temps, CL_setter;
    clSetq(CL_temps, clMakeSymbols(CONS_8, clEOA));
    clSetq(CL_store_temps, clMakeSymbols(CONS_10, clEOA));
    { clObject L_0;
      clSetq(L_0, clMakeClosure(0, clLambda_r1_Lambda, clNULL_HOOK));
      clSetq(CL_setter,
             clApply(L_0, clAppend(CL_temps, CL_store_temps, clEOA),
                     clEOA)); }
    { clObject L_1;
      { clObject L_1__R1, L_0__R1;
        clSetq(L_0__R1, instance);
        clSetq(L_1__R1, location);
        clSetq(L_1, clList(L_0__R1, L_1__R1, clEOA)); }
      return(clValues(CL_temps,
                      L_1,
                      CL_store_temps,
                      CL_setter,
                      clCons(clFUNCALLABLE_STANDARD_INSTANCE_ACCESS,
                             CL_temps,
                             clEOA),
                      clEOA)); } } }

void clInitCommonComp __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(CONS_5, clCons(cl1_symbol, clNIL, clEOA));
  clSetq(CONS_4, clCons(cl1plussymbol, CONS_5, clEOA));
  clSetq(CONS_3, clCons(clENCLOSING_ENVIRONMENT, CONS_4, clEOA));
  clSetq(CONS_2, clCons(clXOR, CONS_3, clEOA));
  clSetq(CONS_1, clCons(clINLINE, CONS_2, clEOA));
  clSetq(CONS_0, clCons(CONS_1, clNIL, clEOA));
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(CONS_7, clCons(clLET, clNIL, clEOA));
  clSetq(CONS_6, clCons(clBQ_QUOTE, CONS_7, clEOA));
  clSetq(CONS_9, clCons(clLOCATION, clNIL, clEOA));
  clSetq(CONS_8, clCons(clINSTANCE, CONS_9, clEOA));
  clSetq(CONS_10, clCons(clVALUE, clNIL, clEOA));
  clSetq(I_3, clIntFixnum(3));

  { clObject L_0;
    clSetq(L_0, clSymbolFunctionValue(clPROCLAIM));
    clMapc(L_0, CONS_0, clEOA); }
  { clObject L_value395;
    clSetq(L_value395,
           clMakeClosure(0, clWithUniqueNames, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value395, clWITH_UNIQUE_NAMES, clEOA); }
  (void) clWITH_UNIQUE_NAMES;
  { clObject L_value398;
    clSetq(L_value398, clMakeClosure(0, clRebinding, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value398, clREBINDING, clEOA); }
  (void) clREBINDING;
  clSetSymbolFunctionValue(clMAKE_NAME,
                           clMakeClosure(0, clMakeName, clNULL_HOOK));
  (void) clMAKE_NAME;
  clSetSymbolFunctionValue(clMAKE_NAME_IN_PACKAGE,
                           clMakeClosure(0,
                                         clMakeNameInPackage,
                                         clNULL_HOOK));
  (void) clMAKE_NAME_IN_PACKAGE;
  clSetSymbolFunctionValue(clMAKE_BINDING_LIST,
                           clMakeClosure(0,
                                         clMakeBindingList,
                                         clNULL_HOOK));
  (void) clMAKE_BINDING_LIST;
  clSetSymbolFunctionValue(clFIND_DECLARATIONS,
                           clMakeClosure(0,
                                         clFindDeclarations,
                                         clNULL_HOOK));
  (void) clFIND_DECLARATIONS;
  { clObject L_value403;
    clSetq(L_value403, clMakeClosure(0, clLambda, clNULL_HOOK));
    cl_SETF_SetfExpander(L_value403,
                         clSTANDARD_INSTANCE_ACCESS,
                         clEOA); }
  (void) clSTANDARD_INSTANCE_ACCESS;
  { clObject L_value407;
    clSetq(L_value407, clMakeClosure(0, clLambda_r1, clNULL_HOOK));
    cl_SETF_SetfExpander(L_value407,
                         clFUNCALLABLE_STANDARD_INSTANCE_ACCESS,
                         clEOA); }
  (void) clFUNCALLABLE_STANDARD_INSTANCE_ACCESS;
  clUnwind(4); }
