/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Wednesday the eighth of April, 1998, 10:34:23 am CDT. */
#include <eclipse.h>

clObject clAppend(clProto), clAtom(clProto),
  clBindFormFromCase(clProto), clButlast(clProto), clCar(clProto),
  clCaseKeys(clProto), clCddr(clProto), clCdr(clProto),
  clCharpSimpleBaseString __P((clCharp)), clCons(clProto),
  clConsp(clProto), clDelete(clProto), clEndp(clProto), clEq(clProto),
  clExtraArgs(clProto), clFind(clProto), clFirst(clProto),
  clFuncall(clProto), clGensym(clProto), clLast(clProto),
  clList(clProto), clListSTAR(clProto), cl_SETF_MacroFunction(clProto),
  clMacroexpand(clProto), clMakeConditionBindings(clProto),
  clMakeKeyword(clProto), clMapcar(clProto), clMissingArgs(clProto),
  clNot(clProto), clRest(clProto), clRplacd(clProto),
  clSecond(clProto), clStringp(clProto), clSymbolName(clProto),
  clWarn(clProto);

extern clObject clampersandREST, clBLOCK, clCONS, clDECLARE,
  clDYNAMIC_EXTENT, clGO, clIF, clLAMBDA, clLET, clMULTIPLE_VALUE_CALL,
  clOTHERWISE, clPROGN, clQUOTE, clRETURN_FROM, clSETQ, clTAGBODY,
  clUNWIND_PROTECT, clstarHANDLERSstar, clstarPRINT_ESCAPEstar,
  clstarRESTARTSstar, clASSERT, clASSERT_ERROR, clASSERT_PROMPT,
  clASSOCIATE_CONDITIONS, clBIND_FORM_FROM_CASE, clCALL_NEXT_METHOD,
  clCANONICALIZE_CONDITION, clCASE, clCCASE, clCERROR, clCHECK_TYPE,
  clCHECK_TYPE_ERROR, clCONDITION, clCTYPECASE, clDEFCLASS,
  clDEFINE_CONDITION, clDEFMETHOD, clDESTRUCTURING_BIND,
  clDISASSOCIATE_CONDITIONS, clERROR, clFIRST, clFORMAT, clFUNCTION,
  clHANDLER_BIND, clHANDLER_CASE, clHANDLER_CASE_BODY, clIGNORE_ERRORS,
  clLIST, clLOOP, clMAKE_CONDITION_BINDINGS, clMAKE_HANDLER,
  clMAKE_RESTART, clMEMBER, clOR, clPRINT_OBJECT, clRESTART_BIND,
  clRESTART_CASE, clRESTART_CASE_BODY, clRESTART_CASE_OPTIONS, clS,
  clSETF, clSIGNAL, clSIMPLE_CONDITION, clSIMPLE_ERROR,
  clSIMPLE_WARNING, clTEMP, clTYPECASE, clTYPEP, clVALUES, clWARN,
  clWHEN, clWITH_CONDITION_RESTARTS, clWITH_SIMPLE_RESTART,
  clWRITE_STRING;

static clObject CONS_0, CONS_1, CONS_10, CONS_11, CONS_12, CONS_13,
  CONS_14, CONS_15, CONS_16, CONS_17, CONS_18, CONS_19, CONS_2,
  CONS_20, CONS_21, CONS_22, CONS_23, CONS_24, CONS_25, CONS_26,
  CONS_27, CONS_28, CONS_29, CONS_3, CONS_30, CONS_31, CONS_32, CONS_4,
  CONS_5, CONS_6, CONS_7, CONS_8, CONS_9, I_1, I_2, I_3, I_4, I_5, I_6,
  I_7, keyASSOCIATED_CONDITIONS, keyINTERACTIVE,
  keyINTERACTIVE_FUNCTION, keyKEY, keyNO_ERROR, keyREPORT,
  keyREPORT_FUNCTION, keyTEST, keyTEST_FUNCTION, STR_ASSERT__6,
  STR_CCASE__8, STR_CHECK_TYPE__1, STR_CONDITION__4, STR_CTYPECASE__7,
  STR_INTERACTIVE__11, STR_KEY__3, STR_NO_ERROR__13,
  STR_NORMAL_RETURN__14, STR_OLD_ASSOCIATIONS__9,
  STR_REPORT_FUNCTION__17, STR_REPORT__2, STR_STREAM__5,
  STR_TEST_FUNCTION__19, STR_TEST__10, STR_VALUES__12, STR_VALUE__0,
  STRn_15, STRn_16, STRn_18;

clObject clCheckType clVdecl(_ap)
{ clObject L_form, L_ignored, place, type, type_string;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top486;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top486, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(place, L_top486); }
    else clSetq(place, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top487;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top487, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(type, L_top487); }
    else clSetq(type, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form))
      { clObject L_top488;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top488, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(type_string, L_top488); }
    else clSetq(type_string, clNIL);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  { clObject var, block;
    clSetq(var, clGensym(STR_VALUE__0, clEOA));
    clSetq(block, clGensym(STR_CHECK_TYPE__1, clEOA));
    { clObject L_2;
      { clObject L_1__R1;
        { clObject L_3, L_2__R1, L_1__R2;
          clSetq(L_1__R2, clList(clList(var, place, clEOA), clEOA));
          { clObject L_1__R3;
            clSetq(L_1__R3,
                   clList(clTYPEP,
                          var,
                          clList(clQUOTE, type, clEOA),
                          clEOA));
            clSetq(L_2__R1,
                   clList(clWHEN,
                          L_1__R3,
                          clListSTAR(clRETURN_FROM,
                                     block,
                                     CONS_0,
                                     clEOA),
                          clEOA)); }
          { clObject L_2__R2;
            { clObject L_4, L_3__R1, L_1__R4;
              clSetq(L_1__R4, clList(clQUOTE, place, clEOA));
              clSetq(L_3__R1, clList(clQUOTE, type, clEOA));
              clSetq(L_4, type_string);
              clSetq(L_2__R2,
                     clList(clCHECK_TYPE_ERROR,
                            L_1__R4,
                            var,
                            L_3__R1,
                            L_4,
                            clEOA)); }
            clSetq(L_3, clList(clSETF, place, L_2__R2, clEOA)); }
          clSetq(L_1__R1,
                 clList(clLET, L_1__R2, L_2__R1, L_3, clEOA)); }
        clSetq(L_2, clList(clLOOP, L_1__R1, clEOA)); }
      return(clList(clBLOCK, block, L_2, clEOA)); } } }

clObject clDefineCondition clVdecl(_ap)
{ clObject L_form, L_ignored, name, superclasses, slot_specs, options;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top491;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top491, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(name, L_top491); }
    else clSetq(name, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top492;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top492, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(superclasses, L_top492); }
    else clSetq(superclasses, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form))
      { clObject L_top493;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top493, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(slot_specs, L_top493); }
    else clSetq(slot_specs, clMissingArgs(I_3, clEOA));
    clSetq(options, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject report_clause, options__R1;
    clSetq(report_clause,
           clFind(keyREPORT, options, keyKEY,
                  clSymbolFunctionValue(clFIRST), clEOA));
    clSetq(options__R1,
           clDelete(keyREPORT, options, keyKEY,
                    clSymbolFunctionValue(clFIRST), clEOA));
    { clObject L_2, L_1;
      { clObject L_2__R1;
        clSetq(L_2__R1,
               (clTrue(superclasses) ? superclasses : CONS_1));
        clSetq(L_1,
               clListSTAR(clDEFCLASS,
                          name,
                          L_2__R1,
                          slot_specs,
                          options__R1,
                          clEOA)); }
      { clObject L_0__R1;
        if (clTrue(report_clause))
          { clObject report, condition, stream;
            clSetq(report, clSecond(report_clause, clEOA));
            clSetq(condition, clGensym(STR_CONDITION__4, clEOA));
            clSetq(stream, clGensym(STR_STREAM__5, clEOA));
            { clObject L_0__R2;
              { clObject L_3, L_2__R1;
                { clObject L_0__R4;
                  clSetq(L_0__R4, clList(condition, name, clEOA));
                  clSetq(L_2__R1, clList(L_0__R4, stream, clEOA)); }
                { clObject L_3__R1;
                  clSetq(L_3__R1,
                         (clTrue(clStringp(report, clEOA)) ?
                          clList(clWRITE_STRING,
                                 report,
                                 stream,
                                 clEOA) :
                          clList(report, condition, stream, clEOA)));
                  clSetq(L_3,
                         clList(clIF,
                                clstarPRINT_ESCAPEstar,
                                CONS_2,
                                L_3__R1,
                                clEOA)); }
                clSetq(L_0__R2,
                       clList(clDEFMETHOD,
                              clPRINT_OBJECT,
                              L_2__R1,
                              L_3,
                              clEOA)); }
              clSetq(L_0__R1, clList(L_0__R2, clEOA)); } }
        else clSetq(L_0__R1, clNIL);
        clSetq(L_2,
               clAppend(L_0__R1,
                        clList(clList(clQUOTE, name, clEOA), clEOA),
                        clEOA)); }
      return(clListSTAR(clPROGN, L_1, L_2, clEOA)); } } }

static clObject clAssert_Lambda clVdecl(_ap)
{ clObject place;
  { clBeginParse(_ap);
    clSetq(place,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_2;
    { clObject L_1__R1;
      clSetq(L_1__R1, clList(clQUOTE, place, clEOA));
      clSetq(L_2, clList(clASSERT_PROMPT, L_1__R1, place, clEOA)); }
    return(clList(clSETF, place, L_2, clEOA)); } }

clObject clAssert clVdecl(_ap)
{ clObject L_form, L_ignored, test_form, places, datum, arguments;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top497;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top497, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(test_form, L_top497); }
    else clSetq(test_form, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top498;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top498, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(places, L_top498); }
    else clSetq(places, clNIL);
    if (clTrue(L_form))
      { clObject L_top499;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top499, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(datum, L_top499); }
    else clSetq(datum, clNIL);
    clSetq(arguments, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject block;
    clSetq(block, clGensym(STR_ASSERT__6, clEOA));
    { clObject L_2;
      { clObject L_3, L_2__R1, L_1__R1;
        clSetq(L_1__R1,
               clList(clWHEN,
                      test_form,
                      clListSTAR(clRETURN_FROM, block, CONS_0, clEOA),
                      clEOA));
        { clObject L_3__R1, L_2__R2, L_1__R2;
          clSetq(L_1__R2, clList(clQUOTE, test_form, clEOA));
          { clObject L_1__R3;
            clSetq(L_1__R3, places);
            clSetq(L_2__R2, clList(clQUOTE, L_1__R3, clEOA)); }
          clSetq(L_3__R1, datum);
          clSetq(L_2__R1,
                 clListSTAR(clASSERT_ERROR,
                            L_1__R2,
                            L_2__R2,
                            L_3__R1,
                            arguments,
                            clEOA)); }
        { clObject L_1__R2, L_0__R2;
          clSetq(L_0__R2,
                 clMakeClosure(0, clAssert_Lambda, clNULL_HOOK));
          clSetq(L_1__R2, places);
          clSetq(L_3, clMapcar(L_0__R2, L_1__R2, clEOA)); }
        clSetq(L_2,
               clListSTAR(clLOOP, L_1__R1, L_2__R1, L_3, clEOA)); }
      return(clList(clBLOCK, block, L_2, clEOA)); } } }

clObject clCtypecase clVdecl(_ap)
{ clObject L_form, L_ignored, keyform, clauses;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top502;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top502, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(keyform, L_top502); }
    else clSetq(keyform, clMissingArgs(I_1, clEOA));
    clSetq(clauses, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject block;
    clSetq(block, clGensym(STR_CTYPECASE__7, clEOA));
    { clObject L_2;
      { clObject L_2__R1;
        { clObject L_2__R2;
          { clObject L_2__R3;
            { clObject L_1__R4;
              { clObject L_0__R5;
                { clObject L_1__R5;
                  { clObject L_2__R5;
                    { clObject L_3, L_1__R7;
                      clSetq(L_1__R7, clList(clQUOTE, keyform, clEOA));
                      { clObject L_1__R8;
                        { clObject L_1__R9;
                          { clObject L_0__R11;
                            clSetq(L_0__R11,
                                   clSymbolFunctionValue(clFIRST));
                            clSetq(L_1__R9,
                                   clMapcar(L_0__R11,
                                            clauses,
                                            clEOA)); }
                          clSetq(L_1__R8,
                                 clListSTAR(clOR, L_1__R9, clEOA)); }
                        clSetq(L_3, clList(clQUOTE, L_1__R8, clEOA)); }
                      clSetq(L_2__R5,
                             clListSTAR(clCHECK_TYPE_ERROR,
                                        L_1__R7,
                                        keyform,
                                        L_3,
                                        CONS_0,
                                        clEOA)); }
                    clSetq(L_1__R5,
                           clList(clSETF, keyform, L_2__R5, clEOA)); }
                  clSetq(L_0__R5,
                         clList(clOTHERWISE,
                                L_1__R5,
                                clList(clGO, block, clEOA),
                                clEOA)); }
                clSetq(L_1__R4, clList(L_0__R5, clEOA)); }
              clSetq(L_2__R3, clAppend(clauses, L_1__R4, clEOA)); }
            clSetq(L_2__R2,
                   clListSTAR(clTYPECASE, keyform, L_2__R3, clEOA)); }
          clSetq(L_2__R1,
                 clList(clRETURN_FROM, block, L_2__R2, clEOA)); }
        clSetq(L_2, clList(clTAGBODY, block, L_2__R1, clEOA)); }
      return(clList(clBLOCK, block, L_2, clEOA)); } } }

clObject clCcase clVdecl(_ap)
{ clObject L_form, env, keyform, clauses;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(env,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top505;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top505, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(keyform, L_top505); }
    else clSetq(keyform, clMissingArgs(I_1, clEOA));
    clSetq(clauses, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject block, types;
    clSetq(block, clGensym(STR_CCASE__8, clEOA));
    clSetq(types, clCaseKeys(clauses, env, clEOA));
    { clObject L_2;
      { clObject L_2__R1;
        { clObject L_2__R2;
          { clObject L_2__R3;
            { clObject L_1__R4;
              { clObject L_0__R5;
                { clObject L_1__R5;
                  { clObject L_2__R5;
                    { clObject L_3, L_1__R7;
                      clSetq(L_1__R7, clList(clQUOTE, keyform, clEOA));
                      clSetq(L_3,
                             clList(clQUOTE,
                                    clListSTAR(clMEMBER, types, clEOA),
                                    clEOA));
                      clSetq(L_2__R5,
                             clListSTAR(clCHECK_TYPE_ERROR,
                                        L_1__R7,
                                        keyform,
                                        L_3,
                                        CONS_0,
                                        clEOA)); }
                    clSetq(L_1__R5,
                           clList(clSETF, keyform, L_2__R5, clEOA)); }
                  clSetq(L_0__R5,
                         clList(clOTHERWISE,
                                L_1__R5,
                                clList(clGO, block, clEOA),
                                clEOA)); }
                clSetq(L_1__R4, clList(L_0__R5, clEOA)); }
              clSetq(L_2__R3, clAppend(clauses, L_1__R4, clEOA)); }
            clSetq(L_2__R2,
                   clListSTAR(clCASE, keyform, L_2__R3, clEOA)); }
          clSetq(L_2__R1,
                 clList(clRETURN_FROM, block, L_2__R2, clEOA)); }
        clSetq(L_2, clList(clTAGBODY, block, L_2__R1, clEOA)); }
      return(clList(clBLOCK, block, L_2, clEOA)); } } }

clObject clIgnoreErrors clVdecl(_ap)
{ clObject L_form, L_ignored, forms;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    clSetq(forms, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    clSetq(L_1, clListSTAR(clPROGN, forms, clEOA));
    return(clListSTAR(clHANDLER_CASE, L_1, CONS_3, clEOA)); } }

clObject clMakeConditionBindings clVdecl(_ap)
{ clObject bindings, constructor;
  { clBeginParse(_ap);
    clSetq(bindings,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(constructor,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject name, function, args, L_g3;
    clSetq(name, clNIL);
    clSetq(function, clNIL);
    clSetq(args, clNIL);
    clSetq(L_g3, bindings);
    { clObject L_g4, L_g5;
      clSetq(L_g4, clList(clNIL, clEOA));
      clSetq(L_g5, L_g4);
      clLabel(NEXT_LOOP);
      if (clTrue(clEndp(L_g3, clEOA))) goto END_LOOP;
      { clObject L_loop_desetq_temp;
        clSetq(L_loop_desetq_temp, clCar(L_g3, clEOA));
        clSetq(name, clCar(L_loop_desetq_temp, clEOA));
        { clObject L_0;
          clSetq(L_0, L_loop_desetq_temp);
          clSetq(L_loop_desetq_temp, clCdr(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_loop_desetq_temp);
          clSetq(function, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_loop_desetq_temp);
          clSetq(L_loop_desetq_temp, clCdr(L_0, clEOA)); }
        clSetq(args, L_loop_desetq_temp); }
      { clObject L_0;
        clSetq(L_0, L_g3);
        clSetq(L_g3, clCdr(L_0, clEOA)); }
      { clObject L_1, L_0;
        clSetq(L_0, L_g5);
        { clObject L_0__R1;
          { clObject L_3, L_2, L_1__R1;
            { clObject L_1__R2;
              clSetq(L_1__R2, name);
              clSetq(L_1__R1, clList(clQUOTE, L_1__R2, clEOA)); }
            clSetq(L_2, function);
            clSetq(L_3, args);
            clSetq(L_0__R1,
                   clListSTAR(constructor,
                              L_1__R1,
                              L_2,
                              L_3,
                              clEOA)); }
          clSetq(L_1, clSetq(L_g5, clList(L_0__R1, clEOA))); }
        clRplacd(L_0, L_1, clEOA); }
      goto NEXT_LOOP;
      clLabel(END_LOOP);
      return(clCdr(L_g4, clEOA));
      return(clValues1(clNIL)); } } }

clObject clHandlerBind clVdecl(_ap)
{ clObject L_form, L_ignored, bindings, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top510;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top510, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(bindings, L_top510); }
    else clSetq(bindings, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    { clObject L_0__R1;
      { clObject L_1__R1;
        { clObject L_1__R2;
          clSetq(L_1__R2,
                 clListSTAR(clLIST,
                            clMakeConditionBindings(bindings,
                                                    clMAKE_HANDLER,
                                                    clEOA),
                            clEOA));
          clSetq(L_1__R1,
                 clListSTAR(clCONS, L_1__R2, CONS_9, clEOA)); }
        clSetq(L_0__R1, clList(clstarHANDLERSstar, L_1__R1, clEOA)); }
      clSetq(L_1, clList(L_0__R1, clEOA)); }
    return(clListSTAR(clLET, L_1, CONS_10, body, clEOA)); } }

clObject clRestartBind clVdecl(_ap)
{ clObject L_form, L_ignored, restarts, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top513;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top513, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(restarts, L_top513); }
    else clSetq(restarts, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    { clObject L_0__R1;
      { clObject L_1__R1;
        { clObject L_1__R2;
          clSetq(L_1__R2,
                 clListSTAR(clLIST,
                            clMakeConditionBindings(restarts,
                                                    clMAKE_RESTART,
                                                    clEOA),
                            clEOA));
          clSetq(L_1__R1,
                 clListSTAR(clCONS, L_1__R2, CONS_13, clEOA)); }
        clSetq(L_0__R1, clList(clstarRESTARTSstar, L_1__R1, clEOA)); }
      clSetq(L_1, clList(L_0__R1, clEOA)); }
    return(clListSTAR(clLET, L_1, CONS_14, body, clEOA)); } }

clObject clWithSimpleRestart clVdecl(_ap)
{ clObject L_form, L_ignored, L_g514, restart_name, format_control,
  format_arguments, forms;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top517;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top517, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g514, L_top517); }
    else clSetq(L_g514, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g514))
      { clObject L_top518;
        clSetq(L_top518, clCar(L_g514, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g514);
          clSetq(L_g514, clCdr(L_0, clEOA)); }
        clSetq(restart_name, L_top518); }
    else clSetq(restart_name, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g514))
      { clObject L_top519;
        { clObject L_0;
          clSetq(L_0, L_g514);
          clSetq(L_top519, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g514);
          clSetq(L_g514, clCdr(L_0, clEOA)); }
        clSetq(format_control, L_top519); }
    else clSetq(format_control, clMissingArgs(I_3, clEOA));
    clSetq(format_arguments, L_g514);
    clSetq(forms, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_2, L_1;
    clSetq(L_1, clListSTAR(clPROGN, forms, clEOA));
    { clObject L_3;
      clSetq(L_3,
             clList(clLAMBDA, CONS_17,
                    clListSTAR(clFORMAT,
                               clS,
                               format_control,
                               format_arguments,
                               clEOA),
                    clEOA));
      clSetq(L_2,
             clListSTAR(restart_name,
                        clNIL,
                        keyREPORT,
                        L_3,
                        CONS_18,
                        clEOA)); }
    return(clList(clRESTART_CASE, L_1, L_2, clEOA)); } }

clObject clWithConditionRestarts clVdecl(_ap)
{ clObject L_form, L_ignored, condition_form, restarts_form, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top522;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top522, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(condition_form, L_top522); }
    else clSetq(condition_form, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top523;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top523, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(restarts_form, L_top523); }
    else clSetq(restarts_form, clMissingArgs(I_2, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject old_associations;
    clSetq(old_associations, clGensym(STR_OLD_ASSOCIATIONS__9, clEOA));
    { clObject L_2, L_1;
      clSetq(L_1,
             clList(clList(old_associations,
                           clList(clASSOCIATE_CONDITIONS,
                                  condition_form,
                                  restarts_form,
                                  clEOA),
                           clEOA),
                    clEOA));
      { clObject L_1__R1;
        clSetq(L_1__R1, clListSTAR(clPROGN, body, clEOA));
        clSetq(L_2,
               clList(clUNWIND_PROTECT,
                      L_1__R1,
                      clList(clDISASSOCIATE_CONDITIONS,
                             old_associations,
                             clEOA),
                      clEOA)); }
      return(clList(clLET, L_1, L_2, clEOA)); } } }

clObject clHandlerCaseBody clVdecl(_ap)
{ clObject temp, vars, body;
  { clBeginParse(_ap);
    clSetq(temp,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(vars,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(body,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_1;
    if (clTrue(vars))
      { clObject L_0__R1;
        { clObject L_0__R2;
          clSetq(L_0__R2, clFirst(vars, clEOA));
          clSetq(L_0__R1, clList(L_0__R2, temp, clEOA)); }
        clSetq(L_1, clList(L_0__R1, clEOA)); }
    else clSetq(L_1, clNIL);
    return(clListSTAR(clLET, L_1, body, clEOA)); } }

clObject clRestartCaseBody clVdecl(_ap)
{ clObject temp, vars, body;
  { clBeginParse(_ap);
    clSetq(temp,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(vars,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(body,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  clLabel(l_LOOP6);
  { clObject L_test;
    { clObject L_item524;
      clSetq(L_item524, clCar(body, clEOA));
      clSetq(L_test,
             (_clEq(L_item524, keyTEST) ? CONS_22 :
              (_clEq(L_item524, keyREPORT) ? CONS_23 :
               (_clEq(L_item524, keyINTERACTIVE) ? CONS_24 :
                clNIL)))); }
    if (clTrue(L_test))
      { clObject L_0;
        clSetq(L_0, body);
        clSetq(body, clCddr(L_0, clEOA)); }
    else clLocalReturn(NIL); }
  goto l_LOOP6;
  clBlockEnd(NIL);
  { clObject L_3;
    clSetq(L_3, body);
    return(clListSTAR(clDESTRUCTURING_BIND,
                      vars,
                      temp,
                      L_3,
                      clEOA)); } }

clDeclareEnv(clBindFormFromCase_Lambda);
static clObject clBindFormFromCase_Lambda clVdecl(_ap)
{ clUseEnv(clBindFormFromCase_Lambda);
  { clObject binding;
    { clBeginParse(_ap);
      clSetq(binding,
             (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
      if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
      clEndParse(_ap); }
    { clObject L_form525, name, vars, body;
      clSetq(L_form525, binding);
      if (clTrue(L_form525))
        { clObject L_top526;
          clSetq(L_top526, clCar(L_form525, clEOA));
          { clObject L_0;
            clSetq(L_0, L_form525);
            clSetq(L_form525, clCdr(L_0, clEOA)); }
          clSetq(name, L_top526); }
      else clSetq(name, clMissingArgs(I_1, clEOA));
      if (clTrue(L_form525))
        { clObject L_top527;
          { clObject L_0;
            clSetq(L_0, L_form525);
            clSetq(L_top527, clCar(L_0, clEOA)); }
          { clObject L_0;
            clSetq(L_0, L_form525);
            clSetq(L_form525, clCdr(L_0, clEOA)); }
          clSetq(vars, L_top527); }
      else clSetq(vars, clMissingArgs(I_2, clEOA));
      clSetq(body, L_form525);
      { clObject label;
        clSetq(label, clGensym(clEOA));
        clSetq(clEnv(0, *labels),
               clAppend(clEnv(0, *labels),
                        clList(label,
                               clList(clRETURN_FROM,
                                      clEnv(1, *block),
                                      clFuncall(clEnv(2, *body_fn),
                                                clEnv(3, *temp),
                                                vars,
                                                body,
                                                clEOA),
                                      clEOA),
                               clEOA),
                        clEOA));
        { clObject L_2, L_1;
          { clObject L_1__R1;
            { clObject L_2__R1, L_1__R2;
              clSetq(L_1__R2,
                     clAppend(clEnv(4, *args_restp), CONS_25, clEOA));
              clSetq(L_2__R1,
                     clListSTAR(clSETQ,
                                clEnv(3, *temp),
                                CONS_25,
                                clEOA));
              clSetq(L_1__R1,
                     clList(clLAMBDA,
                            L_1__R2,
                            L_2__R1,
                            clList(clGO, label, clEOA),
                            clEOA)); }
            clSetq(L_1, clList(clFUNCTION, L_1__R1, clEOA)); }
          clSetq(L_2,
                 (clTrue(clEnv(5, *options_fn)) ?
                  clFuncall(clEnv(5, *options_fn),
                            name,
                            body,
                            clEnv(6, *options_fn_extra_arg),
                            clEOA) :
                  clNIL));
          return(clListSTAR(name, L_1, L_2, clEOA)); } } } } }

clObject clBindFormFromCase clVdecl(_ap)
{ clObject binder, expression, bindings, *options_fn = clMakeBinding(),
  *body_fn = clMakeBinding(), *args_restp = clMakeBinding(),
  *options_fn_extra_arg = clMakeBinding(), *block = clMakeBinding(),
  *temp = clMakeBinding(), *labels = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(binder,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(expression,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(bindings,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(*options_fn,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    clSetq(*body_fn,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_5, clEOA)));
    clSetq(*args_restp,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_6, clEOA)));
    clSetq(*options_fn_extra_arg,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_7, clEOA)));
    clSetq(*block, clGensym(clSymbolName(binder, clEOA), clEOA));
    clSetq(*temp, clGensym(STR_VALUES__12, clEOA));
    clSetq(*labels, clNIL);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_2, L_1;
    clSetq(L_1, *block);
    { clObject L_2__R1, L_1__R1;
      clSetq(L_1__R1, clList(clListSTAR(*temp, CONS_0, clEOA), clEOA));
      { clObject L_2__R2, L_1__R2;
        { clObject L_2__R3, L_1__R3;
          { clObject L_0__R4;
            clSetq(L_0__R4,
                   clMakeClosure(7,
                                 clBindFormFromCase_Lambda,
                                 &clEnvHook(clBindFormFromCase_Lambda),
                                 &*labels,
                                 &*block,
                                 &*body_fn,
                                 &*temp,
                                 &*args_restp,
                                 &*options_fn,
                                 &*options_fn_extra_arg));
            clSetq(L_1__R3, clMapcar(L_0__R4, bindings, clEOA)); }
          { clObject L_1__R4;
            clSetq(L_1__R4, *block);
            clSetq(L_2__R3,
                   clList(clRETURN_FROM,
                          L_1__R4,
                          expression,
                          clEOA)); }
          clSetq(L_1__R2, clList(binder, L_1__R3, L_2__R3, clEOA)); }
        clSetq(L_2__R2, *labels);
        clSetq(L_2__R1,
               clListSTAR(clTAGBODY, L_1__R2, L_2__R2, clEOA)); }
      clSetq(L_2, clList(clLET, L_1__R1, L_2__R1, clEOA)); }
    return(clList(clBLOCK, L_1, L_2, clEOA)); } }

clObject clHandlerCase clVdecl(_ap)
{ clObject L_form, L_ignored, expression, bindings;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top530;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top530, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(expression, L_top530); }
    else clSetq(expression, clMissingArgs(I_1, clEOA));
    clSetq(bindings, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject last_clause;
    clSetq(last_clause, clCar(clLast(bindings, clEOA), clEOA));
    { clObject L_test;
      { clObject L_0;
        clSetq(L_0, clCar(last_clause, clEOA));
        clSetq(L_test, clEq(L_0, keyNO_ERROR, clEOA)); }
      if (clTrue(L_test))
        { clObject error_return, normal_return;
          clSetq(error_return, clGensym(STR_NO_ERROR__13, clEOA));
          clSetq(normal_return,
                 clGensym(STR_NORMAL_RETURN__14, clEOA));
          { clObject L_2;
            { clObject L_2__R1, L_1__R1;
              clSetq(L_1__R1,
                     clList(clFUNCTION,
                            clListSTAR(clLAMBDA,
                                       clRest(last_clause, clEOA),
                                       clEOA),
                            clEOA));
              { clObject L_2__R2;
                { clObject L_2__R3;
                  { clObject L_1__R4;
                    clSetq(L_1__R4,
                           clList(clRETURN_FROM,
                                  normal_return,
                                  expression,
                                  clEOA));
                    clSetq(L_2__R3,
                           clListSTAR(clHANDLER_CASE,
                                      L_1__R4,
                                      clButlast(bindings, clEOA),
                                      clEOA)); }
                  clSetq(L_2__R2,
                         clList(clRETURN_FROM,
                                error_return,
                                L_2__R3,
                                clEOA)); }
                clSetq(L_2__R1,
                       clList(clBLOCK,
                              normal_return,
                              L_2__R2,
                              clEOA)); }
              clSetq(L_2,
                     clList(clMULTIPLE_VALUE_CALL,
                            L_1__R1,
                            L_2__R1,
                            clEOA)); }
            return(clList(clBLOCK, error_return, L_2, clEOA)); } }
      else
        { clObject L_4;
          clSetq(L_4, clSymbolFunctionValue(clHANDLER_CASE_BODY));
          return(clBindFormFromCase(clHANDLER_BIND,
                                    expression,
                                    bindings,
                                    clNIL,
                                    L_4,
                                    clNIL,
                                    clNIL,
                                    clEOA)); } } } }

clObject clRestartCase clVdecl(_ap)
{ clObject L_form, env, expression, bindings;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(env,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top533;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top533, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(expression, L_top533); }
    else clSetq(expression, clMissingArgs(I_1, clEOA));
    clSetq(bindings, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject expression__R1, signaller, condition_var, exp, form;
    clSetq(expression__R1, clMacroexpand(expression, env, clEOA));
    clSetq(signaller,
           (clTrue(clConsp(expression__R1, clEOA)) ?
            clCar(expression__R1, clEOA) : clNIL));
    { clObject L_test;
      { clObject L_item534;
        clSetq(L_item534, signaller);
        clSetq(L_test,
               (_clEq(L_item534, clSIGNAL) ? CONS_26 :
                (_clEq(L_item534, clERROR) ? CONS_27 :
                 (_clEq(L_item534, clCERROR) ? CONS_28 :
                  (_clEq(L_item534, clWARN) ? CONS_29 : clNIL))))); }
      clSetq(condition_var,
             (clTrue(L_test) ? clGensym(STR_CONDITION__4, clEOA) :
              clNIL)); }
    if (clTrue(condition_var))
      { clObject L_1, L_0;
        clSetq(L_0, signaller);
        clSetq(L_1, condition_var);
        clSetq(exp, clList(L_0, L_1, clEOA)); }
    else clSetq(exp, expression__R1);
    { clObject L_6, L_4, L_3, L_1;
      clSetq(L_1, exp);
      clSetq(L_3, clSymbolFunctionValue(clRESTART_CASE_OPTIONS));
      clSetq(L_4, clSymbolFunctionValue(clRESTART_CASE_BODY));
      clSetq(L_6, condition_var);
      clSetq(form,
             clBindFormFromCase(clRESTART_BIND,
                                L_1,
                                bindings,
                                L_3,
                                L_4,
                                CONS_30,
                                L_6,
                                clEOA)); }
    if (clTrue(condition_var))
      { clObject L_1;
        { clObject L_0__R1;
          { clObject L_1__R1, L_0__R2;
            clSetq(L_0__R2, condition_var);
            { clObject L_3, L_2__R1, L_1__R2;
              clSetq(L_1__R2, clSecond(expression__R1, clEOA));
              clSetq(L_2__R1,
                     clListSTAR(clLIST,
                                clCddr(expression__R1, clEOA),
                                clEOA));
              { clObject L_1__R3;
                { clObject L_key535;
                  clSetq(L_key535, signaller);
                  clSetq(L_1__R3,
                         (_clEq(L_key535, clWARN) ?
                          clSIMPLE_WARNING :
                          (_clEq(L_key535, clSIGNAL) ?
                           clSIMPLE_CONDITION :
                           (clTrue((_clEq(L_key535, clERROR) ?
                                    CONS_31 :
                                    (_clEq(L_key535, clCERROR) ?
                                     CONS_32 :
                                     clNIL))) ?
                            clSIMPLE_ERROR :
                            clNIL)))); }
                clSetq(L_3, clList(clQUOTE, L_1__R3, clEOA)); }
              clSetq(L_1__R1,
                     clList(clCANONICALIZE_CONDITION,
                            L_1__R2,
                            L_2__R1,
                            L_3,
                            clEOA)); }
            clSetq(L_0__R1, clList(L_0__R2, L_1__R1, clEOA)); }
          clSetq(L_1, clList(L_0__R1, clEOA)); }
        return(clList(clLET, L_1, form, clEOA)); }
    else return(clValues1(form)); } }

clDeclareEnv(clRestartCaseOptions_AddOpt);
static clObject clRestartCaseOptions_AddOpt clVdecl(_ap)
{ clUseEnv(clRestartCaseOptions_AddOpt);
  { clObject name, val;
    { clBeginParse(_ap);
      clSetq(name,
             (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
      clSetq(val,
             (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
      if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
      clEndParse(_ap); }
    return(clValues1(clSetq(clEnv(0, *options),
                            clAppend(clEnv(0, *options),
                                     clList(name,
                                            clList(clFUNCTION,
                                                   val,
                                                   clEOA),
                                            clEOA),
                                     clEOA)))); } }

clDeclareEnv(clRestartCaseOptions_Done);
static clObject clRestartCaseOptions_Done clVdecl(_ap)
{ clUseEnv(clRestartCaseOptions_Done);
  { { clBeginParse(_ap);
      if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
      clEndParse(_ap); }
    { clObject L_test;
      { clObject L_0;
        clSetq(L_0,
               (clTrue(clEnv(0, *name)) ? clEnv(0, *name) :
                clEnv(1, *reportp)));
        clSetq(L_test, clNot(L_0, clEOA)); }
      if (clTrue(L_test)) clWarn(STRn_15, clEnv(2, *body), clEOA); }
    if (clTrue(clEnv(4, *condition)))
      { clObject L_2, L_1;
        clSetq(L_1, clList(clLIST, clEnv(4, *condition), clEOA));
        clSetq(L_2, clEnv(5, *options));
        clReturnFrom(clEnv(3, RESTART_CASE_OPTIONS),
                     clListSTAR(keyASSOCIATED_CONDITIONS,
                                L_1,
                                L_2,
                                clEOA)); }
    else
      clReturnFrom(clEnv(3, RESTART_CASE_OPTIONS),
                   clValues1(clEnv(5, *options)));
    return(clValues1(clNIL)); } }

clObject clRestartCaseOptions clVdecl(_ap)
{ clObject *name = clMakeBinding(), *body = clMakeBinding(),
  *condition = clMakeBinding(), *options = clMakeBinding(),
  *reportp = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*name,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*body,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(*condition,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(*options, clNIL);
    clSetq(*reportp, clNIL);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clBlock(RESTART_CASE_OPTIONS);
    if (clTrue(clReturned(RESTART_CASE_OPTIONS)))
      return(clSavedValue(RESTART_CASE_OPTIONS));
    else
      { clObject _Done_, _AddOpt_;
        clSetq(_AddOpt_,
               clMakeClosure(1,
                             clRestartCaseOptions_AddOpt,
                             &clEnvHook(clRestartCaseOptions_AddOpt),
                             &*options));
        clSetq(_Done_,
               clMakeClosure(6,
                             clRestartCaseOptions_Done,
                             &clEnvHook(clRestartCaseOptions_Done),
                             &*name,
                             &*reportp,
                             &*body,
                             &RESTART_CASE_OPTIONS,
                             &*condition,
                             &*options));
        { clObject L_g7, key, val;
          clSetq(L_g7, *body);
          clSetq(key, clNIL);
          clSetq(val, clNIL);
          clLabel(NEXT_LOOP);
          if (clTrue(clAtom(L_g7, clEOA))) goto END_LOOP;
          { clObject L_loop_desetq_temp;
            clSetq(L_loop_desetq_temp, L_g7);
            clSetq(key, clCar(L_loop_desetq_temp, clEOA));
            { clObject L_0;
              clSetq(L_0, L_loop_desetq_temp);
              clSetq(L_loop_desetq_temp, clCdr(L_0, clEOA)); }
            { clObject L_0;
              clSetq(L_0, L_loop_desetq_temp);
              clSetq(val, clCar(L_0, clEOA)); } }
          { clObject L_0;
            clSetq(L_0, L_g7);
            clSetq(L_g7, clCddr(L_0, clEOA)); }
          { clObject L_key538;
            clSetq(L_key538, key);
            if (_clEq(L_key538, keyREPORT))
              { clSetq(*reportp, clT);
                { clObject L_1;
                  { clObject L_test__R1;
                    { clObject L_0__R1;
                      clSetq(L_0__R1, val);
                      clSetq(L_test__R1, clStringp(L_0__R1, clEOA)); }
                    if (clTrue(L_test__R1))
                      { clObject L_2;
                        { clObject L_1__R2;
                          clSetq(L_1__R2, val);
                          clSetq(L_2,
                                 clListSTAR(clWRITE_STRING,
                                            L_1__R2,
                                            CONS_17,
                                            clEOA)); }
                        clSetq(L_1,
                               clList(clLAMBDA,
                                      CONS_17,
                                      L_2,
                                      clEOA)); }
                    else clSetq(L_1, val); }
                  clFuncallFunction(_AddOpt_,
                                    keyREPORT_FUNCTION,
                                    L_1,
                                    clEOA); } }
            else if (_clEq(L_key538, keyINTERACTIVE))
              { clObject L_1;
                clSetq(L_1, val);
                clFuncallFunction(_AddOpt_,
                                  keyINTERACTIVE_FUNCTION,
                                  L_1,
                                  clEOA); }
            else if (_clEq(L_key538, keyTEST))
              { clObject L_1;
                clSetq(L_1, val);
                clFuncallFunction(_AddOpt_,
                                  keyTEST_FUNCTION,
                                  L_1,
                                  clEOA); }
            else clFuncallFunction(_Done_, clEOA); }
          goto NEXT_LOOP;
          clLabel(END_LOOP);
          clFuncallFunction(_Done_, clEOA);
          return(clValues1(clNIL)); } } } }

void clInitCondComp __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(STR_VALUE__0,
         clCharpSimpleBaseString("VALUE"));
  clSetq(STR_CHECK_TYPE__1,
         clCharpSimpleBaseString("CHECK-TYPE"));
  clSetq(CONS_0, clCons(clNIL, clNIL, clEOA));
  clSetq(I_3, clIntFixnum(3));
  clSetq(STR_REPORT__2,
         clCharpSimpleBaseString("REPORT"));
  clSetq(keyREPORT, clMakeKeyword(STR_REPORT__2, clEOA));
  clSetq(STR_KEY__3,
         clCharpSimpleBaseString("KEY"));
  clSetq(keyKEY, clMakeKeyword(STR_KEY__3, clEOA));
  clSetq(CONS_1, clCons(clCONDITION, clNIL, clEOA));
  clSetq(STR_CONDITION__4,
         clCharpSimpleBaseString("CONDITION"));
  clSetq(STR_STREAM__5,
         clCharpSimpleBaseString("STREAM"));
  clSetq(CONS_2, clCons(clCALL_NEXT_METHOD, clNIL, clEOA));
  clSetq(STR_ASSERT__6,
         clCharpSimpleBaseString("ASSERT"));
  clSetq(STR_CTYPECASE__7,
         clCharpSimpleBaseString("CTYPECASE"));
  clSetq(STR_CCASE__8,
         clCharpSimpleBaseString("CCASE"));
  clSetq(CONS_8, clCons(clNIL, CONS_1, clEOA));
  clSetq(CONS_7, clCons(clVALUES, CONS_8, clEOA));
  clSetq(CONS_6, clCons(CONS_7, clNIL, clEOA));
  clSetq(CONS_5, clCons(CONS_1, CONS_6, clEOA));
  clSetq(CONS_4, clCons(clERROR, CONS_5, clEOA));
  clSetq(CONS_3, clCons(CONS_4, clNIL, clEOA));
  clSetq(CONS_9, clCons(clstarHANDLERSstar, clNIL, clEOA));
  clSetq(CONS_12, clCons(clDYNAMIC_EXTENT, CONS_9, clEOA));
  clSetq(CONS_11, clCons(CONS_12, clNIL, clEOA));
  clSetq(CONS_10, clCons(clDECLARE, CONS_11, clEOA));
  clSetq(CONS_13, clCons(clstarRESTARTSstar, clNIL, clEOA));
  clSetq(CONS_16, clCons(clDYNAMIC_EXTENT, CONS_13, clEOA));
  clSetq(CONS_15, clCons(CONS_16, clNIL, clEOA));
  clSetq(CONS_14, clCons(clDECLARE, CONS_15, clEOA));
  clSetq(CONS_17, clCons(clS, clNIL, clEOA));
  clSetq(CONS_21, clCons(clT, clNIL, clEOA));
  clSetq(CONS_20, clCons(clNIL, CONS_21, clEOA));
  clSetq(CONS_19, clCons(clVALUES, CONS_20, clEOA));
  clSetq(CONS_18, clCons(CONS_19, clNIL, clEOA));
  clSetq(STR_OLD_ASSOCIATIONS__9,
         clCharpSimpleBaseString("OLD-ASSOCIATIONS"));
  clSetq(STR_TEST__10,
         clCharpSimpleBaseString("TEST"));
  clSetq(keyTEST, clMakeKeyword(STR_TEST__10, clEOA));
  clSetq(STR_INTERACTIVE__11,
         clCharpSimpleBaseString("INTERACTIVE"));
  clSetq(keyINTERACTIVE, clMakeKeyword(STR_INTERACTIVE__11, clEOA));
  clSetq(CONS_24, clCons(keyINTERACTIVE, clNIL, clEOA));
  clSetq(CONS_23, clCons(keyREPORT, CONS_24, clEOA));
  clSetq(CONS_22, clCons(keyTEST, CONS_23, clEOA));
  clSetq(I_4, clIntFixnum(4));
  clSetq(I_5, clIntFixnum(5));
  clSetq(I_6, clIntFixnum(6));
  clSetq(I_7, clIntFixnum(7));
  clSetq(STR_VALUES__12,
         clCharpSimpleBaseString("VALUES"));
  clSetq(CONS_25, clCons(clTEMP, clNIL, clEOA));
  clSetq(STR_NO_ERROR__13,
         clCharpSimpleBaseString("NO-ERROR"));
  clSetq(keyNO_ERROR, clMakeKeyword(STR_NO_ERROR__13, clEOA));
  clSetq(STR_NORMAL_RETURN__14,
         clCharpSimpleBaseString("NORMAL-RETURN"));
  clSetq(CONS_29, clCons(clWARN, clNIL, clEOA));
  clSetq(CONS_28, clCons(clCERROR, CONS_29, clEOA));
  clSetq(CONS_27, clCons(clERROR, CONS_28, clEOA));
  clSetq(CONS_26, clCons(clSIGNAL, CONS_27, clEOA));
  clSetq(CONS_30, clCons(clampersandREST, clNIL, clEOA));
  clSetq(CONS_32, clCons(clCERROR, clNIL, clEOA));
  clSetq(CONS_31, clCons(clERROR, CONS_32, clEOA));
  clSetq(STRn_15,
         clCharpSimpleBaseString("No report option specified for anonymous restart ~s."));
  clSetq(STRn_16,
         clCharpSimpleBaseString("ASSOCIATED-CONDITIONS"));
  clSetq(keyASSOCIATED_CONDITIONS, clMakeKeyword(STRn_16, clEOA));
  clSetq(STR_REPORT_FUNCTION__17,
         clCharpSimpleBaseString("REPORT-FUNCTION"));
  clSetq(keyREPORT_FUNCTION,
         clMakeKeyword(STR_REPORT_FUNCTION__17, clEOA));
  clSetq(STRn_18,
         clCharpSimpleBaseString("INTERACTIVE-FUNCTION"));
  clSetq(keyINTERACTIVE_FUNCTION, clMakeKeyword(STRn_18, clEOA));
  clSetq(STR_TEST_FUNCTION__19,
         clCharpSimpleBaseString("TEST-FUNCTION"));
  clSetq(keyTEST_FUNCTION,
         clMakeKeyword(STR_TEST_FUNCTION__19, clEOA));


  { clObject L_value484;
    clSetq(L_value484, clMakeClosure(0, clCheckType, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value484, clCHECK_TYPE, clEOA); }
  (void) clCHECK_TYPE;
  { clObject L_value489;
    clSetq(L_value489,
           clMakeClosure(0, clDefineCondition, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value489, clDEFINE_CONDITION, clEOA); }
  (void) clDEFINE_CONDITION;
  { clObject L_value495;
    clSetq(L_value495, clMakeClosure(0, clAssert, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value495, clASSERT, clEOA); }
  (void) clASSERT;
  { clObject L_value500;
    clSetq(L_value500, clMakeClosure(0, clCtypecase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value500, clCTYPECASE, clEOA); }
  (void) clCTYPECASE;
  { clObject L_value503;
    clSetq(L_value503, clMakeClosure(0, clCcase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value503, clCCASE, clEOA); }
  (void) clCCASE;
  { clObject L_value506;
    clSetq(L_value506, clMakeClosure(0, clIgnoreErrors, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value506, clIGNORE_ERRORS, clEOA); }
  (void) clIGNORE_ERRORS;
  clSetSymbolFunctionValue(clMAKE_CONDITION_BINDINGS,
                           clMakeClosure(0,
                                         clMakeConditionBindings,
                                         clNULL_HOOK));
  (void) clMAKE_CONDITION_BINDINGS;
  { clObject L_value508;
    clSetq(L_value508, clMakeClosure(0, clHandlerBind, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value508, clHANDLER_BIND, clEOA); }
  (void) clHANDLER_BIND;
  { clObject L_value511;
    clSetq(L_value511, clMakeClosure(0, clRestartBind, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value511, clRESTART_BIND, clEOA); }
  (void) clRESTART_BIND;
  { clObject L_value515;
    clSetq(L_value515,
           clMakeClosure(0, clWithSimpleRestart, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value515, clWITH_SIMPLE_RESTART, clEOA); }
  (void) clWITH_SIMPLE_RESTART;
  { clObject L_value520;
    clSetq(L_value520,
           clMakeClosure(0, clWithConditionRestarts, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value520,
                          clWITH_CONDITION_RESTARTS,
                          clEOA); }
  (void) clWITH_CONDITION_RESTARTS;
  clSetSymbolFunctionValue(clHANDLER_CASE_BODY,
                           clMakeClosure(0,
                                         clHandlerCaseBody,
                                         clNULL_HOOK));
  (void) clHANDLER_CASE_BODY;
  clSetSymbolFunctionValue(clRESTART_CASE_BODY,
                           clMakeClosure(0,
                                         clRestartCaseBody,
                                         clNULL_HOOK));
  (void) clRESTART_CASE_BODY;
  clSetSymbolFunctionValue(clBIND_FORM_FROM_CASE,
                           clMakeClosure(0,
                                         clBindFormFromCase,
                                         clNULL_HOOK));
  (void) clBIND_FORM_FROM_CASE;
  { clObject L_value528;
    clSetq(L_value528, clMakeClosure(0, clHandlerCase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value528, clHANDLER_CASE, clEOA); }
  (void) clHANDLER_CASE;
  { clObject L_value531;
    clSetq(L_value531, clMakeClosure(0, clRestartCase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value531, clRESTART_CASE, clEOA); }
  (void) clRESTART_CASE;
  clSetSymbolFunctionValue(clRESTART_CASE_OPTIONS,
                           clMakeClosure(0,
                                         clRestartCaseOptions,
                                         clNULL_HOOK));
  (void) clRESTART_CASE_OPTIONS;
  clUnwind(4); }
