/* Generated by Eclipse Common Lisp 1.1-HOSTED for howard on circe.
   Friday the sixth of March, 1998, 9:24:53 pm CST. */
#include <eclipse.h>

clObject clAddInteger(clProto), clAppend(clProto), clCar(clProto),
  clCdr(clProto), clCharpSimpleBaseString __P((clCharp)),
  clCheckKeys(clProto), clCons(clProto), clConstantp(clProto),
  clCopyList(clProto), clDoBody(clProto), clEndp(clProto),
  clEq(clProto), clError(clProto), clExtraArgs(clProto),
  clFindDeclarations(clProto), clFirst(clProto), clGeInteger(clProto),
  clGenerateSetfMethod(clProto), clGensym(clProto),
  clGetSetfExpansion(clProto), clKeyArg(clProto), clLength(clProto),
  clList(clProto), clListSTAR(clProto), clListp(clProto),
  cl_SETF_MacroFunction(clProto), clMakeKeyword(clProto),
  clMakeSymbols(clProto), clMapcan(clProto), clMapcar(clProto),
  clMissingArgs(clProto), clNot(clProto), clNull(clProto),
  clRplacd(clProto), clSecond(clProto), cl_SETF_SetfExpander(clProto),
  clSignalProgramError(clProto), clThird(clProto), clValues(clProto);

extern clObject clBLOCK, clCONS, clDECLARE, clDYNAMIC_EXTENT, clEQ,
  clGO, clIGNORABLE, clIGNORE, clINTEGER, clLET, clLETstar,
  clMULTIPLE_VALUE_CALL, clMULTIPLE_VALUE_PROG1, clOTHERWISE, clPROGN,
  clQUOTE, clRETURN_FROM, clRPLACD, clSETQ, clSYMBOL, clTAGBODY,
  clTYPE, clADD_INTEGER, clATOM, clCAR, clCASE, clCDDR, clCDR,
  clCHARACTER, clCOND, clDO, clDOstar, clDO_BODY, clDOLIST, clDOTIMES,
  clECASE, clENDP, clERROR, clETYPECASE, clFIRST, clFUNCTION,
  clGE_INTEGER, clGET_OUTPUT_STREAM_STRING, clGETF, clINPUT_BUFFER,
  clINPUT_BUFFER_POSITION, clLIST, clMEMBER, clMULTIPLE_VALUE_BIND,
  clMULTIPLE_VALUE_LIST, clMULTIPLE_VALUE_SETQ, clNREVERSE, clNTH,
  clNTH_VALUE, clNULL, clOR, clOUTPUT_BUFFER, clOUTPUT_STREAM,
  clPRINT_UNREADABLE_OBJECT, clPRINT_UNREADABLE_OBJECT_HEADER,
  clPRINT_UNREADABLE_OBJECT_TRAILER, clPROG, clPROGstar, clPSETQ,
  clPUTF, clREMF, clRETURN, clSET_SYMBOL_PLIST, clSYMBOL_PLIST,
  clTYPE_ERROR, clTYPECASE, clUSING_RESOURCE, clVALUES, clWHEN,
  clWITH_INPUT_FROM_STRING, clWITH_OUTPUT_TO_STRING;

static clObject CONS_0, CONS_1, CONS_10, CONS_11, CONS_12, CONS_13,
  CONS_14, CONS_15, CONS_16, CONS_17, CONS_18, CONS_19, CONS_2,
  CONS_20, CONS_21, CONS_22, CONS_23, CONS_24, CONS_25, CONS_26,
  CONS_27, CONS_28, CONS_29, CONS_3, CONS_4, CONS_5, CONS_6, CONS_7,
  CONS_8, CONS_9, I_0, I_1, I_2, I_3, I_4, I_5, I_6, keyDATUM,
  keyELEMENT_TYPE, keyEND, keyEXPECTED_TYPE, keyFORMAT_ARGUMENTS,
  keyFORMAT_STRING, keyIDENTITY, keyINDEX, keySTART, keyTYPE,
  STR_DATUM__1, STR_DEF_TEMP__10, STR_ELEMENT_TYPE__17, STR_END__4,
  STR_EXPECTED_TYPE__2, STR_FORMAT_ARGUMENTS__16,
  STR_FORMAT_STRING__14, STR_IDENTITYP__25, STR_IDENTITY__21,
  STR_IGNORE___7, STR_IND_TEMP__11, STR_INDEX__18, STR_ITERATE__0,
  STR_KEEPER__6, STR_LOCAL__12, STR_NEWVAL__8,
  STR_No_clauses_in_tildesdot__15, STR_OBJECT__22, STR_PTEMP__9,
  STR_START__19, STR_STREAM__23, STR_SUBLIST__3, STR_TYPEP__24,
  STR_TYPE__20, STR_VALUES__5, STRn_13;

clObject clDoBody clVdecl(_ap)
{ clObject varlist, endlist, body, bind, step, block;
  { clBeginParse(_ap);
    clSetq(varlist,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(endlist,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(body,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(bind,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    clSetq(step,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_5, clEOA)));
    clSetq(block,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_6, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_values646, decl, code;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clFindDeclarations(body, clT, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values646, clMultipleValueFuncall(MVC)); }
    clSetq(decl, clCar(L_values646, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values646);
        clSetq(L_0, clSetq(L_values646, clCdr(L_0__R1, clEOA))); }
      clSetq(code, clCar(L_0, clEOA)); }
    { clObject inits, steps, l1;
      clSetq(inits, clNIL);
      clSetq(steps, clNIL);
      clSetq(l1, clGensym(STR_ITERATE__0, clEOA));
      { clObject L_sublist647, v;
        clSetq(L_sublist647, varlist);
        clSetq(v, clCar(L_sublist647, clEOA));
        clLabel(l_ITERATE648);
        if (clTrue(clEndp(L_sublist647, clEOA))) clLocalReturn(NIL);
        { clObject L_class_name651;
          clSetq(L_class_name651, clInstanceTag(v));
          if (clTrue((_clEq(L_class_name651, clSYMBOL) ?
                      CONS_0 :
                      (_clEq(L_class_name651, clNULL) ?
                       CONS_1 :
                       clNIL))))
            { clObject L_1;
              clSetq(L_1, inits);
              clSetq(inits, clCons(v, L_1, clEOA)); }
          else if (_clEq(L_class_name651, clCONS))
            { clObject L_g655;
              clSetq(L_g655, clLength(v, clEOA));
              if (_clEq(L_g655, I_1))
                { clObject L_1, L_0;
                  clSetq(L_0, clFirst(v, clEOA));
                  clSetq(L_1, inits);
                  clSetq(inits, clCons(L_0, L_1, clEOA)); }
              else if (_clEq(L_g655, I_2))
                { clObject L_1;
                  clSetq(L_1, inits);
                  clSetq(inits, clCons(v, L_1, clEOA)); }
              else if (_clEq(L_g655, I_3))
                { { clObject L_1, L_0;
                    { clObject L_0__R1;
                      clSetq(L_0__R1, clFirst(v, clEOA));
                      clSetq(L_0,
                             clList(L_0__R1,
                                    clSecond(v, clEOA),
                                    clEOA)); }
                    clSetq(L_1, inits);
                    clSetq(inits, clCons(L_0, L_1, clEOA)); }
                  { clObject L_2, L_1, L_0;
                    clSetq(L_0, clThird(v, clEOA));
                    clSetq(L_1, clFirst(v, clEOA));
                    clSetq(L_2, steps);
                    clSetq(steps,
                           clListSTAR(L_0, L_1, L_2, clEOA)); } }
              else
                clError(clTYPE_ERROR,
                        keyDATUM,
                        L_g655,
                        keyEXPECTED_TYPE,
                        CONS_2,
                        clEOA); }
          else
            clError(clTYPE_ERROR, keyDATUM, v, keyEXPECTED_TYPE,
                    CONS_6, clEOA); }
        { clObject L_0;
          clSetq(L_0, L_sublist647);
          clSetq(L_sublist647, clCdr(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_sublist647);
          clSetq(v, clCar(L_0, clEOA)); }
        goto l_ITERATE648; }
      clBlockEnd(NIL);
      { clObject L_2;
        { clObject L_3, L_2__R1, L_1__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2, inits);
            clSetq(L_1__R1,
                   clFuncallFunction(clSymbolFunctionValue(clNREVERSE),
                                     L_0__R2,
                                     clEOA)); }
          clSetq(L_2__R1, clListSTAR(clDECLARE, decl, clEOA));
          { clObject L_4, L_3__R1, L_2__R2;
            { clObject L_1__R3;
              clSetq(L_1__R3, clCar(endlist, clEOA));
              clSetq(L_2__R2,
                     clList(clWHEN,
                            L_1__R3,
                            clList(clRETURN_FROM,
                                   block,
                                   clListSTAR(clPROGN,
                                              clCdr(endlist, clEOA),
                                              clEOA),
                                   clEOA),
                            clEOA)); }
            clSetq(L_3__R1, clListSTAR(clTAGBODY, code, clEOA));
            { clObject L_1__R3;
              { clObject L_0__R4;
                clSetq(L_0__R4, steps);
                clSetq(L_1__R3,
                       clFuncallFunction(clSymbolFunctionValue(clNREVERSE),
                                         L_0__R4,
                                         clEOA)); }
              clSetq(L_4, clListSTAR(step, L_1__R3, clEOA)); }
            clSetq(L_3,
                   clList(clTAGBODY,
                          l1,
                          L_2__R2,
                          L_3__R1,
                          L_4,
                          clList(clGO, l1, clEOA),
                          clEOA)); }
          clSetq(L_2, clList(bind, L_1__R1, L_2__R1, L_3, clEOA)); }
        return(clList(clBLOCK, block, L_2, clEOA)); } } } }

clObject clDo clVdecl(_ap)
{ clObject L_form, L_ignored, varlist, endlist, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top659;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top659, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(varlist, L_top659); }
    else clSetq(varlist, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top660;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top660, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(endlist, L_top660); }
    else clSetq(endlist, clMissingArgs(I_2, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clDoBody(varlist, endlist, body, clLET, clPSETQ, clNIL,
                  clEOA)); }

clObject clDoSTAR clVdecl(_ap)
{ clObject L_form, L_ignored, varlist, endlist, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top663;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top663, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(varlist, L_top663); }
    else clSetq(varlist, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top664;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top664, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(endlist, L_top664); }
    else clSetq(endlist, clMissingArgs(I_2, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clDoBody(varlist, endlist, body, clLETstar, clSETQ, clNIL,
                  clEOA)); }

clObject clDolist clVdecl(_ap)
{ clObject L_form, L_ignored, L_g665, var, listform, resultform,
  tagbody;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top668;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top668, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g665, L_top668); }
    else clSetq(L_g665, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g665))
      { clObject L_top669;
        clSetq(L_top669, clCar(L_g665, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g665);
          clSetq(L_g665, clCdr(L_0, clEOA)); }
        clSetq(var, L_top669); }
    else clSetq(var, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g665))
      { clObject L_top670;
        { clObject L_0;
          clSetq(L_0, L_g665);
          clSetq(L_top670, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g665);
          clSetq(L_g665, clCdr(L_0, clEOA)); }
        clSetq(listform, L_top670); }
    else clSetq(listform, clMissingArgs(I_3, clEOA));
    if (clTrue(L_g665))
      { clObject L_top671;
        { clObject L_0;
          clSetq(L_0, L_g665);
          clSetq(L_top671, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g665);
          clSetq(L_g665, clCdr(L_0, clEOA)); }
        clSetq(resultform, L_top671); }
    else clSetq(resultform, clNIL);
    clSetq(tagbody, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_g665))
    { clObject L_0; clSetq(L_0, L_g665); clExtraArgs(L_0, clEOA); }
  { clObject list;
    clSetq(list, clGensym(STR_SUBLIST__3, clEOA));
    { clObject L_2, L_1;
      { clObject L_1__R1, L_0__R1;
        clSetq(L_0__R1,
               clList(list,
                      listform,
                      clList(clCDR, list, clEOA),
                      clEOA));
        { clObject L_1__R2;
          clSetq(L_1__R2, clList(clCAR, list, clEOA));
          clSetq(L_1__R1,
                 clList(var,
                        L_1__R2,
                        clList(clCAR, list, clEOA),
                        clEOA)); }
        clSetq(L_1, clList(L_0__R1, L_1__R1, clEOA)); }
      { clObject L_1__R1, L_0__R1;
        clSetq(L_0__R1, clList(clENDP, list, clEOA));
        clSetq(L_1__R1, resultform);
        clSetq(L_2, clList(L_0__R1, L_1__R1, clEOA)); }
      return(clListSTAR(clDOstar, L_1, L_2, tagbody, clEOA)); } } }

clObject clDotimes clVdecl(_ap)
{ clObject L_form, L_ignored, L_g672, var, countform, resultform,
  tagbody;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top675;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top675, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g672, L_top675); }
    else clSetq(L_g672, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g672))
      { clObject L_top676;
        clSetq(L_top676, clCar(L_g672, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g672);
          clSetq(L_g672, clCdr(L_0, clEOA)); }
        clSetq(var, L_top676); }
    else clSetq(var, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g672))
      { clObject L_top677;
        { clObject L_0;
          clSetq(L_0, L_g672);
          clSetq(L_top677, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g672);
          clSetq(L_g672, clCdr(L_0, clEOA)); }
        clSetq(countform, L_top677); }
    else clSetq(countform, clMissingArgs(I_3, clEOA));
    if (clTrue(L_g672))
      { clObject L_top678;
        { clObject L_0;
          clSetq(L_0, L_g672);
          clSetq(L_top678, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g672);
          clSetq(L_g672, clCdr(L_0, clEOA)); }
        clSetq(resultform, L_top678); }
    else clSetq(resultform, clNIL);
    clSetq(tagbody, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_g672))
    { clObject L_0; clSetq(L_0, L_g672); clExtraArgs(L_0, clEOA); }
  { clObject end_number;
    clSetq(end_number, clGensym(STR_END__4, clEOA));
    { clObject L_3, L_2, L_1;
      { clObject L_0__R1;
        clSetq(L_0__R1, clList(end_number, countform, clEOA));
        clSetq(L_1,
               clList(L_0__R1,
                      clList(var,
                             I_0,
                             clListSTAR(clADD_INTEGER,
                                        var,
                                        CONS_9,
                                        clEOA),
                             clEOA),
                      clEOA)); }
      { clObject L_1__R1, L_0__R1;
        clSetq(L_0__R1, clList(clGE_INTEGER, var, end_number, clEOA));
        clSetq(L_1__R1, resultform);
        clSetq(L_2, clList(L_0__R1, L_1__R1, clEOA)); }
      { clObject L_1__R1;
        clSetq(L_1__R1, clList(clIGNORABLE, var, clEOA));
        clSetq(L_3,
               clList(clDECLARE,
                      L_1__R1,
                      clList(clTYPE, clINTEGER, var, clEOA),
                      clEOA)); }
      return(clListSTAR(clDOstar, L_1, L_2, L_3, tagbody, clEOA)); } } }

clObject clProg clVdecl(_ap)
{ clObject L_form, L_ignored, variables, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top681;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top681, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(variables, L_top681); }
    else clSetq(variables, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_values682, decls, body__R1;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clFindDeclarations(body, clT, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values682, clMultipleValueFuncall(MVC)); }
    clSetq(decls, clCar(L_values682, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values682);
        clSetq(L_0, clSetq(L_values682, clCdr(L_0__R1, clEOA))); }
      clSetq(body__R1, clCar(L_0, clEOA)); }
    { clObject L_2;
      { clObject L_2__R1;
        clSetq(L_2__R1, clListSTAR(clDECLARE, decls, clEOA));
        clSetq(L_2,
               clList(clLET,
                      variables,
                      L_2__R1,
                      clListSTAR(clTAGBODY, body__R1, clEOA),
                      clEOA)); }
      return(clList(clBLOCK, clNIL, L_2, clEOA)); } } }

clObject clProgSTAR clVdecl(_ap)
{ clObject L_form, L_ignored, variables, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top685;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top685, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(variables, L_top685); }
    else clSetq(variables, clMissingArgs(I_1, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_values686, decls, body__R1;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clFindDeclarations(body, clT, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values686, clMultipleValueFuncall(MVC)); }
    clSetq(decls, clCar(L_values686, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values686);
        clSetq(L_0, clSetq(L_values686, clCdr(L_0__R1, clEOA))); }
      clSetq(body__R1, clCar(L_0, clEOA)); }
    { clObject L_2;
      { clObject L_2__R1;
        clSetq(L_2__R1, clListSTAR(clDECLARE, decls, clEOA));
        clSetq(L_2,
               clList(clLETstar,
                      variables,
                      L_2__R1,
                      clListSTAR(clTAGBODY, body__R1, clEOA),
                      clEOA)); }
      return(clList(clBLOCK, clNIL, L_2, clEOA)); } } }

clObject clMultipleValueList clVdecl(_ap)
{ clObject L_form, L_ignored, value_form;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top689;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top689, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(value_form, L_top689); }
    else clSetq(value_form, clMissingArgs(I_1, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  return(clList(clMULTIPLE_VALUE_CALL, CONS_10, value_form, clEOA)); }

clObject clMultipleValueBind clVdecl(_ap)
{ clObject L_form, L_ignored, varlist, value_form, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top692;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top692, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(varlist, L_top692); }
    else clSetq(varlist, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top693;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top693, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(value_form, L_top693); }
    else clSetq(value_form, clMissingArgs(I_2, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(clCdr(varlist, clEOA)))
    { clObject values;
      clSetq(values, clGensym(STR_VALUES__5, clEOA));
      { clObject L_2, L_1;
        { clObject L_1__R1, L_0__R1;
          clSetq(L_0__R1,
                 clList(values,
                        clList(clMULTIPLE_VALUE_LIST,
                               value_form,
                               clEOA),
                        clEOA));
          { clObject var, L_g11;
            clSetq(var, clNIL);
            clSetq(L_g11, varlist);
            { clObject ref;
              clSetq(ref, clNIL);
              { clObject L_g12, L_g13;
                clSetq(L_g12, clList(clNIL, clEOA));
                clSetq(L_g13, L_g12);
                if (clTrue(clEndp(L_g11, clEOA))) goto END_LOOP;
                clSetq(var, clCar(L_g11, clEOA));
                { clObject L_0__R2;
                  clSetq(L_0__R2, L_g11);
                  clSetq(L_g11, clCdr(L_0__R2, clEOA)); }
                clSetq(ref, values);
                clLabel(NEXT_LOOP);
                { clObject L_1__R2, L_0__R2;
                  clSetq(L_0__R2, L_g13);
                  { clObject L_0__R3;
                    { clObject L_1__R3, L_0__R4;
                      clSetq(L_0__R4, var);
                      { clObject L_1__R4;
                        clSetq(L_1__R4, ref);
                        clSetq(L_1__R3,
                               clList(clCAR, L_1__R4, clEOA)); }
                      clSetq(L_0__R3,
                             clList(L_0__R4, L_1__R3, clEOA)); }
                    clSetq(L_1__R2,
                           clSetq(L_g13, clList(L_0__R3, clEOA))); }
                  clRplacd(L_0__R2, L_1__R2, clEOA); }
                { clObject L_test__R1;
                  { clObject L_0__R2;
                    clSetq(L_0__R2, L_g11);
                    clSetq(L_test__R1, clEndp(L_0__R2, clEOA)); }
                  if (clTrue(L_test__R1)) goto END_LOOP; }
                { clObject L_0__R2;
                  clSetq(L_0__R2, L_g11);
                  clSetq(var, clCar(L_0__R2, clEOA)); }
                { clObject L_0__R2;
                  clSetq(L_0__R2, L_g11);
                  clSetq(L_g11, clCdr(L_0__R2, clEOA)); }
                clSetq(ref,
                       clList(clSETQ,
                              values,
                              clList(clCDR, values, clEOA),
                              clEOA));
                goto NEXT_LOOP;
                clLabel(END_LOOP);
                clSetq(L_1__R1, clCdr(L_g12, clEOA));
                clLocalReturn(NIL__r1);
                clSetq(L_1__R1, clNIL);
                clBlockEnd(NIL__r1); } } }
          clSetq(L_1, clListSTAR(L_0__R1, L_1__R1, clEOA)); }
        clSetq(L_2,
               clList(clDECLARE,
                      clList(clDYNAMIC_EXTENT, values, clEOA),
                      clEOA));
        return(clListSTAR(clLETstar, L_1, L_2, body, clEOA)); } }
  else
    { clObject L_1;
      { clObject L_0__R1;
        { clObject L_0__R2;
          clSetq(L_0__R2, clCar(varlist, clEOA));
          clSetq(L_0__R1, clList(L_0__R2, value_form, clEOA)); }
        clSetq(L_1, clList(L_0__R1, clEOA)); }
      return(clListSTAR(clLET, L_1, body, clEOA)); } }

static clObject clMultipleValueSetq_Lambda clVdecl(_ap)
{ clObject var, temp;
  { clBeginParse(_ap);
    clSetq(var,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(temp,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clList(clSETQ, var, temp, clEOA)); }

clObject clMultipleValueSetq clVdecl(_ap)
{ clObject L_form, L_ignored, varlist, value_form;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top696;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top696, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(varlist, L_top696); }
    else clSetq(varlist, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top697;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top697, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(value_form, L_top697); }
    else clSetq(value_form, clMissingArgs(I_2, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  if (clTrue(varlist))
    { clObject temps;
      clSetq(temps, clMakeSymbols(varlist, clEOA));
      { clObject L_3;
        { clObject L_0__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2,
                   clMakeClosure(0,
                                 clMultipleValueSetq_Lambda,
                                 clNULL_HOOK));
            clSetq(L_0__R1,
                   clMapcar(L_0__R2, varlist, temps, clEOA)); }
          clSetq(L_3,
                 clAppend(L_0__R1,
                          clList(clCar(temps, clEOA), clEOA),
                          clEOA)); }
        return(clListSTAR(clMULTIPLE_VALUE_BIND,
                          temps,
                          value_form,
                          L_3,
                          clEOA)); } }
  else return(clList(clVALUES, value_form, clEOA)); }

clObject clNthValue clVdecl(_ap)
{ clObject L_form, L_ignored, n, form;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top700;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top700, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(n, L_top700); }
    else clSetq(n, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top701;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top701, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(form, L_top701); }
    else clSetq(form, clMissingArgs(I_2, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  if (clTrue(clConstantp(n, clEOA)))
    { clObject dummy_list, keeper;
      clSetq(dummy_list, clNIL);
      clSetq(keeper, clGensym(STR_KEEPER__6, clEOA));
      { clObject i;
        clSetq(i, I_0);
        clLabel(l_ITERATE703);
        if (clTrue(clGeInteger(i, n, clEOA))) clLocalReturn(NIL);
        { clObject L_1, L_0;
          clSetq(L_0, clGensym(STR_IGNORE___7, clEOA));
          clSetq(L_1, dummy_list);
          clSetq(dummy_list, clCons(L_0, L_1, clEOA)); }
        { clObject L_0;
          clSetq(L_0, i);
          clSetq(i, clAddInteger(L_0, I_1, clEOA)); }
        goto l_ITERATE703; }
      clBlockEnd(NIL);
      { clObject L_3, L_1;
        { clObject L_0__R1;
          clSetq(L_0__R1, dummy_list);
          clSetq(L_1,
                 clAppend(L_0__R1, clList(keeper, clEOA), clEOA)); }
        { clObject L_1__R1;
          { clObject L_1__R2;
            clSetq(L_1__R2, dummy_list);
            clSetq(L_1__R1, clListSTAR(clIGNORE, L_1__R2, clEOA)); }
          clSetq(L_3, clList(clDECLARE, L_1__R1, clEOA)); }
        return(clList(clMULTIPLE_VALUE_BIND,
                      L_1,
                      form,
                      L_3,
                      keeper,
                      clEOA)); } }
  else
    return(clList(clNTH, n, clList(clMULTIPLE_VALUE_LIST, form, clEOA),
                  clEOA)); }

static clObject clLambda clVdecl(_ap)
{ clObject L_form, L_ignored, CL_form, CL_args;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(CL_form, L_form);
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    clSetq(CL_args, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clGenerateSetfMethod(CL_form, CONS_12, clNIL, clEOA)); }

static clObject clLambda_r1 clVdecl(_ap)
{ clObject L_form, env, place, prop, CL_default;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(env,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top708;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top708, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(place, L_top708); }
    else clSetq(place, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top709;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top709, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(prop, L_top709); }
    else clSetq(prop, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form))
      { clObject L_top710;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top710, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(CL_default, L_top710); }
    else clSetq(CL_default, clNIL);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  { clObject L_values711, temps, values, stores, set, get;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clGetSetfExpansion(place, env, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values711, clMultipleValueFuncall(MVC)); }
    clSetq(temps, clCar(L_values711, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values711);
        clSetq(L_0, clSetq(L_values711, clCdr(L_0__R1, clEOA))); }
      clSetq(values, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values711);
        clSetq(L_0, clSetq(L_values711, clCdr(L_0__R1, clEOA))); }
      clSetq(stores, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values711);
        clSetq(L_0, clSetq(L_values711, clCdr(L_0__R1, clEOA))); }
      clSetq(set, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values711);
        clSetq(L_0, clSetq(L_values711, clCdr(L_0__R1, clEOA))); }
      clSetq(get, clCar(L_0, clEOA)); }
    { clObject newval, ptemp, def_temp;
      clSetq(newval, clGensym(STR_NEWVAL__8, clEOA));
      clSetq(ptemp, clGensym(STR_PTEMP__9, clEOA));
      clSetq(def_temp,
             (clTrue(CL_default) ? clGensym(STR_DEF_TEMP__10, clEOA) :
              clNIL));
      { clObject L_4, L_3, L_2, L_1, L_0;
        { clObject L_1__R1;
          { clObject L_1__R2;
            if (clTrue(CL_default))
              { clObject L_0__R3;
                clSetq(L_0__R3, def_temp);
                clSetq(L_1__R2, clList(L_0__R3, clEOA)); }
            else clSetq(L_1__R2, clNIL);
            clSetq(L_1__R1, clListSTAR(ptemp, L_1__R2, clEOA)); }
          clSetq(L_0, clAppend(temps, L_1__R1, clEOA)); }
        { clObject L_1__R1;
          { clObject L_1__R2;
            if (clTrue(CL_default))
              { clObject L_0__R3;
                clSetq(L_0__R3, CL_default);
                clSetq(L_1__R2, clList(L_0__R3, clEOA)); }
            else clSetq(L_1__R2, clNIL);
            clSetq(L_1__R1, clListSTAR(prop, L_1__R2, clEOA)); }
          clSetq(L_1, clAppend(values, L_1__R1, clEOA)); }
        clSetq(L_2, clList(newval, clEOA));
        { clObject L_1__R1;
          { clObject L_0__R2;
            { clObject L_0__R3;
              clSetq(L_0__R3, clCar(stores, clEOA));
              clSetq(L_0__R2,
                     clList(L_0__R3,
                            clList(clPUTF, get, ptemp, newval, clEOA),
                            clEOA)); }
            clSetq(L_1__R1, clList(L_0__R2, clEOA)); }
          clSetq(L_3, clList(clLET, L_1__R1, set, newval, clEOA)); }
        { clObject L_3__R1;
          if (clTrue(CL_default))
            { clObject L_0__R2;
              clSetq(L_0__R2, def_temp);
              clSetq(L_3__R1, clList(L_0__R2, clEOA)); }
          else clSetq(L_3__R1, clNIL);
          clSetq(L_4,
                 clListSTAR(clGETF, get, ptemp, L_3__R1, clEOA)); }
        return(clValues(L_0, L_1, L_2, L_3, L_4, clEOA)); } } } }

clObject clRemf clVdecl(_ap)
{ clObject L_form, env, place, indicator;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(env,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top714;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top714, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(place, L_top714); }
    else clSetq(place, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top715;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top715, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(indicator, L_top715); }
    else clSetq(indicator, clMissingArgs(I_2, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(L_form))
    { clObject L_0; clSetq(L_0, L_form); clExtraArgs(L_0, clEOA); }
  { clObject L_values716, dummies, vals, newval, setter, getter;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clGetSetfExpansion(place, env, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values716, clMultipleValueFuncall(MVC)); }
    clSetq(dummies, clCar(L_values716, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values716);
        clSetq(L_0, clSetq(L_values716, clCdr(L_0__R1, clEOA))); }
      clSetq(vals, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values716);
        clSetq(L_0, clSetq(L_values716, clCdr(L_0__R1, clEOA))); }
      clSetq(newval, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values716);
        clSetq(L_0, clSetq(L_values716, clCdr(L_0__R1, clEOA))); }
      clSetq(setter, clCar(L_0, clEOA)); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values716);
        clSetq(L_0, clSetq(L_values716, clCdr(L_0__R1, clEOA))); }
      clSetq(getter, clCar(L_0, clEOA)); }
    { clObject d, v, let_list, ind_temp, local1, local2;
      clSetq(d, dummies);
      clSetq(v, vals);
      clSetq(let_list, clNIL);
      clSetq(ind_temp, clGensym(STR_IND_TEMP__11, clEOA));
      clSetq(local1, clGensym(STR_LOCAL__12, clEOA));
      clSetq(local2, clGensym(STR_LOCAL__12, clEOA));
      clLabel(l_ITERATE717);
      if (clTrue(clNull(d, clEOA)))
        { { clObject L_1, L_0;
            { clObject L_0__R1;
              clSetq(L_0__R1, clCar(newval, clEOA));
              clSetq(L_0, clList(L_0__R1, getter, clEOA)); }
            clSetq(L_1, let_list);
            clSetq(let_list, clCons(L_0, L_1, clEOA)); }
          { clObject L_1, L_0;
            clSetq(L_0, clList(ind_temp, indicator, clEOA));
            clSetq(L_1, let_list);
            clSetq(let_list, clCons(L_0, L_1, clEOA)); }
          { clObject L_2, L_1;
            { clObject L_0__R1;
              clSetq(L_0__R1, let_list);
              clSetq(L_1,
                     clFuncallFunction(clSymbolFunctionValue(clNREVERSE),
                                       L_0__R1,
                                       clEOA)); }
            { clObject L_3, L_2__R1, L_1__R1;
              { clObject L_0__R2;
                { clObject L_1__R3;
                  clSetq(L_1__R3, clCar(newval, clEOA));
                  clSetq(L_0__R2,
                         clList(local1,
                                L_1__R3,
                                clList(clCDDR, local1, clEOA),
                                clEOA)); }
                clSetq(L_1__R1,
                       clList(L_0__R2,
                              clList(local2, clNIL, local1, clEOA),
                              clEOA)); }
              { clObject L_0__R2;
                clSetq(L_0__R2, clList(clATOM, local1, clEOA));
                clSetq(L_2__R1, clListSTAR(L_0__R2, CONS_13, clEOA)); }
              { clObject L_2__R2, L_1__R2;
                { clObject L_0__R3;
                  clSetq(L_0__R3,
                         clList(clATOM,
                                clList(clCDR, local1, clEOA),
                                clEOA));
                  clSetq(L_1__R2,
                         clListSTAR(L_0__R3, CONS_14, clEOA)); }
                { clObject L_1__R3, L_0__R3;
                  { clObject L_1__R4;
                    clSetq(L_1__R4, clList(clCAR, local1, clEOA));
                    clSetq(L_0__R3,
                           clList(clEQ, L_1__R4, ind_temp, clEOA)); }
                  { clObject L_2__R3, L_1__R4;
                    { clObject L_1__R5;
                      { clObject L_1__R6;
                        clSetq(L_1__R6, clList(clCDR, local2, clEOA));
                        clSetq(L_1__R5,
                               clList(clRPLACD,
                                      L_1__R6,
                                      clList(clCDDR, local1, clEOA),
                                      clEOA)); }
                      clSetq(L_1__R4,
                             clListSTAR(local2,
                                        L_1__R5,
                                        CONS_17,
                                        clEOA)); }
                    { clObject L_1__R5;
                      { clObject L_1__R6;
                        clSetq(L_1__R6, clCar(newval, clEOA));
                        clSetq(L_1__R5,
                               clList(clSETQ,
                                      L_1__R6,
                                      clList(clCDDR,
                                             clCar(newval, clEOA),
                                             clEOA),
                                      clEOA)); }
                      clSetq(L_2__R3,
                             clListSTAR(clT,
                                        L_1__R5,
                                        setter,
                                        CONS_17,
                                        clEOA)); }
                    clSetq(L_1__R3,
                           clList(clCOND, L_1__R4, L_2__R3, clEOA)); }
                  clSetq(L_2__R2, clList(L_0__R3, L_1__R3, clEOA)); }
                clSetq(L_3, clList(clCOND, L_1__R2, L_2__R2, clEOA)); }
              clSetq(L_2,
                     clList(clDO, L_1__R1, L_2__R1, L_3, clEOA)); }
            return(clList(clLETstar, L_1, L_2, clEOA)); } }
      { clObject L_1, L_0;
        { clObject L_0__R1;
          clSetq(L_0__R1, clCar(d, clEOA));
          clSetq(L_0, clList(L_0__R1, clCar(v, clEOA), clEOA)); }
        clSetq(L_1, let_list);
        clSetq(let_list, clCons(L_0, L_1, clEOA)); }
      { clObject L_0; clSetq(L_0, d); clSetq(d, clCdr(L_0, clEOA)); }
      { clObject L_0; clSetq(L_0, v); clSetq(v, clCdr(L_0, clEOA)); }
      goto l_ITERATE717; } } }

clObject clEtypecase clVdecl(_ap)
{ clObject L_form, L_ignored, keyform, clauses;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top720;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top720, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(keyform, L_top720); }
    else clSetq(keyform, clMissingArgs(I_1, clEOA));
    clSetq(clauses, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject form;
    clSetq(form, clGensym(clEOA));
    { clObject L_2, L_1;
      clSetq(L_1, clList(clList(form, keyform, clEOA), clEOA));
      { clObject L_2__R1;
        { clObject L_1__R2;
          { clObject L_0__R3;
            { clObject L_1__R3;
              { clObject L_5;
                { clObject L_1__R5;
                  { clObject L_1__R6;
                    { clObject L_0__R8;
                      clSetq(L_0__R8, clSymbolFunctionValue(clFIRST));
                      clSetq(L_1__R6,
                             clMapcar(L_0__R8, clauses, clEOA)); }
                    clSetq(L_1__R5,
                           clListSTAR(clOR, L_1__R6, clEOA)); }
                  clSetq(L_5, clList(clQUOTE, L_1__R5, clEOA)); }
                clSetq(L_1__R3,
                       clList(clERROR,
                              CONS_20,
                              keyDATUM,
                              form,
                              keyEXPECTED_TYPE,
                              L_5,
                              clEOA)); }
              clSetq(L_0__R3, clList(clOTHERWISE, L_1__R3, clEOA)); }
            clSetq(L_1__R2, clList(L_0__R3, clEOA)); }
          clSetq(L_2__R1, clAppend(clauses, L_1__R2, clEOA)); }
        clSetq(L_2, clListSTAR(clTYPECASE, form, L_2__R1, clEOA)); }
      return(clList(clLET, L_1, L_2, clEOA)); } } }

static clObject clEcase_Lambda clVdecl(_ap)
{ clObject clause, keylist;
  { clBeginParse(_ap);
    clSetq(clause,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(keylist, clFirst(clause, clEOA));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(clListp(keylist, clEOA)))
    return(clCopyList(keylist, clEOA));
  else return(clList(keylist, clEOA)); }

clObject clEcase clVdecl(_ap)
{ clObject L_form, L_ignored, whole, keyform, clauses;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(whole, L_form);
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top723;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top723, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(keyform, L_top723); }
    else clSetq(keyform, clMissingArgs(I_1, clEOA));
    clSetq(clauses, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject form, types;
    clSetq(form, clGensym(clEOA));
    { clObject L_0;
      clSetq(L_0, clMakeClosure(0, clEcase_Lambda, clNULL_HOOK));
      clSetq(types, clMapcan(L_0, clauses, clEOA)); }
    if (clTrue(clauses))
      { clObject L_1;
        clSetq(L_1, clList(clList(form, keyform, clEOA), clEOA));
        return(clList(clLET,
                      L_1,
                      clListSTAR(clCASE,
                                 form,
                                 clAppend(clauses,
                                          clList(clList(clT,
                                                        clList(clERROR,
                                                               CONS_20,
                                                               keyDATUM,
                                                               form,
                                                               keyEXPECTED_TYPE,
                                                               clList(clQUOTE,
                                                                      clListSTAR(clMEMBER,
                                                                                 types,
                                                                                 clEOA),
                                                                      clEOA),
                                                               clEOA),
                                                        clEOA),
                                                 clEOA),
                                          clEOA),
                                 clEOA),
                      clEOA)); }
    else
      return(clSignalProgramError(keyFORMAT_STRING,
                                  STR_No_clauses_in_tildesdot__15,
                                  keyFORMAT_ARGUMENTS,
                                  clList(whole, clEOA),
                                  clEOA)); } }

clObject clWithOutputToString clVdecl(_ap)
{ clObject L_form, L_ignored, L_form__R1, L_g724, var, string, L_keys,
  element_type, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top727;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top727, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g724, L_top727); }
    else clSetq(L_g724, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g724))
      { clObject L_top728;
        clSetq(L_top728, clCar(L_g724, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g724);
          clSetq(L_g724, clCdr(L_0, clEOA)); }
        clSetq(var, L_top728); }
    else clSetq(var, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g724))
      { clObject L_top729;
        { clObject L_0;
          clSetq(L_0, L_g724);
          clSetq(L_top729, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g724);
          clSetq(L_g724, clCdr(L_0, clEOA)); }
        clSetq(string, L_top729); }
    else clSetq(string, clNIL);
    clSetq(L_keys, L_g724);
    if (clTrue(clSetq(L_form__R1,
                      clKeyArg(keyELEMENT_TYPE, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(element_type, clCar(L_0, clEOA)); }
    else clSetq(element_type, CONS_22);
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  clCheckKeys(L_keys, CONS_24, clEOA);
  { clObject L_values730, decls, body__R1;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clFindDeclarations(body, clT, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values730, clMultipleValueFuncall(MVC)); }
    clSetq(decls, clCar(L_values730, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values730);
        clSetq(L_0, clSetq(L_values730, clCdr(L_0__R1, clEOA))); }
      clSetq(body__R1, clCar(L_0, clEOA)); }
    { clObject L_3, L_2, L_1;
      { clObject L_3__R1, L_2__R1;
        clSetq(L_2__R1, element_type);
        clSetq(L_3__R1, string);
        clSetq(L_1,
               clList(var,
                      clOUTPUT_BUFFER,
                      L_2__R1,
                      L_3__R1,
                      clEOA)); }
      clSetq(L_2, clListSTAR(clDECLARE, decls, clEOA));
      { clObject L_1__R1;
        { clObject L_test;
          { clObject L_0__R2;
            clSetq(L_0__R2, string);
            clSetq(L_test, clNot(L_0__R2, clEOA)); }
          clSetq(L_1__R1,
                 (clTrue(L_test) ?
                  clList(clList(clGET_OUTPUT_STREAM_STRING,
                                var,
                                clEOA),
                         clEOA) :
                  clNIL)); }
        clSetq(L_3, clAppend(body__R1, L_1__R1, clEOA)); }
      return(clListSTAR(clUSING_RESOURCE, L_1, L_2, L_3, clEOA)); } } }

clObject clWithInputFromString clVdecl(_ap)
{ clObject L_form, L_ignored, L_form__R1, L_g731, var, string, L_keys,
  index, start, end, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top734;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top734, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g731, L_top734); }
    else clSetq(L_g731, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g731))
      { clObject L_top735;
        clSetq(L_top735, clCar(L_g731, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g731);
          clSetq(L_g731, clCdr(L_0, clEOA)); }
        clSetq(var, L_top735); }
    else clSetq(var, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g731))
      { clObject L_top736;
        { clObject L_0;
          clSetq(L_0, L_g731);
          clSetq(L_top736, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g731);
          clSetq(L_g731, clCdr(L_0, clEOA)); }
        clSetq(string, L_top736); }
    else clSetq(string, clMissingArgs(I_3, clEOA));
    clSetq(L_keys, L_g731);
    if (clTrue(clSetq(L_form__R1, clKeyArg(keyINDEX, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(index, clCar(L_0, clEOA)); }
    else clSetq(index, clNIL);
    if (clTrue(clSetq(L_form__R1, clKeyArg(keySTART, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(start, clCar(L_0, clEOA)); }
    else clSetq(start, I_0);
    if (clTrue(clSetq(L_form__R1, clKeyArg(keyEND, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(end, clCar(L_0, clEOA)); }
    else clSetq(end, clNIL);
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  clCheckKeys(L_keys, CONS_25, clEOA);
  { clObject L_values737, decls, body__R1;
    { clMultipleValueCall(MVC);
      clSetq(MVC, clSymbolFunctionValue(clLIST));
      clFindDeclarations(body, clT, clEOA);
      clAccumulateValues(MVC);
      clSetq(L_values737, clMultipleValueFuncall(MVC)); }
    clSetq(decls, clCar(L_values737, clEOA));
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, L_values737);
        clSetq(L_0, clSetq(L_values737, clCdr(L_0__R1, clEOA))); }
      clSetq(body__R1, clCar(L_0, clEOA)); }
    { clObject L_3, L_2, L_1;
      { clObject L_4, L_3__R1;
        clSetq(L_3__R1, start);
        clSetq(L_4, end);
        clSetq(L_1,
               clList(var,
                      clINPUT_BUFFER,
                      string,
                      L_3__R1,
                      L_4,
                      clEOA)); }
      clSetq(L_2, clListSTAR(clDECLARE, decls, clEOA));
      if (clTrue(index))
        { clObject L_0__R1;
          { clObject L_2__R1, L_1__R1;
            clSetq(L_1__R1, clListSTAR(clPROGN, body__R1, clEOA));
            { clObject L_1__R2;
              clSetq(L_1__R2, index);
              clSetq(L_2__R1,
                     clList(clSETQ,
                            L_1__R2,
                            clList(clINPUT_BUFFER_POSITION,
                                   var,
                                   clEOA),
                            clEOA)); }
            clSetq(L_0__R1,
                   clList(clMULTIPLE_VALUE_PROG1,
                          L_1__R1,
                          L_2__R1,
                          clEOA)); }
          clSetq(L_3, clList(L_0__R1, clEOA)); }
      else clSetq(L_3, body__R1);
      return(clListSTAR(clUSING_RESOURCE, L_1, L_2, L_3, clEOA)); } } }

clObject clPrintUnreadableObject clVdecl(_ap)
{ clObject L_form, L_ignored, L_form__R1, L_g738, object, stream,
  L_keys, type, identity, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top741;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top741, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(L_g738, L_top741); }
    else clSetq(L_g738, clMissingArgs(I_1, clEOA));
    if (clTrue(L_g738))
      { clObject L_top742;
        clSetq(L_top742, clCar(L_g738, clEOA));
        { clObject L_0;
          clSetq(L_0, L_g738);
          clSetq(L_g738, clCdr(L_0, clEOA)); }
        clSetq(object, L_top742); }
    else clSetq(object, clMissingArgs(I_2, clEOA));
    if (clTrue(L_g738))
      { clObject L_top743;
        { clObject L_0;
          clSetq(L_0, L_g738);
          clSetq(L_top743, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_g738);
          clSetq(L_g738, clCdr(L_0, clEOA)); }
        clSetq(stream, L_top743); }
    else clSetq(stream, clMissingArgs(I_3, clEOA));
    clSetq(L_keys, L_g738);
    if (clTrue(clSetq(L_form__R1, clKeyArg(keyTYPE, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(type, clCar(L_0, clEOA)); }
    else clSetq(type, clNIL);
    if (clTrue(clSetq(L_form__R1,
                      clKeyArg(keyIDENTITY, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_form__R1);
        clSetq(identity, clCar(L_0, clEOA)); }
    else clSetq(identity, clNIL);
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  clCheckKeys(L_keys, CONS_28, clEOA);
  { clObject object_var, stream_var, type_var, identity_var, bodyp;
    clSetq(object_var, clGensym(STR_OBJECT__22, clEOA));
    clSetq(stream_var, clGensym(STR_STREAM__23, clEOA));
    clSetq(type_var, clGensym(STR_TYPEP__24, clEOA));
    clSetq(identity_var, clGensym(STR_IDENTITYP__25, clEOA));
    clSetq(bodyp, clNot(clNull(body, clEOA), clEOA));
    { clObject L_2, L_1;
      { clObject L_3__R1, L_2__R1, L_1__R1, L_0__R1;
        clSetq(L_0__R1, clList(object_var, object, clEOA));
        clSetq(L_1__R1,
               clList(stream_var,
                      clList(clOUTPUT_STREAM, stream, clEOA),
                      clEOA));
        { clObject L_1__R2;
          clSetq(L_1__R2, type);
          clSetq(L_2__R1, clList(type_var, L_1__R2, clEOA)); }
        { clObject L_1__R2;
          clSetq(L_1__R2, identity);
          clSetq(L_3__R1, clList(identity_var, L_1__R2, clEOA)); }
        clSetq(L_1,
               clList(L_0__R1, L_1__R1, L_2__R1, L_3__R1, clEOA)); }
      clSetq(L_2,
             clList(clPRINT_UNREADABLE_OBJECT_HEADER, object_var,
                    stream_var, type_var, identity_var, bodyp, clEOA));
      return(clListSTAR(clLET,
                        L_1,
                        L_2,
                        clAppend(body,
                                 clList(clList(clPRINT_UNREADABLE_OBJECT_TRAILER,
                                               object_var,
                                               stream_var,
                                               identity_var,
                                               bodyp,
                                               clEOA),
                                        clEOA),
                                 clEOA),
                        clEOA)); } } }

void clInitContComp2 __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(I_3, clIntFixnum(3));
  clSetq(I_4, clIntFixnum(4));
  clSetq(I_5, clIntFixnum(5));
  clSetq(I_6, clIntFixnum(6));
  clSetq(STR_ITERATE__0,
         clCharpSimpleBaseString("ITERATE"));
  clSetq(CONS_1, clCons(clNULL, clNIL, clEOA));
  clSetq(CONS_0, clCons(clSYMBOL, CONS_1, clEOA));
  clSetq(STR_DATUM__1,
         clCharpSimpleBaseString("DATUM"));
  clSetq(keyDATUM, clMakeKeyword(STR_DATUM__1, clEOA));
  clSetq(STR_EXPECTED_TYPE__2,
         clCharpSimpleBaseString("EXPECTED-TYPE"));
  clSetq(keyEXPECTED_TYPE, clMakeKeyword(STR_EXPECTED_TYPE__2, clEOA));
  clSetq(CONS_5, clCons(I_3, clNIL, clEOA));
  clSetq(CONS_4, clCons(I_2, CONS_5, clEOA));
  clSetq(CONS_3, clCons(I_1, CONS_4, clEOA));
  clSetq(CONS_2, clCons(clMEMBER, CONS_3, clEOA));
  clSetq(CONS_8, clCons(clCONS, clNIL, clEOA));
  clSetq(CONS_7, clCons(clSYMBOL, CONS_8, clEOA));
  clSetq(CONS_6, clCons(clOR, CONS_7, clEOA));
  clSetq(STR_SUBLIST__3,
         clCharpSimpleBaseString("SUBLIST"));
  clSetq(STR_END__4,
         clCharpSimpleBaseString("END"));
  clSetq(I_0, clIntFixnum(0));
  clSetq(CONS_9, clCons(I_1, clNIL, clEOA));
  clSetq(CONS_11, clCons(clLIST, clNIL, clEOA));
  clSetq(CONS_10, clCons(clFUNCTION, CONS_11, clEOA));
  clSetq(STR_VALUES__5,
         clCharpSimpleBaseString("VALUES"));
  clSetq(STR_KEEPER__6,
         clCharpSimpleBaseString("KEEPER"));
  clSetq(STR_IGNORE___7,
         clCharpSimpleBaseString("IGNORE-"));
  clSetq(CONS_12, clCons(clSET_SYMBOL_PLIST, clNIL, clEOA));
  clSetq(STR_NEWVAL__8,
         clCharpSimpleBaseString("NEWVAL"));
  clSetq(STR_PTEMP__9,
         clCharpSimpleBaseString("PTEMP"));
  clSetq(STR_DEF_TEMP__10,
         clCharpSimpleBaseString("DEF-TEMP"));
  clSetq(STR_IND_TEMP__11,
         clCharpSimpleBaseString("IND-TEMP"));
  clSetq(STR_LOCAL__12,
         clCharpSimpleBaseString("LOCAL"));
  clSetq(CONS_13, clCons(clNIL, clNIL, clEOA));
  clSetq(STRn_13,
         clCharpSimpleBaseString("Odd-length property list in REMF."));
  clSetq(CONS_16, clCons(STRn_13, clNIL, clEOA));
  clSetq(CONS_15, clCons(clERROR, CONS_16, clEOA));
  clSetq(CONS_14, clCons(CONS_15, clNIL, clEOA));
  clSetq(CONS_19, clCons(clT, clNIL, clEOA));
  clSetq(CONS_18, clCons(clRETURN, CONS_19, clEOA));
  clSetq(CONS_17, clCons(CONS_18, clNIL, clEOA));
  clSetq(CONS_21, clCons(clTYPE_ERROR, clNIL, clEOA));
  clSetq(CONS_20, clCons(clQUOTE, CONS_21, clEOA));
  clSetq(STR_FORMAT_STRING__14,
         clCharpSimpleBaseString("FORMAT-STRING"));
  clSetq(keyFORMAT_STRING,
         clMakeKeyword(STR_FORMAT_STRING__14, clEOA));
  clSetq(STR_No_clauses_in_tildesdot__15,
         clCharpSimpleBaseString("No clauses in ~s."));
  clSetq(STR_FORMAT_ARGUMENTS__16,
         clCharpSimpleBaseString("FORMAT-ARGUMENTS"));
  clSetq(keyFORMAT_ARGUMENTS,
         clMakeKeyword(STR_FORMAT_ARGUMENTS__16, clEOA));
  clSetq(STR_ELEMENT_TYPE__17,
         clCharpSimpleBaseString("ELEMENT-TYPE"));
  clSetq(keyELEMENT_TYPE, clMakeKeyword(STR_ELEMENT_TYPE__17, clEOA));
  clSetq(CONS_23, clCons(clCHARACTER, clNIL, clEOA));
  clSetq(CONS_22, clCons(clQUOTE, CONS_23, clEOA));
  clSetq(CONS_24, clCons(keyELEMENT_TYPE, clNIL, clEOA));
  clSetq(STR_INDEX__18,
         clCharpSimpleBaseString("INDEX"));
  clSetq(keyINDEX, clMakeKeyword(STR_INDEX__18, clEOA));
  clSetq(STR_START__19,
         clCharpSimpleBaseString("START"));
  clSetq(keySTART, clMakeKeyword(STR_START__19, clEOA));
  clSetq(keyEND, clMakeKeyword(STR_END__4, clEOA));
  clSetq(CONS_27, clCons(keyINDEX, clNIL, clEOA));
  clSetq(CONS_26, clCons(keySTART, CONS_27, clEOA));
  clSetq(CONS_25, clCons(keyEND, CONS_26, clEOA));
  clSetq(STR_TYPE__20,
         clCharpSimpleBaseString("TYPE"));
  clSetq(keyTYPE, clMakeKeyword(STR_TYPE__20, clEOA));
  clSetq(STR_IDENTITY__21,
         clCharpSimpleBaseString("IDENTITY"));
  clSetq(keyIDENTITY, clMakeKeyword(STR_IDENTITY__21, clEOA));
  clSetq(CONS_29, clCons(keyTYPE, clNIL, clEOA));
  clSetq(CONS_28, clCons(keyIDENTITY, CONS_29, clEOA));
  clSetq(STR_OBJECT__22,
         clCharpSimpleBaseString("OBJECT"));
  clSetq(STR_STREAM__23,
         clCharpSimpleBaseString("STREAM"));
  clSetq(STR_TYPEP__24,
         clCharpSimpleBaseString("TYPEP"));
  clSetq(STR_IDENTITYP__25,
         clCharpSimpleBaseString("IDENTITYP"));


  clSetSymbolFunctionValue(clDO_BODY,
                           clMakeClosure(0, clDoBody, clNULL_HOOK));
  (void) clDO_BODY;
  { clObject L_value657;
    clSetq(L_value657, clMakeClosure(0, clDo, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value657, clDO, clEOA); }
  (void) clDO;
  { clObject L_value661;
    clSetq(L_value661, clMakeClosure(0, clDoSTAR, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value661, clDOstar, clEOA); }
  (void) clDOstar;
  { clObject L_value666;
    clSetq(L_value666, clMakeClosure(0, clDolist, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value666, clDOLIST, clEOA); }
  (void) clDOLIST;
  { clObject L_value673;
    clSetq(L_value673, clMakeClosure(0, clDotimes, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value673, clDOTIMES, clEOA); }
  (void) clDOTIMES;
  { clObject L_value679;
    clSetq(L_value679, clMakeClosure(0, clProg, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value679, clPROG, clEOA); }
  (void) clPROG;
  { clObject L_value683;
    clSetq(L_value683, clMakeClosure(0, clProgSTAR, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value683, clPROGstar, clEOA); }
  (void) clPROGstar;
  { clObject L_value687;
    clSetq(L_value687,
           clMakeClosure(0, clMultipleValueList, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value687, clMULTIPLE_VALUE_LIST, clEOA); }
  (void) clMULTIPLE_VALUE_LIST;
  { clObject L_value690;
    clSetq(L_value690,
           clMakeClosure(0, clMultipleValueBind, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value690, clMULTIPLE_VALUE_BIND, clEOA); }
  (void) clMULTIPLE_VALUE_BIND;
  { clObject L_value694;
    clSetq(L_value694,
           clMakeClosure(0, clMultipleValueSetq, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value694, clMULTIPLE_VALUE_SETQ, clEOA); }
  (void) clMULTIPLE_VALUE_SETQ;
  { clObject L_value698;
    clSetq(L_value698, clMakeClosure(0, clNthValue, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value698, clNTH_VALUE, clEOA); }
  (void) clNTH_VALUE;
  { clObject L_value704;
    clSetq(L_value704, clMakeClosure(0, clLambda, clNULL_HOOK));
    cl_SETF_SetfExpander(L_value704, clSYMBOL_PLIST, clEOA); }
  (void) clSYMBOL_PLIST;
  { clObject L_value706;
    clSetq(L_value706, clMakeClosure(0, clLambda_r1, clNULL_HOOK));
    cl_SETF_SetfExpander(L_value706, clGETF, clEOA); }
  (void) clGETF;
  { clObject L_value712;
    clSetq(L_value712, clMakeClosure(0, clRemf, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value712, clREMF, clEOA); }
  (void) clREMF;
  { clObject L_value718;
    clSetq(L_value718, clMakeClosure(0, clEtypecase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value718, clETYPECASE, clEOA); }
  (void) clETYPECASE;
  { clObject L_value721;
    clSetq(L_value721, clMakeClosure(0, clEcase, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value721, clECASE, clEOA); }
  (void) clECASE;
  { clObject L_value725;
    clSetq(L_value725,
           clMakeClosure(0, clWithOutputToString, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value725,
                          clWITH_OUTPUT_TO_STRING,
                          clEOA); }
  (void) clWITH_OUTPUT_TO_STRING;
  { clObject L_value732;
    clSetq(L_value732,
           clMakeClosure(0, clWithInputFromString, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value732,
                          clWITH_INPUT_FROM_STRING,
                          clEOA); }
  (void) clWITH_INPUT_FROM_STRING;
  { clObject L_value739;
    clSetq(L_value739,
           clMakeClosure(0, clPrintUnreadableObject, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value739,
                          clPRINT_UNREADABLE_OBJECT,
                          clEOA); }
  (void) clPRINT_UNREADABLE_OBJECT;
  clUnwind(4); }
