/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Friday the twenty-second of May, 1998, 11:18:59 am CDT. */
#include <eclipse.h>

clObject clAppend(clProto), clCar(clProto), clCdr(clProto),
  clCharpSimpleBaseString __P((clCharp)), clCons(clProto),
  clConsp(clProto), clExtraArgs(clProto), clFindDeclarations(clProto),
  clFindType(clProto), clFuncallableStandardInstanceAccess(clProto),
  clGensym(clProto), clList(clProto), clListSTAR(clProto),
  cl_SETF_MacroFunction(clProto), clMakeKeyword(clProto),
  clMakeMethodLambdaList(clProto), clMakeStandInMethod(clProto),
  clMakeStandardInstanceFromSlots __P((clObject, clObject, clObject)),
  clMakeStaticSlots __P((clObject, ...)), clMissingArgs(clProto),
  clParseMacro(clProto), clRest(clProto), clSecond(clProto),
  clSpecializerDeclarations(clProto),
  clStandardInstanceAccess(clProto), clValues(clProto);

extern clObject clampersandREST, clBLOCK, clDECLARE, clDYNAMIC_EXTENT,
  clEVAL_WHEN, clIF, clIGNORABLE, clINLINE, clLAMBDA, clLET, clQUOTE,
  clstarsymbol, clAPPLY, clAPPLY_METHOD, clCALL_NEXT_METHOD, clCAR,
  clCNM_ARGS, clDEFTYPE, clDESTRUCTURING_BIND, clENSURE_DEFTYPE,
  clENVIRONMENT, clFLET, clFUNCTION, clGENERIC_FUNCTION,
  clGENERIC_FUNCTION_NAME, clLAMBDA_EXPRESSION, clLIST,
  clMAKE_LOAD_FORM, clMAKE_METHOD_LAMBDA,
  clMAKE_METHOD_LAMBDA_STANDARD_GENERIC_FUNCTION_STANDARD_METHOD_T_T,
  clMETHOD, clNEXT_METHOD, clNEXT_METHOD_P, clNO_NEXT_METHOD, clNOT,
  clNULL, clOR, clREST, clSTANDARD_GENERIC_FUNCTION,
  clSTANDARD_GENERIC_FUNCTION_CLASSOBJ, clSTANDARD_METHOD,
  clSTANDARD_METHOD_CLASSOBJ, clT_CLASSOBJ;

static clObject CONS_0, CONS_1, CONS_10, CONS_11, CONS_12, CONS_13,
  CONS_14, CONS_15, CONS_16, CONS_17, CONS_18, CONS_19, CONS_2,
  CONS_20, CONS_21, CONS_22, CONS_23, CONS_24, CONS_25, CONS_26,
  CONS_27, CONS_3, CONS_4, CONS_5, CONS_6, CONS_7, CONS_8, CONS_9, I_1,
  I_16, I_2, I_3, I_4, keyCOMPILE_TOPLEVEL, keyDECLARATIONS,
  keyDEFAULT, keyDOCUMENTATION, keyEXECUTE, keyFUNCTION,
  keyLOAD_TOPLEVEL, STR_ARGS__5, STR_COMPILE_TOPLEVEL__0,
  STR_DECLARATIONS__7, STR_DEFAULT__4, STR_DOCUMENTATION__8,
  STR_EXECUTE__2, STR_FUNCTION__3, STR_LOAD_TOPLEVEL__1, STR_METHODS__6;

clObject clDeftype clVdecl(_ap)
{ clObject L_form, L_ignored, name, lambda_list, body;
  { clBeginParse(_ap);
    clSetq(L_form,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_ignored,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    { clObject L_0;
      clSetq(L_0, L_form);
      clSetq(L_form, clCdr(L_0, clEOA)); }
    if (clTrue(L_form))
      { clObject L_top397;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top397, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(name, L_top397); }
    else clSetq(name, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form))
      { clObject L_top398;
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_top398, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form);
          clSetq(L_form, clCdr(L_0, clEOA)); }
        clSetq(lambda_list, L_top398); }
    else clSetq(lambda_list, clMissingArgs(I_2, clEOA));
    clSetq(body, L_form);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_3, L_2;
    { clObject L_3__R1, L_1__R1;
      { clObject L_1__R2;
        clSetq(L_1__R2, name);
        clSetq(L_1__R1, clList(clQUOTE, L_1__R2, clEOA)); }
      { clObject L_1__R2;
        { clObject L_1__R3, L_0__R3;
          clSetq(L_0__R3, name);
          clSetq(L_1__R3, lambda_list);
          clSetq(L_1__R2,
                 clParseMacro(L_0__R3,
                              L_1__R3,
                              body,
                              keyDEFAULT,
                              CONS_3,
                              clEOA)); }
        clSetq(L_3__R1, clList(clFUNCTION, L_1__R2, clEOA)); }
      clSetq(L_2,
             clList(clENSURE_DEFTYPE, L_1__R1, keyFUNCTION, L_3__R1,
                    clEOA)); }
    { clObject L_1__R1;
      clSetq(L_1__R1, name);
      clSetq(L_3, clList(clQUOTE, L_1__R1, clEOA)); }
    return(clList(clEVAL_WHEN, CONS_0, L_2, L_3, clEOA)); } }

clObject clMakeMethodLambdaStandardGenericFunctionStandardMethodTT clVdecl(_ap)
{ clObject CL_DOTargsDOT, ignore;
  { clBeginParse(_ap);
    clSetq(CL_DOTargsDOT,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(ignore, clVargs(_ap));
    clEndParse(_ap); }
  { clObject L_form401, generic_function, method, lambda_expression,
    environment;
    clSetq(L_form401, CL_DOTargsDOT);
    if (clTrue(L_form401))
      { clObject L_top402;
        clSetq(L_top402, clCar(L_form401, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(generic_function, L_top402); }
    else clSetq(generic_function, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form401))
      { clObject L_top403;
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_top403, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(method, L_top403); }
    else clSetq(method, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form401))
      { clObject L_top404;
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_top404, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(lambda_expression, L_top404); }
    else clSetq(lambda_expression, clMissingArgs(I_3, clEOA));
    if (clTrue(L_form401))
      { clObject L_top405;
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_top405, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(environment, L_top405); }
    else clSetq(environment, clMissingArgs(I_4, clEOA));
    if (clTrue(L_form401))
      { clObject L_0;
        clSetq(L_0, L_form401);
        clExtraArgs(L_0, clEOA); }
    { clObject L_form406, lambda_list, body;
      { clObject L_0;
        clSetq(L_0, lambda_expression);
        clSetq(L_form406, clRest(L_0, clEOA)); }
      if (clTrue(L_form406))
        { clObject L_top407;
          clSetq(L_top407, clCar(L_form406, clEOA));
          { clObject L_0;
            clSetq(L_0, L_form406);
            clSetq(L_form406, clCdr(L_0, clEOA)); }
          clSetq(lambda_list, L_top407); }
      else clSetq(lambda_list, clMissingArgs(I_1, clEOA));
      clSetq(body, L_form406);
      { clObject name, args, methods;
        { clObject L_0;
          clSetq(L_0, generic_function);
          clSetq(name,
                 clFuncallFunction(clSymbolFunctionValue(clGENERIC_FUNCTION_NAME),
                                   L_0,
                                   clEOA)); }
        clSetq(args, clGensym(STR_ARGS__5, clEOA));
        clSetq(methods, clGensym(STR_METHODS__6, clEOA));
        { clObject L_values408, decl, body__R1, doc;
          { clMultipleValueCall(MVC);
            clSetq(MVC, clSymbolFunctionValue(clLIST));
            clFindDeclarations(body, clNIL, clEOA);
            clAccumulateValues(MVC);
            clSetq(L_values408, clMultipleValueFuncall(MVC)); }
          clSetq(decl, clCar(L_values408, clEOA));
          { clObject L_0;
            { clObject L_0__R1;
              clSetq(L_0__R1, L_values408);
              clSetq(L_0,
                     clSetq(L_values408, clCdr(L_0__R1, clEOA))); }
            clSetq(body__R1, clCar(L_0, clEOA)); }
          { clObject L_0;
            { clObject L_0__R1;
              clSetq(L_0__R1, L_values408);
              clSetq(L_0,
                     clSetq(L_values408, clCdr(L_0__R1, clEOA))); }
            clSetq(doc, clCar(L_0, clEOA)); }
          { clObject L_1, L_0;
            { clObject L_2, L_1__R1;
              clSetq(L_1__R1, clList(args, methods, clEOA));
              { clObject L_3, L_1__R2;
                { clObject L_0__R3;
                  { clObject L_3__R1;
                    { clObject L_2__R3, L_1__R5;
                      clSetq(L_1__R5,
                             clList(clList(clNEXT_METHOD,
                                           clList(clCAR,
                                                  methods,
                                                  clEOA),
                                           clEOA),
                                    clEOA));
                      { clObject L_3__R2, L_2__R4;
                        { clObject L_2__R5;
                          clSetq(L_2__R5,
                                 clList(clOR,
                                        clCNM_ARGS,
                                        args,
                                        clEOA));
                          clSetq(L_2__R4,
                                 clList(clAPPLY_METHOD,
                                        clNEXT_METHOD,
                                        L_2__R5,
                                        clList(clREST, methods, clEOA),
                                        clEOA)); }
                        { clObject L_3__R3, L_2__R5;
                          { clObject L_1__R8, L_0__R8;
                            clSetq(L_0__R8, generic_function);
                            clSetq(L_1__R8, environment);
                            clSetq(L_2__R5,
                                   clFuncallFunction(clSymbolFunctionValue(clMAKE_LOAD_FORM),
                                                     L_0__R8,
                                                     L_1__R8,
                                                     clEOA)); }
                          { clObject L_2__R6, L_1__R8, L_0__R8;
                            clSetq(L_0__R8, generic_function);
                            clSetq(L_1__R8, method);
                            clSetq(L_2__R6, environment);
                            clSetq(L_3__R3,
                                   clMakeStandInMethod(L_0__R8,
                                                       L_1__R8,
                                                       L_2__R6,
                                                       clEOA)); }
                          clSetq(L_3__R2,
                                 clListSTAR(clAPPLY,
                                            CONS_10,
                                            L_2__R5,
                                            L_3__R3,
                                            CONS_6,
                                            clEOA)); }
                        clSetq(L_2__R3,
                               clList(clIF,
                                      clNEXT_METHOD,
                                      L_2__R4,
                                      L_3__R2,
                                      clEOA)); }
                      clSetq(L_3__R1,
                             clList(clLET, L_1__R5, L_2__R3, clEOA)); }
                    clSetq(L_0__R3,
                           clList(clCALL_NEXT_METHOD,
                                  CONS_5,
                                  CONS_7,
                                  L_3__R1,
                                  clEOA)); }
                  clSetq(L_1__R2,
                         clList(L_0__R3,
                                clList(clNEXT_METHOD_P,
                                       clNIL,
                                       clList(clNOT,
                                              clList(clNULL,
                                                     methods,
                                                     clEOA),
                                              clEOA),
                                       clEOA),
                                clEOA)); }
                { clObject L_4, L_3__R1, L_1__R3;
                  { clObject L_0__R4;
                    clSetq(L_0__R4, lambda_list);
                    clSetq(L_1__R3,
                           clMakeMethodLambdaList(L_0__R4, clEOA)); }
                  { clObject L_1__R4;
                    { clObject L_1__R5;
                      { clObject L_1__R6, L_0__R6;
                        clSetq(L_0__R6, lambda_list);
                        clSetq(L_1__R6, environment);
                        clSetq(L_1__R5,
                               clSpecializerDeclarations(L_0__R6,
                                                         L_1__R6,
                                                         clEOA)); }
                      clSetq(L_1__R4,
                             clAppend(decl, L_1__R5, clEOA)); }
                    clSetq(L_3__R1,
                           clListSTAR(clDECLARE, L_1__R4, clEOA)); }
                  { clObject L_1__R4;
                    clSetq(L_1__R4,
                           (clTrue(clConsp(name, clEOA)) ?
                            clSecond(name, clEOA) :
                            name));
                    clSetq(L_4,
                           clListSTAR(clBLOCK,
                                      L_1__R4,
                                      body__R1,
                                      clEOA)); }
                  clSetq(L_3,
                         clList(clDESTRUCTURING_BIND,
                                L_1__R3,
                                args,
                                L_3__R1,
                                L_4,
                                clEOA)); }
                clSetq(L_2,
                       clList(clFLET, L_1__R2, CONS_12, L_3, clEOA)); }
              clSetq(L_0, clList(clLAMBDA, L_1__R1, L_2, clEOA)); }
            { clObject L_1__R1;
              clSetq(L_1__R1, clList(clQUOTE, decl, clEOA));
              clSetq(L_1,
                     clList(keyDECLARATIONS,
                            L_1__R1,
                            keyDOCUMENTATION,
                            doc,
                            clEOA)); }
            return(clValues(L_0, L_1, clEOA)); } } } } } }

void clInitDevMeth __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(STR_COMPILE_TOPLEVEL__0,
         clCharpSimpleBaseString("COMPILE-TOPLEVEL"));
  clSetq(keyCOMPILE_TOPLEVEL,
         clMakeKeyword(STR_COMPILE_TOPLEVEL__0, clEOA));
  clSetq(STR_LOAD_TOPLEVEL__1,
         clCharpSimpleBaseString("LOAD-TOPLEVEL"));
  clSetq(keyLOAD_TOPLEVEL, clMakeKeyword(STR_LOAD_TOPLEVEL__1, clEOA));
  clSetq(STR_EXECUTE__2, clCharpSimpleBaseString("EXECUTE"));
  clSetq(keyEXECUTE, clMakeKeyword(STR_EXECUTE__2, clEOA));
  clSetq(CONS_2, clCons(keyEXECUTE, clNIL, clEOA));
  clSetq(CONS_1, clCons(keyLOAD_TOPLEVEL, CONS_2, clEOA));
  clSetq(CONS_0, clCons(keyCOMPILE_TOPLEVEL, CONS_1, clEOA));
  clSetq(STR_FUNCTION__3, clCharpSimpleBaseString("FUNCTION"));
  clSetq(keyFUNCTION, clMakeKeyword(STR_FUNCTION__3, clEOA));
  clSetq(STR_DEFAULT__4, clCharpSimpleBaseString("DEFAULT"));
  clSetq(keyDEFAULT, clMakeKeyword(STR_DEFAULT__4, clEOA));
  clSetq(CONS_4, clCons(clstarsymbol, clNIL, clEOA));
  clSetq(CONS_3, clCons(clQUOTE, CONS_4, clEOA));
  clSetq(I_3, clIntFixnum(3));
  clSetq(I_4, clIntFixnum(4));
  clSetq(STR_ARGS__5, clCharpSimpleBaseString("ARGS"));
  clSetq(STR_METHODS__6, clCharpSimpleBaseString("METHODS"));
  clSetq(CONS_6, clCons(clCNM_ARGS, clNIL, clEOA));
  clSetq(CONS_5, clCons(clampersandREST, CONS_6, clEOA));
  clSetq(CONS_9, clCons(clDYNAMIC_EXTENT, CONS_6, clEOA));
  clSetq(CONS_8, clCons(CONS_9, clNIL, clEOA));
  clSetq(CONS_7, clCons(clDECLARE, CONS_8, clEOA));
  clSetq(CONS_11, clCons(clNO_NEXT_METHOD, clNIL, clEOA));
  clSetq(CONS_10, clCons(clFUNCTION, CONS_11, clEOA));
  clSetq(CONS_16, clCons(clNEXT_METHOD_P, clNIL, clEOA));
  clSetq(CONS_15, clCons(clCALL_NEXT_METHOD, CONS_16, clEOA));
  clSetq(CONS_14, clCons(clINLINE, CONS_15, clEOA));
  clSetq(CONS_21, clCons(clCALL_NEXT_METHOD, clNIL, clEOA));
  clSetq(CONS_20, clCons(clFUNCTION, CONS_21, clEOA));
  clSetq(CONS_23, clCons(clFUNCTION, CONS_16, clEOA));
  clSetq(CONS_22, clCons(CONS_23, clNIL, clEOA));
  clSetq(CONS_19, clCons(CONS_20, CONS_22, clEOA));
  clSetq(CONS_18, clCons(clIGNORABLE, CONS_19, clEOA));
  clSetq(CONS_17, clCons(CONS_18, clNIL, clEOA));
  clSetq(CONS_13, clCons(CONS_14, CONS_17, clEOA));
  clSetq(CONS_12, clCons(clDECLARE, CONS_13, clEOA));
  clSetq(STR_DECLARATIONS__7, clCharpSimpleBaseString("DECLARATIONS"));
  clSetq(keyDECLARATIONS, clMakeKeyword(STR_DECLARATIONS__7, clEOA));
  clSetq(STR_DOCUMENTATION__8,
         clCharpSimpleBaseString("DOCUMENTATION"));
  clSetq(keyDOCUMENTATION, clMakeKeyword(STR_DOCUMENTATION__8, clEOA));
  clSetq(I_16, clIntFixnum(16));
  clSetq(CONS_27, clCons(clENVIRONMENT, clNIL, clEOA));
  clSetq(CONS_26, clCons(clLAMBDA_EXPRESSION, CONS_27, clEOA));
  clSetq(CONS_25, clCons(clMETHOD, CONS_26, clEOA));
  clSetq(CONS_24, clCons(clGENERIC_FUNCTION, CONS_25, clEOA));

  { clObject L_value395;
    clSetq(L_value395, clMakeClosure(0, clDeftype, clNULL_HOOK));
    cl_SETF_MacroFunction(L_value395, clDEFTYPE, clEOA); }
  (void) clDEFTYPE;
  clSetSymbolFunctionValue(clMAKE_METHOD_LAMBDA_STANDARD_GENERIC_FUNCTION_STANDARD_METHOD_T_T,
                           clMakeClosure(0,
                                         clMakeMethodLambdaStandardGenericFunctionStandardMethodTT,
                                         clNULL_HOOK));
  (void) clMAKE_METHOD_LAMBDA_STANDARD_GENERIC_FUNCTION_STANDARD_METHOD_T_T;
  { clObject CL_gf, CL_meta, CL_method;
    clSetq(CL_gf, clFdefinition(clMAKE_METHOD_LAMBDA, clEOA));
    clSetq(CL_meta, clFindType(clSTANDARD_METHOD, clEOA));
    { clObject L_2, L_1;
      clSetq(L_1, clStandardInstanceAccess(CL_meta, I_16, clEOA));
      { clObject L_5, L_4;
        clSetq(L_4,
               clList(clSTANDARD_GENERIC_FUNCTION_CLASSOBJ,
                      clSTANDARD_METHOD_CLASSOBJ,
                      clT_CLASSOBJ,
                      clT_CLASSOBJ,
                      clEOA));
        clSetq(L_5,
               clSymbolFunctionValue(clMAKE_METHOD_LAMBDA_STANDARD_GENERIC_FUNCTION_STANDARD_METHOD_T_T));
        clSetq(L_2,
               clMakeStaticSlots(clNIL,
                                 clNIL,
                                 clNIL,
                                 CONS_24,
                                 L_4,
                                 L_5,
                                 CL_gf,
                                 clNIL,
                                 clNIL,
                                 clNIL)); }
      clSetq(CL_method,
             clMakeStandardInstanceFromSlots(CL_meta, L_1, L_2)); }
    { clObject L_g409, L_g410;
      clSetq(L_g409, clFindType(clSTANDARD_GENERIC_FUNCTION, clEOA));
      clSetq(L_g410,
             clCons(CL_method,
                    clStandardInstanceAccess(L_g409, I_3, clEOA),
                    clEOA));
      { clObject L_1, L_0;
        clSetq(L_0, clStandardInstanceSlots(L_g409));
        clSetq(L_1, clFixnumIndex(I_3));
        clSetSlot(L_0, L_1, L_g410); } }
    { clObject L_g411, L_g412;
      clSetq(L_g411, clFindType(clSTANDARD_METHOD, clEOA));
      clSetq(L_g412,
             clCons(CL_method,
                    clStandardInstanceAccess(L_g411, I_3, clEOA),
                    clEOA));
      { clObject L_1, L_0;
        clSetq(L_0, clStandardInstanceSlots(L_g411));
        clSetq(L_1, clFixnumIndex(I_3));
        clSetSlot(L_0, L_1, L_g412); } }
    { clObject L_g413, L_g414;
      clSetq(L_g413, clFindType(clT, clEOA));
      clSetq(L_g414,
             clCons(CL_method,
                    clStandardInstanceAccess(L_g413, I_3, clEOA),
                    clEOA));
      { clObject L_1, L_0;
        clSetq(L_0, clStandardInstanceSlots(L_g413));
        clSetq(L_1, clFixnumIndex(I_3));
        clSetSlot(L_0, L_1, L_g414); } }
    { clObject L_g415, L_g416;
      clSetq(L_g415, clFindType(clT, clEOA));
      clSetq(L_g416,
             clCons(CL_method,
                    clStandardInstanceAccess(L_g415, I_3, clEOA),
                    clEOA));
      { clObject L_1, L_0;
        clSetq(L_0, clStandardInstanceSlots(L_g415));
        clSetq(L_1, clFixnumIndex(I_3));
        clSetSlot(L_0, L_1, L_g416); } }
    { clObject L_g418;
      clSetq(L_g418,
             clCons(CL_method,
                    clFuncallableStandardInstanceAccess(CL_gf,
                                                        I_3,
                                                        clEOA),
                    clEOA));
      { clObject L_1, L_0;
        clSetq(L_0, clStandardInstanceSlots(CL_gf));
        clSetq(L_1, clFixnumIndex(I_3));
        clSetSlot(L_0, L_1, L_g418); } } }

  clUnwind(4); }
