/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Tuesday the fifth of May, 1998, 3:53:13 pm CDT. */
#include <eclipse.h>

clObject cl1PLUS_FUNC(clProto), clAddInteger(clProto),
  clAllocateResource(clProto), clApply(clProto),
  clCanonicalizeSpecializer(clProto), clCar(clProto), clCdr(clProto),
  clCharEqual(clProto), clCharUpcase(clProto),
  clCharpSimpleBaseString __P((clCharp)), clClassOf(clProto),
  clCons(clProto), clDeallocateResource(clProto), clEndp(clProto),
  clEnsureGenericFunction(clProto), clEnsureMethod(clProto),
  clEq(clProto), clExpandType(clProto), clExtraArgs(clProto),
  clFastFind __P((clObject, clObject)), clFindClass(clProto),
  clFirstNonEmptyIndex __P((clObject, clObject)), clGeInteger(clProto),
  cl_SETF_Get(clProto), clGetResourceParameters(clProto),
  cl_SETF_GlobalDeclaration(clProto),
  clHashTableKey __P((clObject, clObject)),
  clHashTableNBuckets(clProto),
  clHashTableValue __P((clObject, clObject)), clLength(clProto),
  clList(clProto), clMakeHashTable(clProto), clMakeKeyword(clProto),
  clMakeResource(clProto), clMakeSymbol(clProto),
  clMissingArgs(clProto), clNot(clProto), clNull(clProto),
  cl_SETF_ResourceParameters(clProto), clResourceParameters(clProto),
  clRest(clProto), clStructref(clProto), clSxhash(clProto),
  clSymbolName(clProto), clSymbolPackage(clProto), clTruncate(clProto),
  clValues(clProto), clZerop(clProto);

extern clObject clCONS, clEQ, clNUMBER, clSPECIAL, clSYMBOL,
  clstarEQUALP_CIRCULARITY_HASH_TABLEstar, clARRAY, clARRAY_DIMENSION,
  clARRAY_RANK, clARRAY_TOTAL_SIZE, clCHARACTER, clCLASS_PROTOTYPE,
  clCLASS_SLOTS, clCLRHASH, clCOMPLEX, clDEFAULT_RESOURCE_MATCHER,
  clEQ_NUMBER, clEQUAL_HASH, clEQUALP, clEQUALP_HASH, clEQUALP_HASH1,
  clEQUALP_MAP, clGE, clGETHASH, clGLOBAL_VARIABLE, clHASH_TABLE,
  clHASH_TABLE_COUNT, clHASH_TABLE_TEST, clIDENTITY_REST, clIMAGPART,
  clLIST, clMETHOD_FUNCTION, clNO_NEXT_METHOD, clNULL, clREALPART,
  clRESOURCE, clROW_MAJOR_AREF, clSETF, clSIZE,
  clSLOT_VALUE_USING_CLASS, clSTANDARD_METHOD, clSTRUCTURE_OBJECT,
  clSXHASH, clX, clY;

static clObject CONS_0, CONS_1, CONS_2, CONS_3, CONS_4, CONS_5, CONS_6,
  I_0, I_1, I_2, keyCONSTRUCTOR, keyDECLARATIONS, keyDEINITIALIZER,
  keyDOCUMENTATION, keyFUNCTION, keyINITIALIZER, keyLAMBDA_LIST,
  keyMATCHER, keyNAME, keyQUALIFIERS, keySPECIALIZERS, keyTEST,
  STR_CONSTRUCTOR__7, STR_DECLARATIONS__4, STR_DEINITIALIZER__10,
  STR_DOCUMENTATION__5, STR_FUNCTION__3, STR_INITIALIZER__9,
  STR_LAMBDA_LIST__0, STR_LTV__12, STR_MATCHER__11, STR_NAME__6,
  STR_QUALIFIERS__1, STR_SPECIALIZERS__2, STR_TEST__8, SYM_0_LTV;

clObject clEqualp_clT_clT clVdecl(_ap)
{ clObject *L_args396 = clMakeBinding(),
  *L_methods397 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args396,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods397,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form401, x, y;
    clSetq(L_form401, *L_args396);
    if (clTrue(L_form401))
      { clObject L_top402;
        clSetq(L_top402, clCar(L_form401, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(x, L_top402); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form401))
      { clObject L_top403;
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_top403, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form401);
          clSetq(L_form401, clCdr(L_0, clEOA)); }
        clSetq(y, L_top403); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form401))
      { clObject L_0;
        clSetq(L_0, L_form401);
        clExtraArgs(L_0, clEOA); }
    { clObject L_1, L_0;
      clSetq(L_0, x);
      clSetq(L_1, y);
      return(clEq(L_0, L_1, clEOA)); } } }

clObject clEqualp_clNUMBER_clNUMBER clVdecl(_ap)
{ clObject *L_args404 = clMakeBinding(),
  *L_methods405 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args404,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods405,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form407, x, y;
    clSetq(L_form407, *L_args404);
    if (clTrue(L_form407))
      { clObject L_top408;
        clSetq(L_top408, clCar(L_form407, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form407);
          clSetq(L_form407, clCdr(L_0, clEOA)); }
        clSetq(x, L_top408); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form407))
      { clObject L_top409;
        { clObject L_0;
          clSetq(L_0, L_form407);
          clSetq(L_top409, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form407);
          clSetq(L_form407, clCdr(L_0, clEOA)); }
        clSetq(y, L_top409); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form407))
      { clObject L_0;
        clSetq(L_0, L_form407);
        clExtraArgs(L_0, clEOA); }
    { clObject L_1, L_0;
      clSetq(L_0, x);
      clSetq(L_1, y);
      return(clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                               L_0,
                               L_1,
                               clEOA)); } } }

clObject clEqualp_clCHARACTER_clCHARACTER clVdecl(_ap)
{ clObject *L_args410 = clMakeBinding(),
  *L_methods411 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args410,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods411,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form413, x, y;
    clSetq(L_form413, *L_args410);
    if (clTrue(L_form413))
      { clObject L_top414;
        clSetq(L_top414, clCar(L_form413, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form413);
          clSetq(L_form413, clCdr(L_0, clEOA)); }
        clSetq(x, L_top414); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form413))
      { clObject L_top415;
        { clObject L_0;
          clSetq(L_0, L_form413);
          clSetq(L_top415, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form413);
          clSetq(L_form413, clCdr(L_0, clEOA)); }
        clSetq(y, L_top415); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form413))
      { clObject L_0;
        clSetq(L_0, L_form413);
        clExtraArgs(L_0, clEOA); }
    { clObject L_1, L_0;
      clSetq(L_0, x);
      clSetq(L_1, y);
      return(clCharEqual(L_0, L_1, clEOA)); } } }

clObject clEqualp_clCONS_clCONS clVdecl(_ap)
{ clObject *L_args416 = clMakeBinding(),
  *L_methods417 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args416,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods417,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form419, x, y;
    clSetq(L_form419, *L_args416);
    if (clTrue(L_form419))
      { clObject L_top420;
        clSetq(L_top420, clCar(L_form419, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form419);
          clSetq(L_form419, clCdr(L_0, clEOA)); }
        clSetq(x, L_top420); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form419))
      { clObject L_top421;
        { clObject L_0;
          clSetq(L_0, L_form419);
          clSetq(L_top421, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form419);
          clSetq(L_form419, clCdr(L_0, clEOA)); }
        clSetq(y, L_top421); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form419))
      { clObject L_0;
        clSetq(L_0, L_form419);
        clExtraArgs(L_0, clEOA); }
    { clObject L_test;
      { clObject L_1, L_0;
        { clObject L_0__R1;
          clSetq(L_0__R1, x);
          clSetq(L_0, clCar(L_0__R1, clEOA)); }
        { clObject L_0__R1;
          clSetq(L_0__R1, y);
          clSetq(L_1, clCar(L_0__R1, clEOA)); }
        clSetq(L_test,
               clFuncallFunction(clSymbolFunctionValue(clEQUALP),
                                 L_0,
                                 L_1,
                                 clEOA)); }
      if (clTrue(L_test))
        { clObject L_1, L_0;
          { clObject L_0__R1;
            clSetq(L_0__R1, x);
            clSetq(L_0, clCdr(L_0__R1, clEOA)); }
          { clObject L_0__R1;
            clSetq(L_0__R1, y);
            clSetq(L_1, clCdr(L_0__R1, clEOA)); }
          return(clFuncallFunction(clSymbolFunctionValue(clEQUALP),
                                   L_0,
                                   L_1,
                                   clEOA)); }
      else return(clValues1(clNIL)); } } }

clObject clEqualp_clARRAY_clARRAY clVdecl(_ap)
{ clObject *L_args422 = clMakeBinding(),
  *L_methods423 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args422,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods423,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form425, x, y;
    clSetq(L_form425, *L_args422);
    if (clTrue(L_form425))
      { clObject L_top426;
        clSetq(L_top426, clCar(L_form425, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form425);
          clSetq(L_form425, clCdr(L_0, clEOA)); }
        clSetq(x, L_top426); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form425))
      { clObject L_top427;
        { clObject L_0;
          clSetq(L_0, L_form425);
          clSetq(L_top427, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form425);
          clSetq(L_form425, clCdr(L_0, clEOA)); }
        clSetq(y, L_top427); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form425))
      { clObject L_0;
        clSetq(L_0, L_form425);
        clExtraArgs(L_0, clEOA); }
    { clObject rank_x, size;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(rank_x,
               clFuncallFunction(clSymbolFunctionValue(clARRAY_RANK),
                                 L_0,
                                 clEOA)); }
      clSetq(size, clNIL);
      { clObject L_test;
        { clObject L_1;
          { clObject L_0__R1;
            clSetq(L_0__R1, y);
            clSetq(L_1,
                   clFuncallFunction(clSymbolFunctionValue(clARRAY_RANK),
                                     L_0__R1,
                                     clEOA)); }
          clSetq(L_test,
                 clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                                   rank_x,
                                   L_1,
                                   clEOA)); }
        if (clTrue(L_test))
          { clObject L_test__R1;
            if (clTrue(clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                                         I_1,
                                         rank_x,
                                         clEOA)))
              { clObject L_1, L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, x);
                  clSetq(L_0,
                         clSetq(size, clLength(L_0__R1, clEOA))); }
                { clObject L_0__R1;
                  clSetq(L_0__R1, y);
                  clSetq(L_1, clLength(L_0__R1, clEOA)); }
                clSetq(L_test__R1,
                       clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                                         L_0,
                                         L_1,
                                         clEOA)); }
            else
              { { clObject L_end428, axis;
                  { clObject L_0;
                    clSetq(L_0, x);
                    clSetq(L_end428,
                           clFuncallFunction(clSymbolFunctionValue(clARRAY_RANK),
                                             L_0,
                                             clEOA)); }
                  clSetq(axis, I_0);
                  clLabel(l_ITERATE429);
                  if (clTrue(clGeInteger(axis, L_end428, clEOA)))
                    { clSetq(L_test__R1, clT);
                      clLocalReturn(NIL__r1); }
                  { clObject L_test__R3;
                    { clObject L_0;
                      { clObject L_1, L_0__R1;
                        { clObject L_0__R2;
                          clSetq(L_0__R2, x);
                          clSetq(L_0__R1,
                                 clFuncallFunction(clSymbolFunctionValue(clARRAY_DIMENSION),
                                                   L_0__R2,
                                                   axis,
                                                   clEOA)); }
                        { clObject L_0__R2;
                          clSetq(L_0__R2, y);
                          clSetq(L_1,
                                 clFuncallFunction(clSymbolFunctionValue(clARRAY_DIMENSION),
                                                   L_0__R2,
                                                   axis,
                                                   clEOA)); }
                        clSetq(L_0,
                               clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                                                 L_0__R1,
                                                 L_1,
                                                 clEOA)); }
                      clSetq(L_test__R3, clNot(L_0, clEOA)); }
                    if (clTrue(L_test__R3))
                      { clSetq(L_test__R1, clNIL);
                        clLocalReturn(NIL__r1); } }
                  { clObject L_0;
                    clSetq(L_0, axis);
                    clSetq(axis, clAddInteger(L_0, I_1, clEOA)); }
                  goto l_ITERATE429; }
                clBlockEnd(NIL__r1); }
            if (clTrue(L_test__R1))
              { clObject L_end430, index;
                { clObject L_g432;
                  clSetq(L_g432, size);
                  if (clTrue(L_g432))
                    clSetq(L_end430, L_g432);
                  else
                    { clObject L_0;
                      clSetq(L_0, x);
                      clSetq(L_end430,
                             clFuncallFunction(clSymbolFunctionValue(clARRAY_TOTAL_SIZE),
                                               L_0,
                                               clEOA)); } }
                clSetq(index, I_0);
                clLabel(l_ITERATE431);
                { clObject L_test__R2;
                  { clObject L_1;
                    clSetq(L_1, L_end430);
                    clSetq(L_test__R2,
                           clGeInteger(index, L_1, clEOA)); }
                  if (clTrue(L_test__R2)) return(clValues1(clT)); }
                { clObject x_el, y_el;
                  { clObject L_0;
                    clSetq(L_0, x);
                    clSetq(x_el,
                           clFuncallFunction(clSymbolFunctionValue(clROW_MAJOR_AREF),
                                             L_0,
                                             index,
                                             clEOA)); }
                  { clObject L_0;
                    clSetq(L_0, y);
                    clSetq(y_el,
                           clFuncallFunction(clSymbolFunctionValue(clROW_MAJOR_AREF),
                                             L_0,
                                             index,
                                             clEOA)); }
                  if (clTrue(clNot(clFuncallFunction(clSymbolFunctionValue(clEQUALP),
                                                     x_el,
                                                     y_el,
                                                     clEOA),
                                   clEOA)))
                    return(clValues1(clNIL)); }
                { clObject L_0;
                  clSetq(L_0, index);
                  clSetq(index, clAddInteger(L_0, I_1, clEOA)); }
                goto l_ITERATE431; }
            else return(clValues1(clNIL)); }
        else return(clValues1(clNIL)); } } } }

clObject clEqualp_clHASH_TABLE_clHASH_TABLE clVdecl(_ap)
{ clObject *L_args433 = clMakeBinding(),
  *L_methods434 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args433,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods434,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form436, x, y;
    clSetq(L_form436, *L_args433);
    if (clTrue(L_form436))
      { clObject L_top437;
        clSetq(L_top437, clCar(L_form436, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form436);
          clSetq(L_form436, clCdr(L_0, clEOA)); }
        clSetq(x, L_top437); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form436))
      { clObject L_top438;
        { clObject L_0;
          clSetq(L_0, L_form436);
          clSetq(L_top438, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form436);
          clSetq(L_form436, clCdr(L_0, clEOA)); }
        clSetq(y, L_top438); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form436))
      { clObject L_0;
        clSetq(L_0, L_form436);
        clExtraArgs(L_0, clEOA); }
    { clObject n, test;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(n,
               clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_COUNT),
                                 L_0,
                                 clEOA)); }
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(test,
               clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_TEST),
                                 L_0,
                                 clEOA)); }
      { clObject L_test;
        { clObject L_1;
          { clObject L_0__R1;
            clSetq(L_0__R1, y);
            clSetq(L_1,
                   clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_COUNT),
                                     L_0__R1,
                                     clEOA)); }
          clSetq(L_test,
                 clFuncallFunction(clSymbolFunctionValue(clEQ_NUMBER),
                                   n,
                                   L_1,
                                   clEOA)); }
        if (clTrue(L_test))
          { clObject L_test__R1;
            { clObject L_1;
              { clObject L_0__R1;
                clSetq(L_0__R1, y);
                clSetq(L_1,
                       clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_TEST),
                                         L_0__R1,
                                         clEOA)); }
              clSetq(L_test__R1, clEq(test, L_1, clEOA)); }
            if (clTrue(L_test__R1))
              { clObject L_table0, L_limit1, L_index2;
                clSetq(L_table0, x);
                clSetq(L_limit1, clHashTableNBuckets(L_table0, clEOA));
                clSetq(L_index2, I_0);
                clLabel(l_LOOP3);
                { clObject L_values439, more, key_x, val_x;
                  { clMultipleValueCall(MVC);
                    clSetq(MVC, clSymbolFunctionValue(clLIST));
                    { clObject index;
                      clSetq(index,
                             clFirstNonEmptyIndex(L_table0, L_index2));
                      if (clTrue(clNot(clFuncallFunction(clSymbolFunctionValue(clGE),
                                                         index,
                                                         L_limit1,
                                                         clEOA),
                                       clEOA)))
                      { clSetq(L_index2, cl1PLUS_FUNC(index, clEOA));
                        { clObject L_1;
                          clSetq(L_1, clHashTableKey(L_table0, index));
                          clValues(clT,
                                   L_1,
                                   clHashTableValue(L_table0, index),
                                   clEOA); } }
                      else
                      clValues1(clNIL); }
                    clAccumulateValues(MVC);
                    clSetq(L_values439, clMultipleValueFuncall(MVC)); }
                  clSetq(more, clCar(L_values439, clEOA));
                  { clObject L_0;
                    { clObject L_0__R1;
                      clSetq(L_0__R1, L_values439);
                      clSetq(L_0,
                             clSetq(L_values439,
                                    clCdr(L_0__R1, clEOA))); }
                    clSetq(key_x, clCar(L_0, clEOA)); }
                  { clObject L_0;
                    { clObject L_0__R1;
                      clSetq(L_0__R1, L_values439);
                      clSetq(L_0,
                             clSetq(L_values439,
                                    clCdr(L_0__R1, clEOA))); }
                    clSetq(val_x, clCar(L_0, clEOA)); }
                  if (clTrue(more))
                    { clObject L_values443, val_y, foundp;
                      { clMultipleValueCall(MVC__r1);
                        clSetq(MVC__r1, clSymbolFunctionValue(clLIST));
                        { clObject L_1;
                          clSetq(L_1, y);
                          clFuncallFunction(clSymbolFunctionValue(clGETHASH),
                                            key_x,
                                            L_1,
                                            clEOA); }
                        clAccumulateValues(MVC__r1);
                        clSetq(L_values443,
                               clMultipleValueFuncall(MVC__r1)); }
                      clSetq(val_y, clCar(L_values443, clEOA));
                      { clObject L_0;
                        { clObject L_0__R1;
                          clSetq(L_0__R1, L_values443);
                          clSetq(L_0,
                                 clSetq(L_values443,
                                        clCdr(L_0__R1, clEOA))); }
                        clSetq(foundp, clCar(L_0, clEOA)); }
                      { clObject L_test__R3;
                        { clObject L_0;
                          clSetq(L_0,
                                 (clTrue(foundp) ?
                                  clFuncallFunction(clSymbolFunctionValue(clEQUALP),
                                                    val_x,
                                                    val_y,
                                                    clEOA) :
                                  clNIL));
                          clSetq(L_test__R3, clNot(L_0, clEOA)); }
                        if (clTrue(L_test__R3))
                        return(clValues1(clNIL)); } }
                  else return(clValues1(clT)); }
                goto l_LOOP3; }
            else return(clValues1(clNIL)); }
        else return(clValues1(clNIL)); } } } }

clObject clEqualp_clSTRUCTURE_OBJECT_clSTRUCTURE_OBJECT clVdecl(_ap)
{ clObject *L_args444 = clMakeBinding(),
  *L_methods445 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args444,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods445,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form447, x, y;
    clSetq(L_form447, *L_args444);
    if (clTrue(L_form447))
      { clObject L_top448;
        clSetq(L_top448, clCar(L_form447, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form447);
          clSetq(L_form447, clCdr(L_0, clEOA)); }
        clSetq(x, L_top448); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form447))
      { clObject L_top449;
        { clObject L_0;
          clSetq(L_0, L_form447);
          clSetq(L_top449, clCar(L_0, clEOA)); }
        { clObject L_0;
          clSetq(L_0, L_form447);
          clSetq(L_form447, clCdr(L_0, clEOA)); }
        clSetq(y, L_top449); }
    else clSetq(y, clMissingArgs(I_2, clEOA));
    if (clTrue(L_form447))
      { clObject L_0;
        clSetq(L_0, L_form447);
        clExtraArgs(L_0, clEOA); }
    { clObject class_x;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(class_x, clClassOf(L_0, clEOA)); }
      { clObject L_test;
        { clObject L_1;
          { clObject L_0__R1;
            clSetq(L_0__R1, y);
            clSetq(L_1, clClassOf(L_0__R1, clEOA)); }
          clSetq(L_test, clEq(class_x, L_1, clEOA)); }
        if (clTrue(L_test))
          { clObject L_end450, i;
            clSetq(L_end450,
                   clLength(clFuncallFunction(clSymbolFunctionValue(clCLASS_SLOTS),
                                              class_x,
                                              clEOA),
                            clEOA));
            clSetq(i, I_0);
            clLabel(l_ITERATE451);
            if (clTrue(clGeInteger(i, L_end450, clEOA)))
              return(clValues1(clT));
            { clObject L_test__R1;
              { clObject L_0;
                { clObject L_1, L_0__R1;
                  { clObject L_0__R2;
                    clSetq(L_0__R2, x);
                    clSetq(L_0__R1, clStructref(L_0__R2, i, clEOA)); }
                  { clObject L_0__R2;
                    clSetq(L_0__R2, y);
                    clSetq(L_1, clStructref(L_0__R2, i, clEOA)); }
                  clSetq(L_0,
                         clFuncallFunction(clSymbolFunctionValue(clEQUALP),
                                           L_0__R1,
                                           L_1,
                                           clEOA)); }
                clSetq(L_test__R1, clNot(L_0, clEOA)); }
              if (clTrue(L_test__R1)) return(clValues1(clNIL)); }
            { clObject L_0;
              clSetq(L_0, i);
              clSetq(i, clAddInteger(L_0, I_1, clEOA)); }
            goto l_ITERATE451; }
        else return(clValues1(clNIL)); } } } }

static clObject clLambda clVdecl(_ap)
{ clObject L_resource4;
  { clBeginParse(_ap);
    clSetq(L_resource4,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_object5;
    clSetq(L_object5, clMakeHashTable(keyTEST, clEQ, clEOA));
    { clObject L_arg457, L_value456;
      clSetq(L_arg457, L_resource4);
      { clObject L_0;
        clSetq(L_0, clCons(L_object5, clList(clEOA), clEOA));
        clSetq(L_value456,
               clCons(L_0,
                      clResourceParameters(L_arg457, clEOA),
                      clEOA)); }
      cl_SETF_ResourceParameters(L_value456, L_arg457, clEOA); }
    return(clValues1(L_object5)); } }

static clObject clLambda_r1 clVdecl(_ap)
{ clObject equalp_map, L_resource4;
  { clBeginParse(_ap);
    clSetq(equalp_map,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_resource4,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form458;
    { clObject L_1, L_0;
      clSetq(L_0, equalp_map);
      clSetq(L_1, L_resource4);
      clSetq(L_form458, clGetResourceParameters(L_0, L_1, clEOA)); }
    if (clTrue(L_form458)) clExtraArgs(L_form458, clEOA);
    { clObject L_0;
      clSetq(L_0, equalp_map);
      return(clFuncallFunction(clSymbolFunctionValue(clCLRHASH),
                               L_0,
                               clEOA)); } } }

clObject clEqualpHash clVdecl(_ap)
{ clObject x;
  { clBeginParse(_ap);
    clSetq(x, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject STARequalp_circularity_hash_tableSTAR;
    clSetq(STARequalp_circularity_hash_tableSTAR,
           clAllocateResource(clEQUALP_MAP, clEOA));
    clDbind(clstarEQUALP_CIRCULARITY_HASH_TABLEstar);
    clSetSymbolValueValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                          STARequalp_circularity_hash_tableSTAR);
    { clMultipleValueProg1(MVP1);
      { clObject L_0;
        clSetq(L_0, x);
        clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                          L_0,
                          clEOA); }
      clSaveValues(MVP1);
      if (clTrue(clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                               clEOA)))
        clDeallocateResource(clEQUALP_MAP,
                             clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                                           clEOA),
                             clEOA);
      clRestoreValues(MVP1);
      clUnwindReturn(clSavedValue(MVP1), 1); } } }

clObject clEqualpHash1_clT clVdecl(_ap)
{ clObject *L_args466 = clMakeBinding(),
  *L_methods467 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args466,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods467,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form469, x;
    clSetq(L_form469, *L_args466);
    if (clTrue(L_form469))
      { clObject L_top470;
        clSetq(L_top470, clCar(L_form469, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form469);
          clSetq(L_form469, clCdr(L_0, clEOA)); }
        clSetq(x, L_top470); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form469))
      { clObject L_0;
        clSetq(L_0, L_form469);
        clExtraArgs(L_0, clEOA); }
    { clObject L_0;
      clSetq(L_0, x);
      return(clFuncallFunction(clSymbolFunctionValue(clEQUAL_HASH),
                               L_0,
                               clEOA)); } } }

clObject clEqualpHash1_clCHARACTER clVdecl(_ap)
{ clObject *L_args471 = clMakeBinding(),
  *L_methods472 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args471,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods472,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form474, x;
    clSetq(L_form474, *L_args471);
    if (clTrue(L_form474))
      { clObject L_top475;
        clSetq(L_top475, clCar(L_form474, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form474);
          clSetq(L_form474, clCdr(L_0, clEOA)); }
        clSetq(x, L_top475); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form474))
      { clObject L_0;
        clSetq(L_0, L_form474);
        clExtraArgs(L_0, clEOA); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, x);
        clSetq(L_0, clCharUpcase(L_0__R1, clEOA)); }
      return(clValues1(clEqHash(L_0))); } } }

clObject clEqualpHash1_clNUMBER clVdecl(_ap)
{ clObject *L_args476 = clMakeBinding(),
  *L_methods477 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args476,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods477,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form479, x;
    clSetq(L_form479, *L_args476);
    if (clTrue(L_form479))
      { clObject L_top480;
        clSetq(L_top480, clCar(L_form479, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form479);
          clSetq(L_form479, clCdr(L_0, clEOA)); }
        clSetq(x, L_top480); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form479))
      { clObject L_0;
        clSetq(L_0, L_form479);
        clExtraArgs(L_0, clEOA); }
    { clObject L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, x);
        clSetq(L_0, clTruncate(L_0__R1, clEOA)); }
      return(clValues1(clEqHash(L_0))); } } }

clObject clEqualpHash1_clCOMPLEX clVdecl(_ap)
{ clObject *L_args481 = clMakeBinding(),
  *L_methods482 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args481,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods482,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form484, x;
    clSetq(L_form484, *L_args481);
    if (clTrue(L_form484))
      { clObject L_top485;
        clSetq(L_top485, clCar(L_form484, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form484);
          clSetq(L_form484, clCdr(L_0, clEOA)); }
        clSetq(x, L_top485); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form484))
      { clObject L_0;
        clSetq(L_0, L_form484);
        clExtraArgs(L_0, clEOA); }
    { clObject img, realhash;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(img,
               clFuncallFunction(clSymbolFunctionValue(clIMAGPART),
                                 L_0,
                                 clEOA)); }
      { clObject L_0;
        { clObject L_0__R1;
          clSetq(L_0__R1, x);
          clSetq(L_0,
                 clFuncallFunction(clSymbolFunctionValue(clREALPART),
                                   L_0__R1,
                                   clEOA)); }
        clSetq(realhash,
               clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                 L_0,
                                 clEOA)); }
      if (clTrue(clZerop(img, clEOA)))
        return(clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                 realhash,
                                 clEOA));
      else
        return(clValues1(clMergeHashCodes(realhash,
                                          clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                                            img,
                                                            clEOA)))); } } }

clObject clEqualpHash1_clHASH_TABLE clVdecl(_ap)
{ clObject *L_args486 = clMakeBinding(),
  *L_methods487 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args486,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods487,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form489, x;
    clSetq(L_form489, *L_args486);
    if (clTrue(L_form489))
      { clObject L_top490;
        clSetq(L_top490, clCar(L_form489, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form489);
          clSetq(L_form489, clCdr(L_0, clEOA)); }
        clSetq(x, L_top490); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form489))
      { clObject L_0;
        clSetq(L_0, L_form489);
        clExtraArgs(L_0, clEOA); }
    { clObject L_1, L_0;
      { clObject L_0__R1;
        { clObject L_0__R2;
          clSetq(L_0__R2, x);
          clSetq(L_0__R1,
                 clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_COUNT),
                                   L_0__R2,
                                   clEOA)); }
        clSetq(L_0, clEqHash(L_0__R1)); }
      { clObject L_0__R1;
        { clObject L_0__R2;
          clSetq(L_0__R2, x);
          clSetq(L_0__R1,
                 clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_TEST),
                                   L_0__R2,
                                   clEOA)); }
        clSetq(L_1, clEqHash(L_0__R1)); }
      return(clValues1(clMergeHashCodes(L_0, L_1))); } } }

clObject clEqualpHash1_clCONS clVdecl(_ap)
{ clObject *L_args491 = clMakeBinding(),
  *L_methods492 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args491,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods492,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form494, x;
    clSetq(L_form494, *L_args491);
    if (clTrue(L_form494))
      { clObject L_top495;
        clSetq(L_top495, clCar(L_form494, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form494);
          clSetq(L_form494, clCdr(L_0, clEOA)); }
        clSetq(x, L_top495); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form494))
      { clObject L_0;
        clSetq(L_0, L_form494);
        clExtraArgs(L_0, clEOA); }
    { clObject L_g499;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(L_g499,
               clFuncallFunction(clSymbolFunctionValue(clGETHASH),
                                 L_0,
                                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                                               clEOA),
                                 clEOA)); }
      if (clTrue(L_g499))
        return(clValues1(L_g499));
      else
        { clObject L_arg501, L_arg502, L_value500;
          clSetq(L_arg501, x);
          clSetq(L_arg502,
                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                               clEOA));
          { clObject x__R1, n, next;
            clSetq(x__R1, x);
            { clObject L_0;
              { clObject L_0__R1;
                clSetq(L_0__R1, x);
                clSetq(L_0, clCar(L_0__R1, clEOA)); }
              clSetq(n,
                     clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                       L_0,
                                       clEOA)); }
            { clObject L_0;
              clSetq(L_0, x);
              clSetq(next, clCdr(L_0, clEOA)); }
            clLabel(l_ITERATE503);
            if (clTrue(clNIL))
              { clSetq(L_value500, clNIL); clLocalReturn(NIL); }
            { clObject L_class_name505;
              clSetq(L_class_name505, clInstanceTag(next));
              if (_clEq(L_class_name505, clNULL))
                { clSetq(L_value500, n); clLocalReturn(NIL); }
              else if (!_clEq(L_class_name505, clCONS))
                { { clObject L_0;
                    clSetq(L_0,
                           clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                             next,
                                             clEOA));
                    clSetq(L_value500, clMergeHashCodes(L_0, n)); }
                  clLocalReturn(NIL); } }
            { clObject L_value508, L_value509, L_value510;
              clSetq(L_value508, next);
              clSetq(L_value509,
                     clMergeHashCodes(n,
                                      clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                                        clCar(x__R1,
                                                              clEOA),
                                                        clEOA)));
              clSetq(L_value510, clCdr(next, clEOA));
              clSetq(x__R1, L_value508);
              clSetq(n, L_value509);
              clSetq(next, L_value510); }
            goto l_ITERATE503; }
          clBlockEnd(NIL);
          { clObject L_0;
            clSetq(L_0, L_value500);
            return(clFuncallFunction(clFdefinition(CONS_3, clEOA),
                                     L_0,
                                     L_arg501,
                                     L_arg502,
                                     clEOA)); } } } } }

clObject clEqualpHash1_clARRAY clVdecl(_ap)
{ clObject *L_args511 = clMakeBinding(),
  *L_methods512 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args511,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods512,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form514, x;
    clSetq(L_form514, *L_args511);
    if (clTrue(L_form514))
      { clObject L_top515;
        clSetq(L_top515, clCar(L_form514, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form514);
          clSetq(L_form514, clCdr(L_0, clEOA)); }
        clSetq(x, L_top515); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form514))
      { clObject L_0;
        clSetq(L_0, L_form514);
        clExtraArgs(L_0, clEOA); }
    { clObject L_g519;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(L_g519,
               clFuncallFunction(clSymbolFunctionValue(clGETHASH),
                                 L_0,
                                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                                               clEOA),
                                 clEOA)); }
      if (clTrue(L_g519))
        return(clValues1(L_g519));
      else
        { clObject L_arg521, L_arg522, L_value520;
          clSetq(L_arg521, x);
          clSetq(L_arg522,
                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                               clEOA));
          { clObject i, L_g6;
            clSetq(i, I_1);
            { clObject L_0;
              clSetq(L_0, x);
              clSetq(L_g6,
                     clFuncallFunction(clSymbolFunctionValue(clSIZE),
                                       L_0,
                                       clEOA)); }
            { clObject code;
              { clObject L_0;
                { clObject L_0__R1;
                  clSetq(L_0__R1, x);
                  clSetq(L_0,
                         clFuncallFunction(clSymbolFunctionValue(clROW_MAJOR_AREF),
                                           L_0__R1,
                                           I_0,
                                           clEOA)); }
                clSetq(code,
                       clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                         L_0,
                                         clEOA)); }
              clLabel(NEXT_LOOP);
              if (clTrue(clFuncallFunction(clSymbolFunctionValue(clGE),
                                           i,
                                           L_g6,
                                           clEOA)))
                goto END_LOOP;
              { clObject L_1, L_0;
                clSetq(L_0, code);
                { clObject L_0__R1;
                  { clObject L_0__R2;
                    clSetq(L_0__R2, x);
                    clSetq(L_0__R1,
                           clFuncallFunction(clSymbolFunctionValue(clROW_MAJOR_AREF),
                                             L_0__R2,
                                             i,
                                             clEOA)); }
                  clSetq(L_1,
                         clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                           L_0__R1,
                                           clEOA)); }
                clSetq(code, clMergeHashCodes(L_0, L_1)); }
              { clObject L_0;
                clSetq(L_0, i);
                clSetq(i, cl1PLUS_FUNC(L_0, clEOA)); }
              goto NEXT_LOOP;
              clLabel(END_LOOP);
              clSetq(L_value520, code);
              clLocalReturn(NIL);
              clSetq(L_value520, clNIL);
              clBlockEnd(NIL); } }
          { clObject L_0;
            clSetq(L_0, L_value520);
            return(clFuncallFunction(clFdefinition(CONS_3, clEOA),
                                     L_0,
                                     L_arg521,
                                     L_arg522,
                                     clEOA)); } } } } }

clObject clEqualpHash1_clSTRUCTURE_OBJECT clVdecl(_ap)
{ clObject *L_args523 = clMakeBinding(),
  *L_methods524 = clMakeBinding();
  { clBeginParse(_ap);
    clSetq(*L_args523,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*L_methods524,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_form526, x;
    clSetq(L_form526, *L_args523);
    if (clTrue(L_form526))
      { clObject L_top527;
        clSetq(L_top527, clCar(L_form526, clEOA));
        { clObject L_0;
          clSetq(L_0, L_form526);
          clSetq(L_form526, clCdr(L_0, clEOA)); }
        clSetq(x, L_top527); }
    else clSetq(x, clMissingArgs(I_1, clEOA));
    if (clTrue(L_form526))
      { clObject L_0;
        clSetq(L_0, L_form526);
        clExtraArgs(L_0, clEOA); }
    { clObject L_g531;
      { clObject L_0;
        clSetq(L_0, x);
        clSetq(L_g531,
               clFuncallFunction(clSymbolFunctionValue(clGETHASH),
                                 L_0,
                                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                                               clEOA),
                                 clEOA)); }
      if (clTrue(L_g531))
        return(clValues1(L_g531));
      else
        { clObject L_arg533, L_arg534;
          clSetq(L_arg533, x);
          clSetq(L_arg534,
                 clSymbolValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                               clEOA));
          { clObject code;
            clSetq(code, I_0);
            { clObject CL_class;
              { clObject L_0;
                clSetq(L_0, x);
                clSetq(CL_class, clClassOf(L_0, clEOA)); }
              { clObject slot, L_g7;
                clSetq(slot, clNIL);
                clSetq(L_g7,
                       clFuncallFunction(clSymbolFunctionValue(clCLASS_SLOTS),
                                         CL_class,
                                         clEOA));
                clLabel(NEXT_LOOP);
                if (clTrue(clEndp(L_g7, clEOA))) goto END_LOOP;
                clSetq(slot, clCar(L_g7, clEOA));
                { clObject L_0;
                  clSetq(L_0, L_g7);
                  clSetq(L_g7, clCdr(L_0, clEOA)); }
                { clObject L_1, L_0;
                  clSetq(L_0, code);
                  { clObject L_0__R1;
                    { clObject L_2, L_1__R1;
                      clSetq(L_1__R1, x);
                      clSetq(L_2, slot);
                      clSetq(L_0__R1,
                             clFuncallFunction(clSymbolFunctionValue(clSLOT_VALUE_USING_CLASS),
                                               CL_class,
                                               L_1__R1,
                                               L_2,
                                               clEOA)); }
                    clSetq(L_1,
                           clFuncallFunction(clSymbolFunctionValue(clEQUALP_HASH1),
                                             L_0__R1,
                                             clEOA)); }
                  clSetq(code, clMergeHashCodes(L_0, L_1)); }
                goto NEXT_LOOP;
                clLabel(END_LOOP); } } }
          return(clFuncallFunction(clFdefinition(CONS_3, clEOA),
                                   clNIL,
                                   L_arg533,
                                   L_arg534,
                                   clEOA)); } } } }

clObject clSxhash clVdecl(_ap)
{ clObject object;
  { clBeginParse(_ap);
    clSetq(object,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_object535, L_class_name536, L_cpl537;
    clSetq(L_object535, object);
    clSetq(L_class_name536, clInstanceTag(L_object535));
    clSetq(L_cpl537, clInstanceCpl(L_object535));
    if (clTrue((_clEq(L_class_name536, clSYMBOL) ? CONS_5 :
                (_clEq(L_class_name536, clNULL) ? CONS_6 : clNIL))))
      { clObject L_1, L_0;
        { clObject L_0__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2, object);
            clSetq(L_0__R1, clSymbolPackage(L_0__R2, clEOA)); }
          clSetq(L_0,
                 clFuncallFunction(clSymbolFunctionValue(clEQUAL_HASH),
                                   L_0__R1,
                                   clEOA)); }
        { clObject L_0__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2, object);
            clSetq(L_0__R1, clSymbolName(L_0__R2, clEOA)); }
          clSetq(L_1,
                 clFuncallFunction(clSymbolFunctionValue(clEQUAL_HASH),
                                   L_0__R1,
                                   clEOA)); }
        return(clValues1(clMergeHashCodes(L_0, L_1))); }
    else if (clTrue(clFastFind(SYM_0_LTV, L_cpl537)))
      { clObject L_1, L_0;
        { clObject L_0__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2, object);
            clSetq(L_0__R1,
                   clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_COUNT),
                                     L_0__R2,
                                     clEOA)); }
          clSetq(L_0, clEqHash(L_0__R1)); }
        { clObject L_0__R1;
          { clObject L_0__R2;
            clSetq(L_0__R2, object);
            clSetq(L_0__R1,
                   clFuncallFunction(clSymbolFunctionValue(clHASH_TABLE_TEST),
                                     L_0__R2,
                                     clEOA)); }
          clSetq(L_1, clSxhash(L_0__R1, clEOA)); }
        return(clValues1(clMergeHashCodes(L_0, L_1))); }
    else
      { clObject L_0;
        clSetq(L_0, object);
        return(clFuncallFunction(clSymbolFunctionValue(clEQUAL_HASH),
                                 L_0,
                                 clEOA)); } } }

void clInitEqualp __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(STR_LAMBDA_LIST__0, clCharpSimpleBaseString("LAMBDA-LIST"));
  clSetq(keyLAMBDA_LIST, clMakeKeyword(STR_LAMBDA_LIST__0, clEOA));
  clSetq(CONS_1, clCons(clY, clNIL, clEOA));
  clSetq(CONS_0, clCons(clX, CONS_1, clEOA));
  clSetq(STR_QUALIFIERS__1, clCharpSimpleBaseString("QUALIFIERS"));
  clSetq(keyQUALIFIERS, clMakeKeyword(STR_QUALIFIERS__1, clEOA));
  clSetq(STR_SPECIALIZERS__2, clCharpSimpleBaseString("SPECIALIZERS"));
  clSetq(keySPECIALIZERS, clMakeKeyword(STR_SPECIALIZERS__2, clEOA));
  clSetq(STR_FUNCTION__3, clCharpSimpleBaseString("FUNCTION"));
  clSetq(keyFUNCTION, clMakeKeyword(STR_FUNCTION__3, clEOA));
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_2, clIntFixnum(2));
  clSetq(STR_DECLARATIONS__4, clCharpSimpleBaseString("DECLARATIONS"));
  clSetq(keyDECLARATIONS, clMakeKeyword(STR_DECLARATIONS__4, clEOA));
  clSetq(STR_DOCUMENTATION__5,
         clCharpSimpleBaseString("DOCUMENTATION"));
  clSetq(keyDOCUMENTATION, clMakeKeyword(STR_DOCUMENTATION__5, clEOA));
  clSetq(I_0, clIntFixnum(0));
  clSetq(STR_NAME__6, clCharpSimpleBaseString("NAME"));
  clSetq(keyNAME, clMakeKeyword(STR_NAME__6, clEOA));
  clSetq(STR_CONSTRUCTOR__7, clCharpSimpleBaseString("CONSTRUCTOR"));
  clSetq(keyCONSTRUCTOR, clMakeKeyword(STR_CONSTRUCTOR__7, clEOA));
  clSetq(STR_TEST__8, clCharpSimpleBaseString("TEST"));
  clSetq(keyTEST, clMakeKeyword(STR_TEST__8, clEOA));
  clSetq(STR_INITIALIZER__9, clCharpSimpleBaseString("INITIALIZER"));
  clSetq(keyINITIALIZER, clMakeKeyword(STR_INITIALIZER__9, clEOA));
  clSetq(STR_DEINITIALIZER__10,
         clCharpSimpleBaseString("DEINITIALIZER"));
  clSetq(keyDEINITIALIZER,
         clMakeKeyword(STR_DEINITIALIZER__10, clEOA));
  clSetq(STR_MATCHER__11, clCharpSimpleBaseString("MATCHER"));
  clSetq(keyMATCHER, clMakeKeyword(STR_MATCHER__11, clEOA));
  clSetq(CONS_2, clCons(clX, clNIL, clEOA));
  clSetq(CONS_4, clCons(clGETHASH, clNIL, clEOA));
  clSetq(CONS_3, clCons(clSETF, CONS_4, clEOA));
  clSetq(CONS_6, clCons(clNULL, clNIL, clEOA));
  clSetq(CONS_5, clCons(clSYMBOL, CONS_6, clEOA));
  clSetq(STR_LTV__12, clCharpSimpleBaseString("LTV"));
  clSetq(SYM_0_LTV, clMakeSymbol(STR_LTV__12, clEOA));
  clSetq(SYM_0_LTV, clExpandType(clHASH_TABLE, clNIL, clEOA));

  clEnsureGenericFunction(clEQUALP, keyLAMBDA_LIST, CONS_0, clEOA);
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clT, clEOA));
      clSetq(L_6,
             clList(L_0__R1, clCanonicalizeSpecializer(clT, clEOA),
                    clEOA)); }
    clSetq(L_8, clMakeClosure(0, clEqualp_clT_clT, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clNUMBER, clEOA));
      clSetq(L_6,
             clList(L_0__R1,
                    clCanonicalizeSpecializer(clNUMBER, clEOA),
                    clEOA)); }
    clSetq(L_8,
           clMakeClosure(0, clEqualp_clNUMBER_clNUMBER, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clCHARACTER, clEOA));
      clSetq(L_6,
             clList(L_0__R1,
                    clCanonicalizeSpecializer(clCHARACTER, clEOA),
                    clEOA)); }
    clSetq(L_8,
           clMakeClosure(0,
                         clEqualp_clCHARACTER_clCHARACTER,
                         clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clCONS, clEOA));
      clSetq(L_6,
             clList(L_0__R1, clCanonicalizeSpecializer(clCONS, clEOA),
                    clEOA)); }
    clSetq(L_8, clMakeClosure(0, clEqualp_clCONS_clCONS, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clARRAY, clEOA));
      clSetq(L_6,
             clList(L_0__R1, clCanonicalizeSpecializer(clARRAY, clEOA),
                    clEOA)); }
    clSetq(L_8,
           clMakeClosure(0, clEqualp_clARRAY_clARRAY, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1, clCanonicalizeSpecializer(clHASH_TABLE, clEOA));
      clSetq(L_6,
             clList(L_0__R1,
                    clCanonicalizeSpecializer(clHASH_TABLE, clEOA),
                    clEOA)); }
    clSetq(L_8,
           clMakeClosure(0,
                         clEqualp_clHASH_TABLE_clHASH_TABLE,
                         clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP, clEOA));
    { clObject L_0__R1;
      clSetq(L_0__R1,
             clCanonicalizeSpecializer(clSTRUCTURE_OBJECT, clEOA));
      clSetq(L_6,
             clList(L_0__R1,
                    clCanonicalizeSpecializer(clSTRUCTURE_OBJECT,
                                              clEOA),
                    clEOA)); }
    clSetq(L_8,
           clMakeClosure(0,
                         clEqualp_clSTRUCTURE_OBJECT_clSTRUCTURE_OBJECT,
                         clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_0,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  cl_SETF_GlobalDeclaration(clT,
                            clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                            clGLOBAL_VARIABLE,
                            clSPECIAL,
                            clEOA);
  clSetSymbolValueValue(clstarEQUALP_CIRCULARITY_HASH_TABLEstar,
                        clNIL);
  (void) clstarEQUALP_CIRCULARITY_HASH_TABLEstar;
  { clObject L_resource4;
    { clObject L_7, L_5, L_3;
      clSetq(L_3, clMakeClosure(0, clLambda, clNULL_HOOK));
      clSetq(L_5, clSymbolFunctionValue(clIDENTITY_REST));
      clSetq(L_7, clMakeClosure(0, clLambda_r1, clNULL_HOOK));
      clSetq(L_resource4,
             clMakeResource(keyNAME,
                            clEQUALP_MAP,
                            keyCONSTRUCTOR,
                            L_3,
                            keyINITIALIZER,
                            L_5,
                            keyDEINITIALIZER,
                            L_7,
                            keyMATCHER,
                            clSymbolFunctionValue(clDEFAULT_RESOURCE_MATCHER),
                            clEOA)); }
    cl_SETF_Get(L_resource4, clEQUALP_MAP, clRESOURCE, clEOA);
    { clObject L_end462, n;
      clSetq(L_end462, (clTrue(clNIL) ? clNIL : I_0));
      clSetq(n, I_0);
      clLabel(l_ITERATE463);
      { clObject L_test;
        { clObject L_1;
          clSetq(L_1, L_end462);
          clSetq(L_test, clGeInteger(n, L_1, clEOA)); }
        if (clTrue(L_test)) clLocalReturn(NIL); }
      clDeallocateResource(clEQUALP_MAP,
                           clAllocateResource(clEQUALP_MAP, clEOA),
                           clEOA);
      { clObject L_0;
        clSetq(L_0, n);
        clSetq(n, clAddInteger(L_0, I_1, clEOA)); }
      goto l_ITERATE463; }
    clBlockEnd(NIL);
    (void) clEQUALP_MAP; }
  clSetSymbolFunctionValue(clEQUALP_HASH,
                           clMakeClosure(0,
                                         clEqualpHash,
                                         clNULL_HOOK));
  (void) clEQUALP_HASH;
  clEnsureGenericFunction(clEQUALP_HASH1,
                          keyLAMBDA_LIST,
                          CONS_2,
                          clEOA);
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6, clList(clCanonicalizeSpecializer(clT, clEOA), clEOA));
    clSetq(L_8, clMakeClosure(0, clEqualpHash1_clT, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clCHARACTER, clEOA),
                  clEOA));
    clSetq(L_8,
           clMakeClosure(0, clEqualpHash1_clCHARACTER, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clNUMBER, clEOA), clEOA));
    clSetq(L_8, clMakeClosure(0, clEqualpHash1_clNUMBER, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clCOMPLEX, clEOA), clEOA));
    clSetq(L_8,
           clMakeClosure(0, clEqualpHash1_clCOMPLEX, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clHASH_TABLE, clEOA),
                  clEOA));
    clSetq(L_8,
           clMakeClosure(0, clEqualpHash1_clHASH_TABLE, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clCONS, clEOA), clEOA));
    clSetq(L_8, clMakeClosure(0, clEqualpHash1_clCONS, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clARRAY, clEOA), clEOA));
    clSetq(L_8, clMakeClosure(0, clEqualpHash1_clARRAY, clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  { clObject L_8, L_6, L_0;
    clSetq(L_0, clEnsureGenericFunction(clEQUALP_HASH1, clEOA));
    clSetq(L_6,
           clList(clCanonicalizeSpecializer(clSTRUCTURE_OBJECT, clEOA),
                  clEOA));
    clSetq(L_8,
           clMakeClosure(0,
                         clEqualpHash1_clSTRUCTURE_OBJECT,
                         clNULL_HOOK));
    clEnsureMethod(L_0, keyQUALIFIERS, clNIL, keyLAMBDA_LIST, CONS_2,
                   keySPECIALIZERS, L_6, keyFUNCTION, L_8,
                   keyDECLARATIONS, clNIL, keyDOCUMENTATION, clNIL,
                   clEOA); }
  clSetSymbolFunctionValue(clSXHASH,
                           clMakeClosure(0, clSxhash, clNULL_HOOK));
  (void) clSXHASH;
  clUnwind(4); }
