/* Generated by Eclipse Common Lisp 1.1-HOSTED on cad0.
   Wednesday the eleventh of March, 1998, 9:45:52 am CST. */
#include <eclipse.h>

clObject cl1PLUS_FUNC(clProto), cl1MINUS_FUNC(clProto),
  clAddInteger(clProto), clAssoc1(clProto), clAtom(clProto),
  clCadddr(clProto), clCaddr(clProto), clCadr(clProto), clCar(clProto),
  clCddddr(clProto), clCddr(clProto), clCdr(clProto),
  clCharpSimpleBaseString __P((clCharp)), clCheckKeys(clProto),
  clConc(clProto), clCons(clProto), clConsp(clProto), clEndp(clProto),
  clEq(clProto), clExtraArgs(clProto), clFuncall(clProto),
  clGeInteger(clProto), clKeyArg(clProto), clLast(clProto),
  clLast1(clProto), clLength(clProto), clList(clProto),
  clMakeKeyword(clProto), clMax(clProto), clMember1(clProto),
  clMissingArgs(clProto), clNot(clProto), clNthcdr(clProto),
  clNull(clProto), clPlusp(clProto), clRplacd(clProto),
  clSatisfiesTheTest(clProto);

extern clObject clADD, clADJOIN, clAPPEND, clASSOC, clASSOC1,
  clBUTLAST, clCAAAAR, clCAAADR, clCAAAR, clCAADAR, clCAADDR, clCAADR,
  clCAAR, clCADAAR, clCADADR, clCADAR, clCADDAR, clCADDDR, clCADDR,
  clCADR, clCDAAAR, clCDAADR, clCDAAR, clCDADAR, clCDADDR, clCDADR,
  clCDAR, clCDDAAR, clCDDADR, clCDDAR, clCDDDAR, clCDDDDR, clCDDDR,
  clCDDR, clCONC, clCOPY_LIST, clEIGHTH, clFIFTH, clFIRST, clFOURTH,
  clGE, clGT, clIDENTITY, clLAST, clLAST1, clLDIFF, clLIST, clLISTstar,
  clLIST_LENGTH, clMAKE_LIST, clMEMBER, clMEMBER1, clNBUTLAST, clNCONC,
  clNINTH, clNRECONC, clNTH, clNTHCAR, clNTHCDR, clREST, clREVAPPEND,
  clSECOND, clSEVENTH, clSIXTH, clSUBSEQ, clSUBT, clTENTH, clTHIRD;

static clObject CONS_0, CONS_1, CONS_2, CONS_3, I_0, I_1, I_2, I_3,
  I_4, I_5, keyINITIAL_ELEMENT, keyKEY, keyTEST, keyTEST_NOT,
  STR_INITIAL_ELEMENT__0, STR_KEY__3, STR_TEST_NOT__2, STR_TEST__1;

clObject clCaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(list, clEOA), clEOA)); }

clObject clCadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(list, clEOA), clEOA)); }

clObject clCdar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(list, clEOA), clEOA)); }

clObject clCddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(list, clEOA), clEOA)); }

clObject clCaaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCar(list, clEOA), clEOA), clEOA)); }

clObject clCaadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCdr(list, clEOA), clEOA), clEOA)); }

clObject clCadar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCar(list, clEOA), clEOA), clEOA)); }

clObject clCaddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCdr(list, clEOA), clEOA), clEOA)); }

clObject clCdaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCar(list, clEOA), clEOA), clEOA)); }

clObject clCdadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCdr(list, clEOA), clEOA), clEOA)); }

clObject clCddar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCar(list, clEOA), clEOA), clEOA)); }

clObject clCdddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCdr(list, clEOA), clEOA), clEOA)); }

clObject clCaaaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCar(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCaaadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCar(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCaadar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCdr(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCaaddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCar(clCdr(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCadaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCar(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCadadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCar(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCaddar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCdr(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCadddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCdr(clCdr(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCdaaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCar(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCdaadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCar(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCdadar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCdr(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCdaddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCar(clCdr(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCddaar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCar(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCddadr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCar(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCdddar clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCdr(clCar(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clCddddr clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(clCdr(clCdr(clCdr(list, clEOA), clEOA), clEOA),
               clEOA)); }

clObject clListLength clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject n, fast, slow;
    clSetq(n, I_0);
    clSetq(fast, list);
    clSetq(slow, list);
    clLabel(l_ITERATE580);
    if (clTrue(clNIL)) return(clValues1(clNIL));
    if (clTrue(clEndp(fast, clEOA))) return(clValues1(n));
    if (clTrue(clEndp(clCdr(fast, clEOA), clEOA)))
      return(clFuncallFunction(clSymbolFunctionValue(clADD),
                               n,
                               I_1,
                               clEOA));
    if (clTrue((_clEq(fast, slow) ?
                clFuncallFunction(clSymbolFunctionValue(clGT),
                                  n,
                                  I_0,
                                  clEOA) :
                clNIL)))
      return(clValues1(clNIL));
    { clObject L_value581, L_value582, L_value583;
      clSetq(L_value581,
             clFuncallFunction(clSymbolFunctionValue(clADD),
                               n,
                               I_2,
                               clEOA));
      clSetq(L_value582, clCddr(fast, clEOA));
      clSetq(L_value583, clCdr(slow, clEOA));
      clSetq(n, L_value581);
      clSetq(fast, L_value582);
      clSetq(slow, L_value583); }
    goto l_ITERATE580; } }

clObject clNth clVdecl(_ap)
{ clObject n, list;
  { clBeginParse(_ap);
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clNthcdr(n, list, clEOA), clEOA)); }

clObject clFirst clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(list, clEOA)); }

clObject clSecond clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCadr(list, clEOA)); }

clObject clThird clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCaddr(list, clEOA)); }

clObject clFourth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCadddr(list, clEOA)); }

clObject clFifth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCddddr(list, clEOA), clEOA)); }

clObject clSixth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCadr(clCddddr(list, clEOA), clEOA)); }

clObject clSeventh clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCaddr(clCddddr(list, clEOA), clEOA)); }

clObject clEighth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCadddr(clCddddr(list, clEOA), clEOA)); }

clObject clNinth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCar(clCddddr(clCddddr(list, clEOA), clEOA), clEOA)); }

clObject clTenth clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCadr(clCddddr(clCddddr(list, clEOA), clEOA), clEOA)); }

clObject clRest clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clCdr(list, clEOA)); }

clObject clNthcdr clVdecl(_ap)
{ clObject n, list;
  { clBeginParse(_ap);
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject x;
    clSetq(x, I_0);
    clLabel(l_ITERATE590);
    if (clTrue(clGeInteger(x, n, clEOA))) return(clValues1(list));
    if (clTrue(clEndp(list, clEOA)))
      return(clValues1(clNIL));
    else
      { clObject L_0;
        clSetq(L_0, list);
        clSetq(list, clCdr(L_0, clEOA)); }
    { clObject L_0;
      clSetq(L_0, x);
      clSetq(x, clAddInteger(L_0, I_1, clEOA)); }
    goto l_ITERATE590; } }

clObject clNthcar clVdecl(_ap)
{ clObject n, list;
  { clBeginParse(_ap);
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject x;
    clSetq(x, I_0);
    clLabel(l_ITERATE598);
    if (clTrue(clGeInteger(x, n, clEOA))) return(clValues1(list));
    if (clTrue(clEndp(list, clEOA)))
      return(clValues1(clNIL));
    else
      { clObject L_0;
        clSetq(L_0, list);
        clSetq(list, clCar(L_0, clEOA)); }
    { clObject L_0;
      clSetq(L_0, x);
      clSetq(x, clAddInteger(L_0, I_1, clEOA)); }
    goto l_ITERATE598; } }

clObject clLast1 clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(clConsp(list, clEOA)))
    { clObject l, next;
      clSetq(l, list);
      clSetq(next, clCdr(list, clEOA));
      clLabel(l_ITERATE600);
      if (clTrue(clAtom(next, clEOA))) return(clValues1(l));
      { clObject L_value601, L_value602;
        clSetq(L_value601, next);
        clSetq(L_value602, clCdr(next, clEOA));
        clSetq(l, L_value601);
        clSetq(next, L_value602); }
      goto l_ITERATE600; }
  else return(clValues1(list)); }

clObject clLast clVdecl(_ap)
{ clObject list, n;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : clNIL));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  if (clTrue(n))
    { clObject l, r, i;
      clSetq(l, list);
      clSetq(r, list);
      clSetq(i, I_0);
      clLabel(l_ITERATE603);
      if (clTrue(clAtom(l, clEOA))) return(clValues1(r));
      { clObject L_test__R1;
        { clObject L_1;
          clSetq(L_1, n);
          clSetq(L_test__R1,
                 clFuncallFunction(clSymbolFunctionValue(clGE),
                                   i,
                                   L_1,
                                   clEOA)); }
        if (clTrue(L_test__R1))
          { clObject L_top604;
            clSetq(L_top604, clCar(r, clEOA));
            { clObject L_0;
              clSetq(L_0, r);
              clSetq(r, clCdr(L_0, clEOA)); }
            (void) L_top604; } }
      { clObject L_value605, L_value606;
        clSetq(L_value605, clCdr(l, clEOA));
        clSetq(L_value606, cl1PLUS_FUNC(i, clEOA));
        clSetq(l, L_value605);
        clSetq(i, L_value606); }
      goto l_ITERATE603; }
  else return(clLast1(list, clEOA)); }

clObject clList clVdecl(_ap)
{ clObject args;
  { clBeginParse(_ap); clSetq(args, clVargs(_ap)); clEndParse(_ap); }
  return(clValues1(args)); }

clObject clListSTAR clVdecl(_ap)
{ clObject arg, others;
  { clBeginParse(_ap);
    clSetq(arg,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(others, clVargs(_ap));
    clEndParse(_ap); }
  if (clTrue(clAtom(others, clEOA)))
    return(clValues1(arg));
  else if (clTrue(clAtom(clCdr(others, clEOA), clEOA)))
    return(clCons(arg, clCar(others, clEOA), clEOA));
  else
    { { clObject x;
        clSetq(x, others);
        clLabel(l_ITERATE607);
        if (clTrue(clNull(clCddr(x, clEOA), clEOA)))
          { clRplacd(x, clCadr(x, clEOA), clEOA); clLocalReturn(NIL); }
        { clObject L_value608;
          clSetq(L_value608, clCdr(x, clEOA));
          clSetq(x, L_value608); }
        goto l_ITERATE607; }
      clBlockEnd(NIL);
      return(clCons(arg, others, clEOA)); } }

clObject clMakeList clVdecl(_ap)
{ clObject L_ap, size, L_keys, initial_element, list;
  { clBeginParse(_ap);
    clSetq(size,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(L_keys, clVargs(_ap));
    if (clTrue(clSetq(L_ap,
                      clKeyArg(keyINITIAL_ELEMENT, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(initial_element, clCar(L_0, clEOA)); }
    else clSetq(initial_element, clNIL);
    clSetq(list, clNIL);
    clCheckKeys(L_keys, CONS_0, clEOA);
    clEndParse(_ap); }
  { clObject n;
    clSetq(n, I_0);
    clLabel(l_ITERATE610);
    if (clTrue(clGeInteger(n, size, clEOA))) return(clValues1(list));
    { clObject L_1, L_0;
      clSetq(L_0, initial_element);
      clSetq(L_1, list);
      clSetq(list, clCons(L_0, L_1, clEOA)); }
    { clObject L_0;
      clSetq(L_0, n);
      clSetq(n, clAddInteger(L_0, I_1, clEOA)); }
    goto l_ITERATE610; } }

clDeclareEnv(clConc_Pf);
static clObject clConc_Pf clVdecl(_ap)
{ clUseEnv(clConc_Pf);
  { clObject moreQUESTION;
    { clBeginParse(_ap);
      clSetq(moreQUESTION,
             (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
      if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
      clEndParse(_ap); }
    if (clTrue((clTrue(clEnv(0, *last_processf)) ?
                clNot(moreQUESTION, clEOA) : clNIL)))
      return(clValues1(clEnv(0, *last_processf)));
    else return(clValues1(clEnv(1, *processf))); } }

clObject clConc clVdecl(_ap)
{ clObject list, *processf = clMakeBinding(),
  *last_processf = clMakeBinding(), CL_new, newlist, last;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(*processf,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(*last_processf, (_clVp(_ap) ? clVpop(_ap) : clNIL));
    clSetq(CL_new, clNIL);
    clSetq(newlist, clNIL);
    clSetq(last, clNIL);
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject _Pf_;
    clSetq(_Pf_,
           clMakeClosure(2,
                         clConc_Pf,
                         &clEnvHook(clConc_Pf),
                         &*last_processf,
                         &*processf));
    if (clTrue(list))
      { { clObject L_1, L_0;
          clSetq(L_0,
                 clFuncallFunction(_Pf_, clCdr(list, clEOA), clEOA));
          { clObject L_top613;
            clSetq(L_top613, clCar(list, clEOA));
            { clObject L_0__R1;
              clSetq(L_0__R1, list);
              clSetq(list, clCdr(L_0__R1, clEOA)); }
            clSetq(L_1, L_top613); }
          clSetq(newlist, clFuncall(L_0, L_1, clEOA)); }
        { clObject L_0;
          clSetq(L_0, newlist);
          clSetq(last, clLast(L_0, clEOA)); }
        { clObject sub;
          clSetq(sub, list);
          clLabel(l_ITERATE614);
          if (clTrue(clAtom(sub, clEOA)))
            { if (clTrue(sub))
                { clObject L_g615;
                  { clObject L_0;
                    clSetq(L_0, last);
                    clSetq(L_g615, clLast(L_0, clEOA)); }
                  clRplacd(L_g615, sub, clEOA);
                  (void) sub; }
              return(clValues1(newlist)); }
          { clObject L_0;
            clSetq(L_0,
                   clFuncallFunction(_Pf_, clCdr(sub, clEOA), clEOA));
            clSetq(CL_new, clFuncall(L_0, clCar(sub, clEOA), clEOA)); }
          { clObject L_g618, L_g619;
            { clObject L_0;
              clSetq(L_0, last);
              clSetq(L_g618, clLast(L_0, clEOA)); }
            clSetq(L_g619, CL_new);
            clRplacd(L_g618, L_g619, clEOA);
            (void) L_g619; }
          { clObject L_value620;
            clSetq(L_value620, clCdr(sub, clEOA));
            clSetq(sub, L_value620); }
          goto l_ITERATE614; } }
    else return(clValues1(clNIL)); } }

clObject clAppend clVdecl(_ap)
{ clObject lists;
  { clBeginParse(_ap); clSetq(lists, clVargs(_ap)); clEndParse(_ap); }
  clLabel(l_LOOP1);
  { clObject L_test;
    { clObject L_g624;
      clSetq(L_g624, clCar(lists, clEOA));
      clSetq(L_test,
             (clTrue(L_g624) ? L_g624 : clNull(lists, clEOA))); }
    if (clTrue(L_test)) clLocalReturn(NIL); }
  { clObject L_0;
    clSetq(L_0, lists);
    clSetq(lists, clCdr(L_0, clEOA)); }
  goto l_LOOP1;
  clBlockEnd(NIL);
  { clObject L_1, L_0;
    clSetq(L_0, lists);
    clSetq(L_1, clSymbolFunctionValue(clCOPY_LIST));
    return(clConc(L_0, L_1, clSymbolFunctionValue(clIDENTITY),
                  clEOA)); } }

clObject clNconc clVdecl(_ap)
{ clObject lists;
  { clBeginParse(_ap); clSetq(lists, clVargs(_ap)); clEndParse(_ap); }
  clLabel(l_LOOP2);
  { clObject L_test;
    { clObject L_g629;
      clSetq(L_g629, clCar(lists, clEOA));
      clSetq(L_test,
             (clTrue(L_g629) ? L_g629 : clNull(lists, clEOA))); }
    if (clTrue(L_test)) clLocalReturn(NIL); }
  { clObject L_0;
    clSetq(L_0, lists);
    clSetq(lists, clCdr(L_0, clEOA)); }
  goto l_LOOP2;
  clBlockEnd(NIL);
  { clObject L_0;
    clSetq(L_0, lists);
    return(clConc(L_0, clSymbolFunctionValue(clIDENTITY), clEOA)); } }

clObject clCopyList clVdecl(_ap)
{ clObject list;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  return(clConc(list, clSymbolFunctionValue(clLIST), clEOA)); }

clObject clRevappend clVdecl(_ap)
{ clObject x, y;
  { clBeginParse(_ap);
    clSetq(x, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(y, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_sublist631, item;
    clSetq(L_sublist631, x);
    clSetq(item, clCar(L_sublist631, clEOA));
    clLabel(l_ITERATE632);
    if (clTrue(clEndp(L_sublist631, clEOA))) return(clValues1(y));
    { clObject L_1;
      clSetq(L_1, y);
      clSetq(y, clCons(item, L_1, clEOA)); }
    { clObject L_0;
      clSetq(L_0, L_sublist631);
      clSetq(L_sublist631, clCdr(L_0, clEOA)); }
    { clObject L_0;
      clSetq(L_0, L_sublist631);
      clSetq(item, clCar(L_0, clEOA)); }
    goto l_ITERATE632; } }

clObject clNreconc clVdecl(_ap)
{ clObject x, y;
  { clBeginParse(_ap);
    clSetq(x, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(y, (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject cons;
    clSetq(cons, clNIL);
    clLabel(l_ITERATE633);
    if (clTrue(clNot(clConsp(x, clEOA), clEOA))) return(clValues1(y));
    clSetq(cons, x);
    { clObject L_0; clSetq(L_0, x); clSetq(x, clCdr(L_0, clEOA)); }
    { clObject L_g636;
      clSetq(L_g636, cons);
      clRplacd(L_g636, y, clEOA);
      (void) y; }
    clSetq(y, cons);
    goto l_ITERATE633; } }

clObject clButlast clVdecl(_ap)
{ clObject list, n;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : I_1));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_2;
    { clObject L_1__R1;
      { clObject L_1__R2, L_0__R2;
        clSetq(L_0__R2, clLength(list, clEOA));
        clSetq(L_1__R2, n);
        clSetq(L_1__R1,
               clFuncallFunction(clSymbolFunctionValue(clSUBT),
                                 L_0__R2,
                                 L_1__R2,
                                 clEOA)); }
      clSetq(L_2, clMax(I_0, L_1__R1, clEOA)); }
    return(clFuncallFunction(clSymbolFunctionValue(clSUBSEQ),
                             list,
                             I_0,
                             L_2,
                             clEOA)); } }

clObject clNbutlast clVdecl(_ap)
{ clObject list, n;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(n, (_clVp(_ap) ? clVpop(_ap) : I_1));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject size;
    { clObject L_1, L_0;
      clSetq(L_0, clLength(list, clEOA));
      clSetq(L_1, n);
      clSetq(size,
             clFuncallFunction(clSymbolFunctionValue(clSUBT),
                               L_0,
                               L_1,
                               clEOA)); }
    if (clTrue(clPlusp(size, clEOA)))
      { { clObject L_0;
          { clObject L_0__R1;
            clSetq(L_0__R1, cl1MINUS_FUNC(size, clEOA));
            clSetq(L_0, clNthcdr(L_0__R1, list, clEOA)); }
          clRplacd(L_0, clNIL, clEOA); }
        return(clValues1(list)); }
    else return(clValues1(clNIL)); } }

clObject clLdiff clVdecl(_ap)
{ clObject list, sublist;
  { clBeginParse(_ap);
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(sublist,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject list__R1, result, splice;
    clSetq(list__R1, list);
    clSetq(result, clList(clNIL, clEOA));
    clSetq(splice, result);
    clLabel(l_ITERATE639);
    { clObject L_test;
      { clObject L_g640;
        clSetq(L_g640, clNull(list__R1, clEOA));
        clSetq(L_test,
               (clTrue(L_g640) ? L_g640 :
                clEq(list__R1, sublist, clEOA))); }
      if (clTrue(L_test)) return(clCdr(result, clEOA)); }
    { clObject L_0;
      clSetq(L_0,
             clRplacd(splice,
                      clList(clCar(list__R1, clEOA), clEOA),
                      clEOA));
      clSetq(splice, clCdr(L_0, clEOA)); }
    { clObject L_0;
      clSetq(L_0, list__R1);
      clSetq(list__R1, clCdr(L_0, clEOA)); }
    goto l_ITERATE639; } }

clObject clMember1 clVdecl(_ap)
{ clObject item, list, test, test_not, key;
  { clBeginParse(_ap);
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(test,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(test_not,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    clSetq(key,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_5, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject list__R1;
    clSetq(list__R1, list);
    clLabel(l_ITERATE641);
    if (clTrue(clEndp(list__R1, clEOA))) return(clValues1(clNIL));
    { clObject L_test;
      { clObject L_1;
        clSetq(L_1, clCar(list__R1, clEOA));
        clSetq(L_test,
               clSatisfiesTheTest(item,
                                  L_1,
                                  test,
                                  test_not,
                                  key,
                                  clEOA)); }
      if (clTrue(L_test)) return(clValues1(list__R1)); }
    { clObject L_value642;
      clSetq(L_value642, clCdr(list__R1, clEOA));
      clSetq(list__R1, L_value642); }
    goto l_ITERATE641; } }

clObject clMember clVdecl(_ap)
{ clObject L_ap, item, list, L_keys, test, test_not, key;
  { clBeginParse(_ap);
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(L_keys, clVargs(_ap));
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test, clCar(L_0, clEOA)); }
    else clSetq(test, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST_NOT, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test_not, clCar(L_0, clEOA)); }
    else clSetq(test_not, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyKEY, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(key, clCar(L_0, clEOA)); }
    else clSetq(key, clNIL);
    clCheckKeys(L_keys, CONS_1, clEOA);
    clEndParse(_ap); }
  { clObject L_4, L_3, L_2;
    clSetq(L_2, test);
    clSetq(L_3, test_not);
    clSetq(L_4, key);
    return(clMember1(item, list, L_2, L_3, L_4, clEOA)); } }

clObject clAdjoin clVdecl(_ap)
{ clObject L_ap, item, list, L_keys, test, test_not, key;
  { clBeginParse(_ap);
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(L_keys, clVargs(_ap));
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test, clCar(L_0, clEOA)); }
    else clSetq(test, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST_NOT, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test_not, clCar(L_0, clEOA)); }
    else clSetq(test_not, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyKEY, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(key, clCar(L_0, clEOA)); }
    else clSetq(key, clSymbolFunctionValue(clIDENTITY));
    clCheckKeys(L_keys, CONS_1, clEOA);
    clEndParse(_ap); }
  { clObject L_test;
    { clObject L_4, L_3, L_2, L_0;
      { clObject L_0__R1;
        clSetq(L_0__R1, key);
        clSetq(L_0, clFuncall(L_0__R1, item, clEOA)); }
      clSetq(L_2, test);
      clSetq(L_3, test_not);
      clSetq(L_4, key);
      clSetq(L_test, clMember1(L_0, list, L_2, L_3, L_4, clEOA)); }
    if (clTrue(L_test))
      return(clValues1(list));
    else return(clCons(item, list, clEOA)); } }

clObject clAssoc1 clVdecl(_ap)
{ clObject CL_item, CL_a_list, CL_test, CL_test_not, CL_key;
  { clBeginParse(_ap);
    clSetq(CL_item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(CL_a_list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(CL_test,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_3, clEOA)));
    clSetq(CL_test_not,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_4, clEOA)));
    clSetq(CL_key,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_5, clEOA)));
    if (_clVp(_ap)) clExtraArgs(clVargs(_ap), clEOA);
    clEndParse(_ap); }
  { clObject L_sublist643, CL_pair;
    clSetq(L_sublist643, CL_a_list);
    clSetq(CL_pair, clCar(L_sublist643, clEOA));
    clLabel(l_ITERATE644);
    if (clTrue(clEndp(L_sublist643, clEOA))) return(clValues1(clNIL));
    { clObject L_test;
      { clObject L_1;
        clSetq(L_1, clCar(CL_pair, clEOA));
        clSetq(L_test,
               clSatisfiesTheTest(CL_item,
                                  L_1,
                                  CL_test,
                                  CL_test_not,
                                  CL_key,
                                  clEOA)); }
      if (clTrue(L_test)) return(clValues1(CL_pair)); }
    { clObject L_0;
      clSetq(L_0, L_sublist643);
      clSetq(L_sublist643, clCdr(L_0, clEOA)); }
    { clObject L_0;
      clSetq(L_0, L_sublist643);
      clSetq(CL_pair, clCar(L_0, clEOA)); }
    goto l_ITERATE644; } }

clObject clAssoc clVdecl(_ap)
{ clObject L_ap, item, a_list, L_keys, test, test_not, key;
  { clBeginParse(_ap);
    clSetq(item,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_1, clEOA)));
    clSetq(a_list,
           (_clVp(_ap) ? clVpop(_ap) : clMissingArgs(I_2, clEOA)));
    clSetq(L_keys, clVargs(_ap));
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test, clCar(L_0, clEOA)); }
    else clSetq(test, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyTEST_NOT, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(test_not, clCar(L_0, clEOA)); }
    else clSetq(test_not, clNIL);
    if (clTrue(clSetq(L_ap, clKeyArg(keyKEY, L_keys, clEOA))))
      { clObject L_0;
        clSetq(L_0, L_ap);
        clSetq(key, clCar(L_0, clEOA)); }
    else clSetq(key, clNIL);
    clCheckKeys(L_keys, CONS_1, clEOA);
    clEndParse(_ap); }
  { clObject L_4, L_3, L_2;
    clSetq(L_2, test);
    clSetq(L_3, test_not);
    clSetq(L_4, key);
    return(clAssoc1(item, a_list, L_2, L_3, L_4, clEOA)); } }

void clInitList __P((void)) 
{ clDbind(clstarPACKAGEstar);
  clDbind(clstarREADTABLEstar);
  clDbind(clstarLOAD_TRUENAMEstar);
  clDbind(clstarLOAD_PATHNAMEstar);
  clSetq(I_1, clIntFixnum(1));
  clSetq(I_0, clIntFixnum(0));
  clSetq(I_2, clIntFixnum(2));
  clSetq(STR_INITIAL_ELEMENT__0,
         clCharpSimpleBaseString("INITIAL-ELEMENT"));
  clSetq(keyINITIAL_ELEMENT,
         clMakeKeyword(STR_INITIAL_ELEMENT__0, clEOA));
  clSetq(CONS_0, clCons(keyINITIAL_ELEMENT, clNIL, clEOA));
  clSetq(I_3, clIntFixnum(3));
  clSetq(I_4, clIntFixnum(4));
  clSetq(I_5, clIntFixnum(5));
  clSetq(STR_TEST__1,
         clCharpSimpleBaseString("TEST"));
  clSetq(keyTEST, clMakeKeyword(STR_TEST__1, clEOA));
  clSetq(STR_TEST_NOT__2,
         clCharpSimpleBaseString("TEST-NOT"));
  clSetq(keyTEST_NOT, clMakeKeyword(STR_TEST_NOT__2, clEOA));
  clSetq(STR_KEY__3,
         clCharpSimpleBaseString("KEY"));
  clSetq(keyKEY, clMakeKeyword(STR_KEY__3, clEOA));
  clSetq(CONS_3, clCons(keyTEST, clNIL, clEOA));
  clSetq(CONS_2, clCons(keyTEST_NOT, CONS_3, clEOA));
  clSetq(CONS_1, clCons(keyKEY, CONS_2, clEOA));

  clSetSymbolFunctionValue(clCAAR,
                           clMakeClosure(0, clCaar, clNULL_HOOK));
  (void) clCAAR;
  clSetSymbolFunctionValue(clCADR,
                           clMakeClosure(0, clCadr, clNULL_HOOK));
  (void) clCADR;
  clSetSymbolFunctionValue(clCDAR,
                           clMakeClosure(0, clCdar, clNULL_HOOK));
  (void) clCDAR;
  clSetSymbolFunctionValue(clCDDR,
                           clMakeClosure(0, clCddr, clNULL_HOOK));
  (void) clCDDR;
  clSetSymbolFunctionValue(clCAAAR,
                           clMakeClosure(0, clCaaar, clNULL_HOOK));
  (void) clCAAAR;
  clSetSymbolFunctionValue(clCAADR,
                           clMakeClosure(0, clCaadr, clNULL_HOOK));
  (void) clCAADR;
  clSetSymbolFunctionValue(clCADAR,
                           clMakeClosure(0, clCadar, clNULL_HOOK));
  (void) clCADAR;
  clSetSymbolFunctionValue(clCADDR,
                           clMakeClosure(0, clCaddr, clNULL_HOOK));
  (void) clCADDR;
  clSetSymbolFunctionValue(clCDAAR,
                           clMakeClosure(0, clCdaar, clNULL_HOOK));
  (void) clCDAAR;
  clSetSymbolFunctionValue(clCDADR,
                           clMakeClosure(0, clCdadr, clNULL_HOOK));
  (void) clCDADR;
  clSetSymbolFunctionValue(clCDDAR,
                           clMakeClosure(0, clCddar, clNULL_HOOK));
  (void) clCDDAR;
  clSetSymbolFunctionValue(clCDDDR,
                           clMakeClosure(0, clCdddr, clNULL_HOOK));
  (void) clCDDDR;
  clSetSymbolFunctionValue(clCAAAAR,
                           clMakeClosure(0, clCaaaar, clNULL_HOOK));
  (void) clCAAAAR;
  clSetSymbolFunctionValue(clCAAADR,
                           clMakeClosure(0, clCaaadr, clNULL_HOOK));
  (void) clCAAADR;
  clSetSymbolFunctionValue(clCAADAR,
                           clMakeClosure(0, clCaadar, clNULL_HOOK));
  (void) clCAADAR;
  clSetSymbolFunctionValue(clCAADDR,
                           clMakeClosure(0, clCaaddr, clNULL_HOOK));
  (void) clCAADDR;
  clSetSymbolFunctionValue(clCADAAR,
                           clMakeClosure(0, clCadaar, clNULL_HOOK));
  (void) clCADAAR;
  clSetSymbolFunctionValue(clCADADR,
                           clMakeClosure(0, clCadadr, clNULL_HOOK));
  (void) clCADADR;
  clSetSymbolFunctionValue(clCADDAR,
                           clMakeClosure(0, clCaddar, clNULL_HOOK));
  (void) clCADDAR;
  clSetSymbolFunctionValue(clCADDDR,
                           clMakeClosure(0, clCadddr, clNULL_HOOK));
  (void) clCADDDR;
  clSetSymbolFunctionValue(clCDAAAR,
                           clMakeClosure(0, clCdaaar, clNULL_HOOK));
  (void) clCDAAAR;
  clSetSymbolFunctionValue(clCDAADR,
                           clMakeClosure(0, clCdaadr, clNULL_HOOK));
  (void) clCDAADR;
  clSetSymbolFunctionValue(clCDADAR,
                           clMakeClosure(0, clCdadar, clNULL_HOOK));
  (void) clCDADAR;
  clSetSymbolFunctionValue(clCDADDR,
                           clMakeClosure(0, clCdaddr, clNULL_HOOK));
  (void) clCDADDR;
  clSetSymbolFunctionValue(clCDDAAR,
                           clMakeClosure(0, clCddaar, clNULL_HOOK));
  (void) clCDDAAR;
  clSetSymbolFunctionValue(clCDDADR,
                           clMakeClosure(0, clCddadr, clNULL_HOOK));
  (void) clCDDADR;
  clSetSymbolFunctionValue(clCDDDAR,
                           clMakeClosure(0, clCdddar, clNULL_HOOK));
  (void) clCDDDAR;
  clSetSymbolFunctionValue(clCDDDDR,
                           clMakeClosure(0, clCddddr, clNULL_HOOK));
  (void) clCDDDDR;
  clSetSymbolFunctionValue(clLIST_LENGTH,
                           clMakeClosure(0,
                                         clListLength,
                                         clNULL_HOOK));
  (void) clLIST_LENGTH;
  clSetSymbolFunctionValue(clNTH,
                           clMakeClosure(0, clNth, clNULL_HOOK));
  (void) clNTH;
  clSetSymbolFunctionValue(clFIRST,
                           clMakeClosure(0, clFirst, clNULL_HOOK));
  (void) clFIRST;
  clSetSymbolFunctionValue(clSECOND,
                           clMakeClosure(0, clSecond, clNULL_HOOK));
  (void) clSECOND;
  clSetSymbolFunctionValue(clTHIRD,
                           clMakeClosure(0, clThird, clNULL_HOOK));
  (void) clTHIRD;
  clSetSymbolFunctionValue(clFOURTH,
                           clMakeClosure(0, clFourth, clNULL_HOOK));
  (void) clFOURTH;
  clSetSymbolFunctionValue(clFIFTH,
                           clMakeClosure(0, clFifth, clNULL_HOOK));
  (void) clFIFTH;
  clSetSymbolFunctionValue(clSIXTH,
                           clMakeClosure(0, clSixth, clNULL_HOOK));
  (void) clSIXTH;
  clSetSymbolFunctionValue(clSEVENTH,
                           clMakeClosure(0, clSeventh, clNULL_HOOK));
  (void) clSEVENTH;
  clSetSymbolFunctionValue(clEIGHTH,
                           clMakeClosure(0, clEighth, clNULL_HOOK));
  (void) clEIGHTH;
  clSetSymbolFunctionValue(clNINTH,
                           clMakeClosure(0, clNinth, clNULL_HOOK));
  (void) clNINTH;
  clSetSymbolFunctionValue(clTENTH,
                           clMakeClosure(0, clTenth, clNULL_HOOK));
  (void) clTENTH;
  clSetSymbolFunctionValue(clREST,
                           clMakeClosure(0, clRest, clNULL_HOOK));
  (void) clREST;
  clSetSymbolFunctionValue(clNTHCDR,
                           clMakeClosure(0, clNthcdr, clNULL_HOOK));
  (void) clNTHCDR;
  clSetSymbolFunctionValue(clNTHCAR,
                           clMakeClosure(0, clNthcar, clNULL_HOOK));
  (void) clNTHCAR;
  clSetSymbolFunctionValue(clLAST1,
                           clMakeClosure(0, clLast1, clNULL_HOOK));
  (void) clLAST1;
  clSetSymbolFunctionValue(clLAST,
                           clMakeClosure(0, clLast, clNULL_HOOK));
  (void) clLAST;
  clSetSymbolFunctionValue(clLIST,
                           clMakeClosure(0, clList, clNULL_HOOK));
  (void) clLIST;
  clSetSymbolFunctionValue(clLISTstar,
                           clMakeClosure(0, clListSTAR, clNULL_HOOK));
  (void) clLISTstar;
  clSetSymbolFunctionValue(clMAKE_LIST,
                           clMakeClosure(0, clMakeList, clNULL_HOOK));
  (void) clMAKE_LIST;
  clSetSymbolFunctionValue(clCONC,
                           clMakeClosure(0, clConc, clNULL_HOOK));
  (void) clCONC;
  clSetSymbolFunctionValue(clAPPEND,
                           clMakeClosure(0, clAppend, clNULL_HOOK));
  (void) clAPPEND;
  clSetSymbolFunctionValue(clNCONC,
                           clMakeClosure(0, clNconc, clNULL_HOOK));
  (void) clNCONC;
  clSetSymbolFunctionValue(clCOPY_LIST,
                           clMakeClosure(0, clCopyList, clNULL_HOOK));
  (void) clCOPY_LIST;
  clSetSymbolFunctionValue(clREVAPPEND,
                           clMakeClosure(0, clRevappend, clNULL_HOOK));
  (void) clREVAPPEND;
  clSetSymbolFunctionValue(clNRECONC,
                           clMakeClosure(0, clNreconc, clNULL_HOOK));
  (void) clNRECONC;
  clSetSymbolFunctionValue(clBUTLAST,
                           clMakeClosure(0, clButlast, clNULL_HOOK));
  (void) clBUTLAST;
  clSetSymbolFunctionValue(clNBUTLAST,
                           clMakeClosure(0, clNbutlast, clNULL_HOOK));
  (void) clNBUTLAST;
  clSetSymbolFunctionValue(clLDIFF,
                           clMakeClosure(0, clLdiff, clNULL_HOOK));
  (void) clLDIFF;
  clSetSymbolFunctionValue(clMEMBER1,
                           clMakeClosure(0, clMember1, clNULL_HOOK));
  (void) clMEMBER1;
  clSetSymbolFunctionValue(clMEMBER,
                           clMakeClosure(0, clMember, clNULL_HOOK));
  (void) clMEMBER;
  clSetSymbolFunctionValue(clADJOIN,
                           clMakeClosure(0, clAdjoin, clNULL_HOOK));
  (void) clADJOIN;
  clSetSymbolFunctionValue(clASSOC1,
                           clMakeClosure(0, clAssoc1, clNULL_HOOK));
  (void) clASSOC1;
  clSetSymbolFunctionValue(clASSOC,
                           clMakeClosure(0, clAssoc, clNULL_HOOK));
  (void) clASSOC;
  clUnwind(4); }
