(in-package :user)

(defpackage :HOST
  (:use :common-lisp)
  #+nn(:intern get-setf-expansion define-setf-expander)
  (:import-from
   #+excl :excl
   #+cmu :ext
   FIXNUMP)
  (:shadow
   ;; #+excl ROW-MAJOR-AREF
   STRING))

#| Still need:
*PACKAGE* 
|#

(defpackage :ECLIPSE
  (:use :common-lisp)
  #|#+excl
  (:shadowing-import-from
   :HOST get-setf-expansion define-setf-expander)|#
  (:shadow

   #+lisp-host flet

   TYPEP SUBTYPEP TYPE-OF COERCE
   
   DECLAIM DEFCONSTANT DEFPARAMETER DEFTYPE DEFVAR FDEFINITION FBOUNDP
   FMAKUNBOUND PARSE-MACRO PROCLAIM SPECIAL-OPERATOR-P

   *MACROEXPAND-HOOK* COMPILER-MACRO-FUNCTION DEFINE-COMPILER-MACRO
   DEFINE-SETF-EXPANDER DEFINE-SYMBOL-MACRO DEFMACRO DEFUN
   GET-SETF-EXPANSION MACRO-FUNCTION MACROEXPAND MACROEXPAND-1 

   AND OR ATOM CHARACTERP COMPILED-FUNCTION-P COMPLEXP CONSP
   DOUBLE-FLOAT-P EQL INTEGERP LISTP NOT NULL SIMPLE-VECTOR-P
   SIMPLE-BIT-VECTOR-P SINGLE-FLOAT-P SYMBOLP
   ARRAYP BIT-VECTOR-P EQUAL EQUALP FLOATP FUNCTIONP NUMBERP RATIONALP
   REALP SIMPLE-STRING-P STRINGP VECTORP

   CALL-ARGUMENTS-LIMIT LAMBDA-PARAMETERS-LIMIT MULTIPLE-VALUES-LIMIT
   LAMBDA-LIST-KEYWORDS 

   APPLY BOUNDP COMPLEMENT DEFINE-MODIFY-MACRO DEFSETF FUNCALL FUNCTION
   IDENTITY MAKUNBOUND MAPC MAPCAN MAPCAR MAPCON MAPL MAPLIST PROG
   PROG* PROG2 PSETF ROTATEF SET SETF SHIFTF SYMBOL-FUNCTION SYMBOL-VALUE
   THE VALUES VALUES-LIST 

   CASE COND DESTRUCTURING-BIND DO DO* DOLIST DOTIMES ECASE ETYPECASE
   LOOP LOOP-FINISH MULTIPLE-VALUE-BIND MULTIPLE-VALUE-LIST MULTIPLE-VALUE-SETQ
   NTH-VALUE PROG1 PSETQ RETURN WHEN TYPECASE UNLESS

   = /= < <= > >= + - * / 1+ 1- ABS ACOS ACOSH ASIN ASINH ATAN ATANH
   CEILING CIS COS COSH COMPLEX CONJUGATE DECF DECODE-FLOAT DENOMINATOR
   EVENP EXP EXPT FCEILING FFLOOR FLOAT FLOAT-DIGITS FLOAT-PRECISION
   FLOAT-RADIX FLOAT-SIGN FLOOR FROUND FTRUNCATE GCD IMAGPART INCF 
   INTEGER-DECODE-FLOAT ISQRT LCM LOG MAX MIN MINUSP MOD NUMERATOR
   ODDP PHASE PLUSP RATIONAL RATIONALIZE REALPART REM ROUND
   SCALE-FLOAT SIGNUM SIN SINH SQRT TAN TANH TRUNCATE ZEROP
   UPGRADED-COMPLEX-PART-TYPE
   RANDOM RANDOM-STATE MAKE-RANDOM-STATE RANDOM-STATE-P *RANDOM-STATE*

   PI MOST-NEGATIVE-FIXNUM MOST-NEGATIVE-SHORT-FLOAT
   MOST-NEGATIVE-SINGLE-FLOAT MOST-NEGATIVE-DOUBLE-FLOAT
   MOST-NEGATIVE-LONG-FLOAT MOST-POSITIVE-FIXNUM
   MOST-POSITIVE-SHORT-FLOAT MOST-POSITIVE-SINGLE-FLOAT
   MOST-POSITIVE-DOUBLE-FLOAT MOST-POSITIVE-LONG-FLOAT
   LEAST-NEGATIVE-FIXNUM LEAST-NEGATIVE-SHORT-FLOAT
   LEAST-NEGATIVE-SINGLE-FLOAT LEAST-NEGATIVE-DOUBLE-FLOAT
   LEAST-NEGATIVE-LONG-FLOAT LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT
   LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT
   LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT
   LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT LEAST-POSITIVE-FIXNUM
   LEAST-POSITIVE-SHORT-FLOAT LEAST-POSITIVE-SINGLE-FLOAT
   LEAST-POSITIVE-DOUBLE-FLOAT LEAST-POSITIVE-LONG-FLOAT
   LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT
   LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT
   LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT
   LEAST-POSITIVE-NORMALIZED-LONG-FLOAT SHORT-FLOAT-EPSILON
   SINGLE-FLOAT-EPSILON DOUBLE-FLOAT-EPSILON LONG-FLOAT-EPSILON
   SHORT-FLOAT-NEGATIVE-EPSILON SINGLE-FLOAT-NEGATIVE-EPSILON
   DOUBLE-FLOAT-NEGATIVE-EPSILON LONG-FLOAT-NEGATIVE-EPSILON 

   ASH BOOLE BOOLE-1 BOOLE-2 BOOLE-AND BOOLE-ANDC1 BOOLE-ANDC2
   BOOLE-C1 BOOLE-C2 BOOLE-CLR BOOLE-EQV BOOLE-IOR BOOLE-NAND
   BOOLE-NOR BOOLE-ORC1 BOOLE-ORC2 BOOLE-SET BOOLE-XOR BYTE
   BYTE-POSITION BYTE-SIZE DEPOSIT-FIELD DPB INTEGER-LENGTH LDB
   LDB-TEST LOGAND LOGANDC1 LOGANDC2 LOGBITP LOGCOUNT LOGEQV LOGIOR 
   LOGNAND LOGNOR LOGNOT LOGORC1 LOGORC2 LOGTEST LOGXOR MASK-FIELD

   ALPHA-CHAR-P ALPHANUMERICP BOTH-CASE-P CHAR-CODE CHAR-CODE-LIMIT
   CHAR-DOWNCASE CHAR-EQUAL CHAR-GREATERP CHAR-INT CHAR-LESSP
   CHAR-NAME CHAR-NOT-EQUAL CHAR-NOT-GREATERP CHAR-NOT-LESSP
   CHAR-UPCASE CHAR/= CHAR< CHAR<= CHAR= CHAR> CHAR>= CHARACTER
   CODE-CHAR DIGIT-CHAR DIGIT-CHAR-P GRAPHIC-CHAR-P LOWER-CASE-P
   NAME-CHAR STANDARD-CHAR-P UPPER-CASE-P

   *GENSYM-COUNTER* COPY-SYMBOL GENSYM GENTEMP GET
   GET-PROPERTIES GETF KEYWORDP MAKE-SYMBOL REMF REMPROP SYMBOL-PLIST
   SYMBOL-PACKAGE 

   DEFPACKAGE DELETE-PACKAGE DO-ALL-SYMBOLS DO-EXTERNAL-SYMBOLS
   DO-SYMBOLS EXPORT FIND-ALL-SYMBOLS FIND-PACKAGE FIND-SYMBOL IMPORT
   IN-PACKAGE INTERN LIST-ALL-PACKAGES MAKE-PACKAGE PACKAGE 
   PACKAGE-NAME PACKAGE-NICKNAMES PACKAGEP PACKAGE-SHADOWING-SYMBOLS
   PACKAGE-USE-LIST PACKAGE-USED-BY-LIST RENAME-PACKAGE SHADOW
   SHADOWING-IMPORT UNEXPORT UNINTERN UNUSE-PACKAGE USE-PACKAGE
   WITH-PACKAGE-ITERATOR *MODULES* PROVIDE REQUIRE

   CONCATENATE COPY-SEQ COUNT COUNT-IF COUNT-IF-NOT DELETE
   DELETE-DUPLICATES DELETE-IF DELETE-IF-NOT ELT EVERY FILL FIND
   FIND-IF FIND-IF-NOT LENGTH MAKE-SEQUENCE MAP MAP-INTO MERGE
   MISMATCH NOTANY NOTEVERY NREVERSE NSUBSTITUTE NSUBSTITUTE-IF
   NSUBSTITUTE-IF-NOT POSITION POSITION-IF POSITION-IF-NOT REDUCE
   REMOVE REMOVE-DUPLICATES REMOVE-IF REMOVE-IF-NOT REPLACE REVERSE
   SEARCH SOME SORT STABLE-SORT SUBSEQ SUBSTITUTE SUBSTITUTE-IF
   SUBSTITUTE-IF-NOT 

   CAAAAR CAAADR CAAAR CAADAR CAADDR CAADR CAAR CADAAR CADADR CADAR
   CADDAR CADDDR CADDR CADR CAR CDAAAR CDAADR CDAAR CDADAR CDADDR
   CDADR CDAR CDDAAR CDDADR CDDAR CDDDAR CDDDDR CDDDR CDDR CDR
   ACONS ADJOIN APPEND ASSOC ASSOC-IF ASSOC-IF-NOT BUTLAST COPY-ALIST
   COPY-LIST COPY-TREE EIGHTH ENDP FIRST FIFTH FOURTH INTERSECTION
   LAST LDIFF LIST LIST* LIST-LENGTH MAKE-LIST MEMBER MEMBER-IF
   MEMBER-IF-NOT NBUTLAST NCONC NINTERSECTION NINTH NRECONC
   NSET-DIFFERENCE NSET-EXCLUSIVE-OR NSUBLIS NSUBST NSUBST-IF
   NSUBST-IF-NOT NTH NTHCDR NUNION PAIRLIS RASSOC RASSOC-IF
   RASSOC-IF-NOT REST REVAPPEND SECOND SET-DIFFERENCE
   SET-EXCLUSIVE-OR SEVENTH SIXTH SUBLIS SUBSETP SUBST SUBST-IF SUBST-IF-NOT TAILP
   TENTH THIRD TREE-EQUAL UNION  PUSH PUSHNEW POP

   ADJUST-ARRAY ADJUSTABLE-ARRAY-P AREF ARRAY-DIMENSION
   ARRAY-DIMENSIONS ARRAY-DISPLACEMENT ARRAY-ELEMENT-TYPE
   ARRAY-HAS-FILL-POINTER-P ARRAY-IN-BOUNDS-P ARRAY-RANK
   ARRAY-ROW-MAJOR-INDEX ARRAY-TOTAL-SIZE BIT BIT-AND BIT-ANDC1
   BIT-ANDC2 BIT-EQV BIT-IOR BIT-ORC1 BIT-ORC2 BIT-NAND BIT-NOR
   BIT-NOT BIT-XOR FILL-POINTER MAKE-ARRAY ROW-MAJOR-AREF SBIT SVREF VECTOR
   VECTOR-POP VECTOR-PUSH VECTOR-PUSH-EXTEND
   UPGRADED-ARRAY-ELEMENT-TYPE
   SIMPLE-STRING SIMPLE-BASE-STRING SIMPLE-BIT-VECTOR SIMPLE-VECTOR
   SIMPLE-ARRAY ARRAY
   ARRAY-DIMENSION-LIMIT ARRAY-RANK-LIMIT ARRAY-TOTAL-SIZE-LIMIT

   CHAR MAKE-STRING NSTRING-CAPITALIZE NSTRING-DOWNCASE
   NSTRING-UPCASE SCHAR STRING STRING-CAPITALIZE
   STRING-DOWNCASE STRING-EQUAL STRING-GREATERP
   STRING-LEFT-TRIM STRING-LESSP STRING-NOT-EQUAL
   STRING-NOT-GREATERP STRING-NOT-LESSP STRING-RIGHT-TRIM
   STRING-TRIM STRING-UPCASE STRING/= STRING< STRING<=
   STRING= STRING> STRING>=

   *DEBUG-IO* *ERROR-OUTPUT* *QUERY-IO* *STANDARD-INPUT*
   *STANDARD-OUTPUT* *TERMINAL-IO* *TRACE-OUTPUT*  
   BROADCAST-STREAM BROADCAST-STREAM-STREAMS CLEAR-INPUT CLEAR-OUTPUT
   CLOSE CONCATENATED-STREAM CONCATENATED-STREAM-STREAMS ECHO-STREAM
   ECHO-STREAM-INPUT-STREAM ECHO-STREAM-OUTPUT-STREAM FILE-STREAM FINISH-OUTPUT
   FORCE-OUTPUT FRESH-LINE GET-OUTPUT-STREAM-STRING INPUT-STREAM-P
   INTERACTIVE-STREAM-P LISTEN MAKE-BROADCAST-STREAM MAKE-ECHO-STREAM
   MAKE-CONCATENATED-STREAM MAKE-STRING-INPUT-STREAM
   MAKE-STRING-OUTPUT-STREAM MAKE-SYNONYM-STREAM MAKE-TWO-WAY-STREAM
   OPEN-STREAM-P OUTPUT-STREAM-P PEEK-CHAR READ-BYTE READ-CHAR READ-CHAR-NO-HANG
   READ-LINE READ-SEQUENCE STREAM STREAMP STREAM-ELEMENT-TYPE
   STREAM-EXTERNAL-FORMAT STRING-STREAM
   SYNONYM-STREAM SYNONYM-STREAM-SYMBOL TERPRI TWO-WAY-STREAM
   TWO-WAY-STREAM-INPUT-STREAM TWO-WAY-STREAM-OUTPUT-STREAM
   UNREAD-CHAR WITH-INPUT-FROM-STRING WITH-OPEN-STREAM
   WITH-OUTPUT-TO-STRING WRITE-BYTE WRITE-CHAR WRITE-STRING WRITE-SEQUENCE
   WRITE-LINE

   *READ-BASE* *READ-DEFAULT-FLOAT-FORMAT* *READ-EVAL* *READ-SUPPRESS*
   *READTABLE* COPY-READTABLE GET-DISPATCH-MACRO-CHARACTER
   GET-MACRO-CHARACTER MAKE-DISPATCH-MACRO-CHARACTER PARSE-INTEGER READ
   READ-DELIMITED-LIST READ-FROM-STRING READ-PRESERVING-WHITESPACE
   READTABLE READTABLE-CASE READTABLEP SET-DISPATCH-MACRO-CHARACTER
   SET-MACRO-CHARACTER SET-SYNTAX-FROM-CHAR


   *PRINT-ARRAY* *PRINT-BASE* *PRINT-CASE* *PRINT-CIRCLE*
   *PRINT-ESCAPE* *PRINT-GENSYM* *PRINT-LENGTH* *PRINT-LEVEL*
   *PRINT-LINES* *PRINT-MISER-WIDTH* *PRINT-PPRINT-DISPATCH*
   *PRINT-PRETTY* *PRINT-RADIX* *PRINT-READABLY* *PRINT-RIGHT-MARGIN*
   PPRINT PRIN1 PRIN1-TO-STRING PRINC PRINC-TO-STRING PRINT
   PRINT-UNREADABLE-OBJECT FORMAT FORMATTER
   WITH-STANDARD-IO-SYNTAX WRITE WRITE-TO-STRING Y-OR-N-P YES-OR-NO-P

   COPY-PPRINT-DISPATCH PPRINT-DISPATCH PPRINT-EXIT-IF-LIST-EXHAUSTED
   PPRINT-FILL PPRINT-INDENT PPRINT-LINEAR PPRINT-LOGICAL-BLOCK
   PPRINT-NEWLINE PPRINT-POP PPRINT-TAB PPRINT-TABULAR
   SET-PPRINT-DISPATCH 

   *DEFAULT-PATHNAME-DEFAULTS* DIRECTORY-NAMESTRING ENOUGH-NAMESTRING
   FILE-NAMESTRING HOST-NAMESTRING LOAD-LOGICAL-PATHNAME-TRANSLATIONS
   LOGICAL-PATHNAME LOGICAL-PATHNAME-TRANSLATIONS MAKE-PATHNAME
   MERGE-PATHNAMES NAMESTRING PARSE-NAMESTRING PATHNAME
   PATHNAME-DEVICE PATHNAME-DIRECTORY PATHNAME-HOST PATHNAME-NAME
   PATHNAME-TYPE PATHNAME-VERSION PATHNAMEP PATHNAME-MATCH-P
   TRANSLATE-LOGICAL-PATHNAME TRANSLATE-PATHNAME 
   WILD-PATHNAME-P

   DELETE-FILE DIRECTORY ENSURE-DIRECTORIES-EXIST FILE-AUTHOR
   FILE-POSITION FILE-LENGTH FILE-STRING-LENGTH FILE-WRITE-DATE OPEN
   PROBE-FILE RENAME-FILE TRUENAME USER-HOMEDIR-PATHNAME WITH-OPEN-FILE

   *FEATURES* APROPOS APROPOS-LIST CONSTANTLY COMPILE-FILE-PATHNAME
   DECODE-UNIVERSAL-TIME DESCRIBE DOCUMENTATION DRIBBLE ED
   ENCODE-UNIVERSAL-TIME GET-DECODED-TIME GET-INTERNAL-REAL-TIME
   GET-INTERNAL-RUN-TIME GET-UNIVERSAL-TIME INSPECT 
   INTERNAL-TIME-UNITS-PER-SECOND LISP-IMPLEMENTATION-TYPE
   LISP-IMPLEMENTATION-VERSION LONG-SITE-NAME MACHINE-INSTANCE 
   MACHINE-TYPE MACHINE-VERSION ROOM SHORT-SITE-NAME SLEEP
   SOFTWARE-TYPE SOFTWARE-VERSION TIME TRACE UNTRACE

   CONSTANTP FUNCTION-LAMBDA-EXPRESSION
   ;; These shouldn't be present in an ANSI Lisp, but some hosts add
   ;; them anyway.
   enclose define-declaration augment-environment
   variable-information function-information declaration-information
   
   *COMPILE-FILE-PATHNAME* *COMPILE-FILE-TRUENAME* *COMPILE-PRINT*
   *COMPILE-VERBOSE* *LOAD-PATHNAME* *LOAD-PRINT* *LOAD-TRUENAME*
   *LOAD-VERBOSE* COMPILE COMPILE-FILE DISASSEMBLE EVAL
   LOAD STEP WITH-COMPILATION-UNIT
   
   *BREAK-ON-SIGNALS* *DEBUGGER-HOOK* ABORT ASSERT BREAK CCASE CERROR
   COMPUTE-RESTARTS CONTINUE CTYPECASE CHECK-TYPE ERROR
   FIND-RESTART HANDLER-BIND HANDLER-CASE IGNORE-ERRORS
   INVOKE-DEBUGGER INVOKE-RESTART INVOKE-RESTART-INTERACTIVELY
   MUFFLE-WARNING RESTART RESTART-BIND RESTART-CASE RESTART-NAME
   SIGNAL STORE-VALUE USE-VALUE WARN WITH-CONDITION-RESTARTS
   WITH-SIMPLE-RESTART 

   ARITHMETIC-ERROR ARITHMETIC-ERROR-OPERANDS
   ARITHMETIC-ERROR-OPERATION CELL-ERROR CELL-ERROR-NAME CONDITION
   CONTROL-ERROR DEFINE-CONDITION DIVISION-BY-ZERO END-OF-FILE
   FILE-ERROR FILE-ERROR-PATHNAME FLOATING-POINT-OVERFLOW
   FLOATING-POINT-UNDERFLOW FLOATING-POINT-INEXACT
   FLOATING-POINT-INVALID-OPERATION MAKE-CONDITION PACKAGE-ERROR
   PACKAGE-ERROR-PACKAGE PARSE-ERROR PRINT-NOT-READABLE
   PRINT-NOT-READABLE-OBJECT PROGRAM-ERROR READER-ERROR
   SERIOUS-CONDITION SIMPLE-CONDITION SIMPLE-CONDITION-FORMAT-CONTROL
   SIMPLE-CONDITION-FORMAT-ARGUMENTS SIMPLE-ERROR SIMPLE-TYPE-ERROR
   SIMPLE-WARNING STORAGE-CONDITION STREAM-ERROR STREAM-ERROR-STREAM
   STYLE-WARNING TYPE-ERROR TYPE-ERROR-DATUM TYPE-ERROR-EXPECTED-TYPE
   UNBOUND-VARIABLE UNDEFINED-FUNCTION WARNING  

   BUILT-IN-CLASS CLASS GENERIC-FUNCTION METHOD METHOD-COMBINATION
   STANDARD-CLASS STANDARD-GENERIC-FUNCTION STANDARD-METHOD STANDARD-OBJECT 

   METHOD-COMBINATION-ERROR INVALID-METHOD-ERROR
   FUNCTION-KEYWORDS ENSURE-GENERIC-FUNCTION ALLOCATE-INSTANCE
   REINITIALIZE-INSTANCE SHARED-INITIALIZE 
   UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
   UPDATE-INSTANCE-FOR-REDEFINED-CLASS CHANGE-CLASS SLOT-BOUNDP
   SLOT-EXISTS-P SLOT-MAKUNBOUND SLOT-MISSING SLOT-UNBOUND SLOT-VALUE
   METHOD-QUALIFIERS NO-APPLICABLE-METHOD NO-NEXT-METHOD REMOVE-METHOD
   MAKE-INSTANCE MAKE-INSTANCES-OBSOLETE MAKE-LOAD-FORM
   MAKE-LOAD-FORM-SAVING-SLOTS WITH-ACCESSORS WITH-SLOTS DEFCLASS
   DEFGENERIC DEFMETHOD FIND-CLASS NEXT-METHOD-P CALL-METHOD
   MAKE-METHOD CALL-NEXT-METHOD COMPUTE-APPLICABLE-METHODS
   DEFINE-METHOD-COMBINATION FIND-METHOD ADD-METHOD
   INITIALIZE-INSTANCE CLASS-NAME CLASS-OF UNBOUND-SLOT
   UNBOUND-SLOT-INSTANCE PRINT-OBJECT DESCRIBE-OBJECT

   STRUCTURE-OBJECT STRUCTURE-CLASS DEFSTRUCT COPY-STRUCTURE

   CLRHASH GETHASH HASH-TABLE HASH-TABLE-COUNT HASH-TABLE-P
   HASH-TABLE-REHASH-SIZE HASH-TABLE-REHASH-THRESHOLD HASH-TABLE-SIZE
   HASH-TABLE-TEST MAKE-HASH-TABLE MAPHASH REMHASH SXHASH
   WITH-HASH-TABLE-ITERATOR


   )
  (:export

   ;;; primitive type coercion
   character-int character-wint
   single-float-float single-float-double double-float-double 
   integer-index fixnum-index

   int-character wint-character base-char-code-limit

   index-fixnum int-fixnum int-integer ratio-numerator ratio-denominator
   float-single-float float-double-float double-single-float
   single-double-float double-double-float
   charp-simple-base-string
   
   make-ratio  
   complex-realpart complex-imagpart
   make-complex

   OBJECT INDEX CHARP			; Types
   XOR FIXNUMP				; Predicates
   ADD SUBT MULT DIV			; Math
   GET-CHARACTER-SYNTAX			; Reader

   ;; compilation
   OUTPUT-FORMAT LOADER-NAME
   WITH-UNIQUE-NAMES REBINDING

   ;; Errors
   signal-control-error signal-program-error exit
   missing-args extra-args key-not-allowed check-keys key-arg

   ;; Resources
   ALLOCATE-RESOURCE CLEAR-RESOURCE DEALLOCATE-RESOURCE DEFRESOURCE
   MAP-RESOURCE USING-RESOURCE

   ;; Form and other syntax manipulation
   MAKE-NAME MAKE-KEYWORD
   LAMBDA-LIST-KEYWORD-P CAR-EQ LIST-ARG
   BINDINGFORM-NAME BINDINGFORM-INITFORM
   BINDINGFORM-KEYWORD EXTRACT-KEYWORDS
   FIND-DECLARATIONS

   ;; Environments
   ENCLOSE DEFINE-DECLARATION AUGMENT-ENVIRONMENT PARSE-MACRO
   VARIABLE-INFORMATION FUNCTION-INFORMATION DECLARATION-INFORMATION

   ;; Visible accessors/constructors
   make-symbol-macro-function symbol-macro-function
   setf-expander set-setf-expander
   named-function global-declaration
   set-symbol-function-value set-symbol-setf-function-value ;!!!

   ;; Pathnames:
   unix-pathname windows-pathname

   ;; Applications:
   *MACHINE-VERSION* *SHORT-SITE-NAME* *LONG-SITE-NAME* *PROMPT-HOOK*
   *READ-EVAL-PRINT-HELP* CHAR-BIT SET-CHAR-BIT
   MACHINE-ID USER-ID GETENV

   ;; CLOS Streams
   *DEFAULT-ELEMENT-TYPE* *ORIGINAL-STREAM* 
   ENCAPSULATING-STREAM ENCAPSULATING-STREAM-P FUNDAMENTAL-STREAM
   FUNDAMENTAL-CHARACTER-STREAM FUNDAMENTAL-BINARY-STREAM
   FUNDAMENTAL-INPUT-STREAM FUNDAMENTAL-OUTPUT-STREAM
   FUNDAMENTAL-CHARACTER-INPUT-STREAM
   FUNDAMENTAL-CHARACTER-OUTPUT-STREAM FUNDAMENTAL-BINARY-INPUT-STREAM
   FUNDAMENTAL-BINARY-OUTPUT-STREAM STREAM INPUT-STREAM OUTPUT-STREAM
   STREAM-ADVANCE-TO-COLUMN STREAM-CLEAR-INPUT STREAM-CLEAR-OUTPUT
   STREAM-FORCE-OUTPUT STREAM-FINISH-OUTPUT STREAM-ELEMENT-TYPE
   STREAM-LISTEN STREAM-READ-CHAR-NO-HANG STREAM-PEEK-CHAR
   STREAM-LINE-COLUMN STREAM-START-LINE-P STREAM-READ-CHAR
   STREAM-READ-BYTE STREAM-WRITE-CHAR STREAM-WRITE-BYTE
   STREAM-READ-LINE STREAM-READ-SEQUENCE STREAM-WRITE-SEQUENCE
   STREAM-TERPRI STREAM-FRESH-LINE STREAM-UNREAD-CHAR STREAM-WRITE-STRING

   ;; Visible CLOS internals:
   add-attached-methods remove-attached-methods
   ensure-method ensure-method-combination-type ensure-deftype
   find-slot-definition canonicalize-specializer qualifier-match
   class-name-of class-precedence-list-of

   ;; Eclipse extensions to CLOS/MOP
   ABSTRACT-CLASS-P FUNCALLABLE-STANDARD-OBJECT FUNCALLABLE-STANDARD-SYSTEM-CLASS
   FIND-TYPE INTERNED-STANDARD-CLASS INTERNED-STANDARD-SYSTEM-CLASS
   METHOD-COMBINATION-TYPE METHOD-COMBINATION-TYPE-DECLARATIONS
   METHOD-COMBINATION-TYPE-FUNCTION METHOD-COMBINATION-FUNCTION
   PRIMARY-CLASS-P SEALED-CLASS-P STANDARD-SYSTEM-CLASS
   STANDARD-SYSTEM-GENERIC-FUNCTION TYPE-NAME UNKNOWN-OBJECT 

   ;; The following are defined in the MOP, but not by ANSI:

   ADD-DIRECT-SUBCLASS CLASS-DEFAULT-INITARGS
   CLASS-DIRECT-DEFAULT-INITARGS CLASS-DIRECT-SLOTS
   CLASS-DIRECT-SUBCLASSES CLASS-DIRECT-SUPERCLASSES CLASS-FINALIZED-P
   CLASS-PRECEDENCE-LIST CLASS-PROTOTYPE CLASS-SLOTS
   COMPUTE-APPLICABLE-METHODS-USING-CLASSES
   COMPUTE-CLASS-PRECEDENCE-LIST COMPUTE-DEFAULT-INITARGS
   COMPUTE-DISCRIMINATING-FUNCTION COMPUTE-EFFECTIVE-METHOD
   COMPUTE-EFFECTIVE-SLOT-DEFINITION COMPUTE-SLOTS
   DIRECT-SLOT-DEFINITION DIRECT-SLOT-DEFINITION-CLASS
   EFFECTIVE-SLOT-DEFINITION EFFECTIVE-SLOT-DEFINITION-CLASS
   ENSURE-CLASS ENSURE-CLASS-USING-CLASS
   ENSURE-GENERIC-FUNCTION-USING-CLASS EQL-SPECIALIZER
   EQL-SPECIALIZER-OBJECT EXTRACT-LAMBDA-LIST
   EXTRACT-SPECIALIZER-NAMES FINALIZE-INHERITANCE  
   FIND-METHOD-COMBINATION FORWARD-REFERENCED-CLASS
   FUNCALLABLE-STANDARD-CLASS FUNCALLABLE-STANDARD-INSTANCE-ACCESS 
   GENERIC-FUNCTION-ARGUMENT-PRECEDENCE-ORDER
   GENERIC-FUNCTION-DECLARATIONS GENERIC-FUNCTION-LAMBDA-LIST
   GENERIC-FUNCTION-METHOD-CLASS GENERIC-FUNCTION-METHOD-COMBINATION
   GENERIC-FUNCTION-METHODS GENERIC-FUNCTION-NAME INTERN-EQL-SPECIALIZER
   MAKE-METHOD-LAMBDA MAP-DEPENDENTS METAOBJECT METHOD-FUNCTION
   METHOD-GENERIC-FUNCTION METHOD-LAMBDA-LIST METHOD-SPECIALIZERS
   ACCESSOR-METHOD-SLOT-DEFINITION READER-METHOD-CLASS
   REMOVE-DEPENDENT REMOVE-DIRECT-METHOD REMOVE-DIRECT-SUBCLASS
   SET-FUNCALLABLE-INSTANCE-FUNCTION SLOT-BOUNDP-USING-CLASS
   SLOT-DEFINITION SLOT-DEFINITION-ALLOCATION SLOT-DEFINITION-INITARGS
   SLOT-DEFINITION-INITFORM SLOT-DEFINITION-INITFUNCTION
   SLOT-DEFINITION-LOCATION SLOT-DEFINITION-NAME
   SLOT-DEFINITION-READERS SLOT-DEFINITION-WRITERS
   SLOT-DEFINITION-TYPE SLOT-MAKUNBOUND-USING-CLASS
   SLOT-VALUE-USING-CLASS SPECIALIZER
   SPECIALIZER-DIRECT-GENERIC-FUNCTIONS SPECIALIZER-DIRECT-METHODS
   STANDARD-ACCESSOR-METHOD STANDARD-DIRECT-SLOT-DEFINITION
   STANDARD-EFFECTIVE-SLOT-DEFINITION STANDARD-INSTANCE-ACCESS
   STANDARD-READER-METHOD STANDARD-SLOT-DEFINITION
   STANDARD-WRITER-METHOD UPDATE-DEPENDENT VALIDATE-SUPERCLASS
   WRITER-METHOD-CLASS 
   ))



(dolist (sym `(vars xp make-name))
  (import (intern (symbol-name sym) :eclipse) :host))

(dolist (sym `(host-load *src-dir*))
  (import sym :eclipse))

(defvar *cl-symbols*
	 '(&ALLOW-OTHER-KEYS &AUX &BODY &ENVIRONMENT &KEY &OPTIONAL &REST
			     &WHOLE * ** *** *BREAK-ON-SIGNALS* *COMPILE-FILE-PATHNAME*
			     *COMPILE-FILE-TRUENAME* *COMPILE-PRINT* *COMPILE-VERBOSE*
			     *DEBUG-IO* *DEBUGGER-HOOK* *DEFAULT-PATHNAME-DEFAULTS*
			     *ERROR-OUTPUT* *FEATURES* *GENSYM-COUNTER* *LOAD-PATHNAME*
			     *LOAD-PRINT* *LOAD-TRUENAME* *LOAD-VERBOSE* *MACROEXPAND-HOOK*
			     *MODULES*
			     *PACKAGE* *PRINT-ARRAY* *PRINT-BASE* *PRINT-CASE* *PRINT-CIRCLE*
			     *PRINT-ESCAPE* *PRINT-GENSYM* *PRINT-LENGTH* *PRINT-LEVEL*
			     *PRINT-LINES* *PRINT-MISER-WIDTH* *PRINT-PPRINT-DISPATCH*
			     *PRINT-PRETTY* *PRINT-RADIX* *PRINT-READABLY* *PRINT-RIGHT-MARGIN*
			     *QUERY-IO* *RANDOM-STATE* *READ-BASE* *READ-DEFAULT-FLOAT-FORMAT*
			     *READ-EVAL* *READ-SUPPRESS* *READTABLE* *STANDARD-INPUT*
			     *STANDARD-OUTPUT* *TERMINAL-IO* *TRACE-OUTPUT* + ++ +++ - / // ///
			     /= 1+ 1- < <= = > >= ABORT ABS ACONS ACOS ACOSH ADD-METHOD ADJOIN
			     ADJUST-ARRAY ADJUSTABLE-ARRAY-P ALLOCATE-INSTANCE ALPHA-CHAR-P
			     ALPHANUMERICP AND APPEND APPLY APROPOS APROPOS-LIST AREF
			     ARITHMETIC-ERROR ARITHMETIC-ERROR-OPERANDS
			     ARITHMETIC-ERROR-OPERATION ARRAY ARRAY-DIMENSION
			     ARRAY-DIMENSION-LIMIT ARRAY-DIMENSIONS ARRAY-ELEMENT-TYPE
			     ARRAY-HAS-FILL-POINTER-P ARRAY-IN-BOUNDS-P ARRAY-RANK
			     ARRAY-RANK-LIMIT ARRAY-ROW-MAJOR-INDEX ARRAY-DISPLACEMENT
			     ARRAY-TOTAL-SIZE ARRAY-TOTAL-SIZE-LIMIT ARRAYP ASH ASIN ASINH
			     ASSERT ASSOC ASSOC-IF ASSOC-IF-NOT ATAN ATANH ATOM
			     BASE-CHAR BASE-STRING BIGNUM BIT BIT-AND
			     BIT-ANDC1 BIT-ANDC2 BIT-EQV BIT-IOR BIT-NAND BIT-NOR BIT-NOT
			     BIT-ORC1 BIT-ORC2 BIT-VECTOR BIT-VECTOR-P BIT-XOR BLOCK BOOLE BOOLEAN
			     BOOLE-1 BOOLE-2 BOOLE-AND BOOLE-ANDC1 BOOLE-ANDC2 BOOLE-C1 BOOLE-C2
			     BOOLE-CLR BOOLE-EQV BOOLE-IOR BOOLE-NAND BOOLE-NOR BOOLE-ORC1
			     BOOLE-ORC2 BOOLE-SET BOOLE-XOR BOTH-CASE-P BOUNDP BREAK
			     BROADCAST-STREAM BROADCAST-STREAM-STREAMS
			     BUTLAST BUILT-IN-CLASS BYTE
			     BYTE-POSITION BYTE-SIZE CAAAAR CAAADR CAAAR CAADAR CAADDR CAADR
			     CAAR CADAAR CADADR CADAR CADDAR CADDDR CADDR CADR
			     CALL-ARGUMENTS-LIMIT CALL-METHOD CALL-NEXT-METHOD CAR CASE CATCH
			     CCASE CDAAAR CDAADR CDAAR CDADAR CDADDR CDADR CDAR CDDAAR CDDADR
			     CDDAR CDDDAR CDDDDR CDDDR CDDR CDR CEILING CELL-ERROR
			     CELL-ERROR-NAME CERROR CHANGE-CLASS CHAR CHAR-CODE CHAR-CODE-LIMIT
			     CHAR-DOWNCASE CHAR-EQUAL CHAR-GREATERP CHAR-INT CHAR-LESSP
			     CHAR-NAME CHAR-NOT-EQUAL CHAR-NOT-GREATERP CHAR-NOT-LESSP
			     CHAR-UPCASE CHAR/= CHAR< CHAR<= CHAR= CHAR> CHAR>= CHARACTER
			     CHARACTERP CHECK-TYPE CIS CLASS CLASS-NAME CLASS-OF CLEAR-INPUT
			     CLEAR-OUTPUT CLOSE CLRHASH CODE-CHAR COERCE COMPILATION-SPEED
			     COMPILE COMPILE-FILE COMPILE-FILE-PATHNAME COMPILED-FUNCTION
			     COMPILED-FUNCTION-P COMPILER-MACRO
			     COMPILER-MACRO-FUNCTION COMPLEMENT COMPLEX  
			     COMPLEXP COMPUTE-APPLICABLE-METHODS COMPUTE-RESTARTS CONCATENATE
			     CONCATENATED-STREAM CONCATENATED-STREAM-STREAMS COND CONDITION
			     CONJUGATE CONS CONSP CONSTANTLY CONSTANTP CONTINUE CONTROL-ERROR
			     COPY-ALIST COPY-LIST COPY-PPRINT-DISPATCH COPY-READTABLE COPY-SEQ
			     COPY-STRUCTURE COPY-SYMBOL COPY-TREE COS COSH COUNT COUNT-IF
			     COUNT-IF-NOT CTYPECASE DEBUG DECF DECLAIM DECLARATION
			     DECLARE DECODE-FLOAT DECODE-UNIVERSAL-TIME
			     DEFCLASS DEFCONSTANT DEFGENERIC DEFINE-COMPILER-MACRO
			     DEFINE-CONDITION DEFINE-METHOD-COMBINATION
			     DEFINE-MODIFY-MACRO DEFINE-SETF-EXPANDER
			     DEFINE-SYMBOL-MACRO DEFMACRO DEFMETHOD
			     DEFPACKAGE DEFPARAMETER DEFSETF DEFSTRUCT DEFTYPE DEFUN DEFVAR
			     DELETE DELETE-DUPLICATES DELETE-FILE DELETE-IF DELETE-IF-NOT
			     DELETE-PACKAGE DENOMINATOR DEPOSIT-FIELD DESCRIBE DESCRIBE-OBJECT
			     DESTRUCTURING-BIND DIGIT-CHAR DIGIT-CHAR-P DIRECTORY
			     DIRECTORY-NAMESTRING DISASSEMBLE DIVISION-BY-ZERO DO DO*
			     DO-ALL-SYMBOLS DO-EXTERNAL-SYMBOLS DO-SYMBOLS DOCUMENTATION DOLIST
			     DOTIMES DOUBLE-FLOAT DOUBLE-FLOAT-EPSILON
			     DOUBLE-FLOAT-NEGATIVE-EPSILON DPB DRIBBLE DYNAMIC-EXTENT ECASE
			     ECHO-STREAM ECHO-STREAM-INPUT-STREAM ECHO-STREAM-OUTPUT-STREAM ED
			     EIGHTH ELT ENCODE-UNIVERSAL-TIME END-OF-FILE ENDP
			     ENOUGH-NAMESTRING ENSURE-DIRECTORIES-EXIST ENSURE-GENERIC-FUNCTION
			     EQ EQL EQUAL EQUALP ERROR ETYPECASE EVAL EVAL-WHEN EVENP EVERY EXP
			     EXPORT EXPT EXTENDED-CHAR FBOUNDP FCEILING FDEFINITION FFLOOR FIFTH
			     FILE-AUTHOR FILE-ERROR FILE-ERROR-PATHNAME FILE-LENGTH
			     FILE-NAMESTRING FILE-POSITION FILE-STREAM FILE-STRING-LENGTH
			     FILE-WRITE-DATE FILL FILL-POINTER FIND FIND-ALL-SYMBOLS FIND-CLASS
			     FIND-IF FIND-IF-NOT FIND-METHOD FIND-PACKAGE FIND-RESTART
			     FIND-SYMBOL FINISH-OUTPUT FIRST FIXNUM FLET FLOAT FLOAT-DIGITS
			     FLOAT-PRECISION FLOAT-RADIX FLOAT-SIGN FLOATING-POINT-INEXACT
			     FLOATING-POINT-INVALID-OPERATION FLOATING-POINT-OVERFLOW
			     FLOATING-POINT-UNDERFLOW FLOATP FLOOR FMAKUNBOUND FORCE-OUTPUT
			     FORMAT FORMATTER FOURTH FRESH-LINE FROUND FTRUNCATE FTYPE FUNCALL
			     FUNCTION FUNCTION-KEYWORDS
			     FUNCTION-LAMBDA-EXPRESSION FUNCTIONP GCD 
			     GENERIC-FUNCTION GENSYM GENTEMP GET GET-DECODED-TIME
			     GET-DISPATCH-MACRO-CHARACTER GET-INTERNAL-REAL-TIME
			     GET-INTERNAL-RUN-TIME GET-MACRO-CHARACTER GET-OUTPUT-STREAM-STRING
			     GET-PROPERTIES GET-SETF-EXPANSION
			     GET-UNIVERSAL-TIME GETF GETHASH GO GRAPHIC-CHAR-P HANDLER-BIND
			     HANDLER-CASE HASH-TABLE HASH-TABLE-COUNT HASH-TABLE-P
			     HASH-TABLE-REHASH-SIZE HASH-TABLE-REHASH-THRESHOLD HASH-TABLE-SIZE
			     HASH-TABLE-TEST HOST-NAMESTRING IDENTITY IF IGNORABLE IGNORE
			     IGNORE-ERRORS IMAGPART IMPORT IN-PACKAGE INCF INITIALIZE-INSTANCE
			     INLINE INPUT-STREAM-P INSPECT INTEGER INTEGER-DECODE-FLOAT
			     INTEGER-LENGTH INTEGERP INTERACTIVE-STREAM-P INTERN
			     INTERNAL-TIME-UNITS-PER-SECOND INTERSECTION INVALID-METHOD-ERROR
			     INVOKE-DEBUGGER INVOKE-RESTART INVOKE-RESTART-INTERACTIVELY ISQRT
			     KEYWORD KEYWORDP LABELS LAMBDA LAMBDA-LIST-KEYWORDS
			     LAMBDA-PARAMETERS-LIMIT LAST LCM LDB LDB-TEST LDIFF
			     LEAST-NEGATIVE-DOUBLE-FLOAT LEAST-NEGATIVE-LONG-FLOAT
			     LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT
			     LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT
			     LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT
			     LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT LEAST-NEGATIVE-SHORT-FLOAT
			     LEAST-NEGATIVE-SINGLE-FLOAT LEAST-POSITIVE-DOUBLE-FLOAT
			     LEAST-POSITIVE-LONG-FLOAT LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT
			     LEAST-POSITIVE-NORMALIZED-LONG-FLOAT
			     LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT
			     LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT LEAST-POSITIVE-SHORT-FLOAT
			     LEAST-POSITIVE-SINGLE-FLOAT LENGTH LET LET*
			     LISP-IMPLEMENTATION-TYPE LISP-IMPLEMENTATION-VERSION LIST LIST*
			     LIST-ALL-PACKAGES LIST-LENGTH LISTEN LISTP LOAD
			     LOAD-LOGICAL-PATHNAME-TRANSLATIONS LOAD-TIME-VALUE LOCALLY LOG
			     LOGAND LOGANDC1 LOGANDC2 LOGBITP LOGCOUNT LOGEQV LOGICAL-PATHNAME
			     LOGICAL-PATHNAME-TRANSLATIONS LOGIOR LOGNAND LOGNOR LOGNOT LOGORC1
			     LOGORC2 LOGTEST LOGXOR LONG-FLOAT LONG-FLOAT-EPSILON
			     LONG-FLOAT-NEGATIVE-EPSILON LONG-SITE-NAME LOOP LOOP-FINISH
			     LOWER-CASE-P MACHINE-INSTANCE MACHINE-TYPE MACHINE-VERSION
			     MACRO-FUNCTION MACROEXPAND MACROEXPAND-1 MACROLET MAKE-ARRAY
			     MAKE-BROADCAST-STREAM MAKE-CONCATENATED-STREAM MAKE-CONDITION
			     MAKE-DISPATCH-MACRO-CHARACTER MAKE-ECHO-STREAM MAKE-HASH-TABLE
			     MAKE-INSTANCE MAKE-INSTANCES-OBSOLETE MAKE-LIST MAKE-LOAD-FORM
			     MAKE-LOAD-FORM-SAVING-SLOTS MAKE-METHOD MAKE-PACKAGE MAKE-PATHNAME
			     MAKE-RANDOM-STATE MAKE-SEQUENCE MAKE-STRING
			     MAKE-STRING-INPUT-STREAM MAKE-STRING-OUTPUT-STREAM MAKE-SYMBOL
			     MAKE-SYNONYM-STREAM MAKE-TWO-WAY-STREAM MAKUNBOUND MAP MAP-INTO
			     MAPC MAPCAN MAPCAR MAPCON MAPHASH MAPL MAPLIST MASK-FIELD MAX
			     MEMBER MEMBER-IF MEMBER-IF-NOT MERGE
			     MERGE-PATHNAMES METHOD METHOD-COMBINATION
			     METHOD-COMBINATION-ERROR METHOD-QUALIFIERS MIN MINUSP MISMATCH MOD
			     MOST-NEGATIVE-DOUBLE-FLOAT MOST-NEGATIVE-FIXNUM
			     MOST-NEGATIVE-LONG-FLOAT MOST-NEGATIVE-SHORT-FLOAT
			     MOST-NEGATIVE-SINGLE-FLOAT MOST-POSITIVE-DOUBLE-FLOAT
			     MOST-POSITIVE-FIXNUM MOST-POSITIVE-LONG-FLOAT
			     MOST-POSITIVE-SHORT-FLOAT MOST-POSITIVE-SINGLE-FLOAT MUFFLE-WARNING
			     MULTIPLE-VALUE-BIND MULTIPLE-VALUE-CALL MULTIPLE-VALUE-LIST
			     MULTIPLE-VALUE-PROG1 MULTIPLE-VALUE-SETQ MULTIPLE-VALUES-LIMIT
			     NAME-CHAR NAMESTRING NBUTLAST NCONC NEXT-METHOD-P NIL NINTERSECTION
			     NINTH NO-APPLICABLE-METHOD NO-NEXT-METHOD NOT NOTANY NOTEVERY
			     NOTINLINE NRECONC NREVERSE NSET-DIFFERENCE NSET-EXCLUSIVE-OR
			     NSTRING-CAPITALIZE NSTRING-DOWNCASE NSTRING-UPCASE NSUBLIS NSUBST
			     NSUBST-IF NSUBST-IF-NOT NSUBSTITUTE NSUBSTITUTE-IF
			     NSUBSTITUTE-IF-NOT NTH NTH-VALUE NTHCDR NULL NUMBER NUMBERP
			     NUMERATOR NUNION ODDP OPEN OPEN-STREAM-P OPTIMIZE OR OTHERWISE
			     OUTPUT-STREAM-P PACKAGE PACKAGE-ERROR PACKAGE-ERROR-PACKAGE
			     PACKAGE-NAME PACKAGE-NICKNAMES PACKAGE-SHADOWING-SYMBOLS
			     PACKAGE-USE-LIST PACKAGE-USED-BY-LIST PACKAGEP PAIRLIS PARSE-ERROR
			     PARSE-INTEGER PARSE-NAMESTRING PATHNAME PATHNAME-DEVICE
			     PATHNAME-DIRECTORY PATHNAME-HOST PATHNAME-MATCH-P PATHNAME-NAME
			     PATHNAME-TYPE PATHNAME-VERSION PATHNAMEP PEEK-CHAR PHASE PI PLUSP
			     POP POSITION POSITION-IF POSITION-IF-NOT PPRINT PPRINT-DISPATCH
			     PPRINT-EXIT-IF-LIST-EXHAUSTED PPRINT-FILL PPRINT-INDENT
			     PPRINT-LINEAR PPRINT-LOGICAL-BLOCK PPRINT-NEWLINE PPRINT-POP
			     PPRINT-TAB PPRINT-TABULAR PRIN1 PRIN1-TO-STRING PRINC
			     PRINC-TO-STRING PRINT PRINT-NOT-READABLE PRINT-NOT-READABLE-OBJECT
			     PRINT-OBJECT PRINT-UNREADABLE-OBJECT PROBE-FILE PROCLAIM PROG PROG*
			     PROG1 PROG2 PROGN PROGRAM-ERROR PROGV PROVIDE PSETF PSETQ PUSH
			     PUSHNEW QUOTE RANDOM RANDOM-STATE RANDOM-STATE-P RASSOC RASSOC-IF
			     RASSOC-IF-NOT RATIO RATIONAL RATIONALIZE RATIONALP READ READ-BYTE
			     READ-CHAR READ-CHAR-NO-HANG READ-DELIMITED-LIST READ-FROM-STRING
			     READ-LINE READ-PRESERVING-WHITESPACE READ-SEQUENCE
			     READER-ERROR READTABLE
			     READTABLE-CASE READTABLEP REAL REALP REALPART REDUCE
			     REINITIALIZE-INSTANCE REM REMF REMHASH REMOVE REMOVE-DUPLICATES
			     REMOVE-IF REMOVE-IF-NOT REMOVE-METHOD REMPROP RENAME-FILE
			     RENAME-PACKAGE REPLACE REQUIRE REST RESTART RESTART-BIND
			     RESTART-CASE RESTART-NAME RETURN RETURN-FROM REVAPPEND REVERSE ROOM
			     ROTATEF ROUND ROW-MAJOR-AREF RPLACA RPLACD SAFETY SATISFIES SBIT
			     SCALE-FLOAT SCHAR SEARCH SECOND SEQUENCE SERIOUS-CONDITION SET
			     SET-DIFFERENCE SET-DISPATCH-MACRO-CHARACTER SET-EXCLUSIVE-OR
			     SET-MACRO-CHARACTER SET-PPRINT-DISPATCH SET-SYNTAX-FROM-CHAR SETF
			     SETQ SEVENTH SHADOW SHADOWING-IMPORT SHARED-INITIALIZE SHIFTF
			     SHORT-FLOAT SHORT-FLOAT-EPSILON SHORT-FLOAT-NEGATIVE-EPSILON
			     SHORT-SITE-NAME SIGNAL SIGNED-BYTE SIGNUM SIMPLE-ARRAY
			     SIMPLE-BASE-STRING SIMPLE-BIT-VECTOR SIMPLE-BIT-VECTOR-P
			     SIMPLE-CONDITION SIMPLE-CONDITION-FORMAT-ARGUMENTS
			     SIMPLE-CONDITION-FORMAT-CONTROL SIMPLE-ERROR SIMPLE-STRING
			     SIMPLE-STRING-P SIMPLE-TYPE-ERROR SIMPLE-VECTOR SIMPLE-VECTOR-P
			     SIMPLE-WARNING SIN SINGLE-FLOAT SINGLE-FLOAT-EPSILON
			     SINGLE-FLOAT-NEGATIVE-EPSILON SINH SIXTH SLEEP SLOT-BOUNDP
			     SLOT-EXISTS-P SLOT-MAKUNBOUND SLOT-MISSING SLOT-UNBOUND SLOT-VALUE
			     SOFTWARE-TYPE SOFTWARE-VERSION SOME SORT SPACE SPECIAL
			     SPECIAL-OPERATOR-P SPEED SQRT STABLE-SORT STANDARD STANDARD-CHAR
			     STANDARD-CHAR-P STANDARD-CLASS STANDARD-GENERIC-FUNCTION
			     STANDARD-METHOD STANDARD-OBJECT 
			     STEP STORAGE-CONDITION STORE-VALUE STREAM STREAM-ELEMENT-TYPE
			     STREAM-ERROR STREAM-ERROR-STREAM STREAM-EXTERNAL-FORMAT STREAMP
			     STRING STRING-CAPITALIZE STRING-DOWNCASE STRING-EQUAL
			     STRING-GREATERP STRING-LEFT-TRIM STRING-LESSP STRING-NOT-EQUAL
			     STRING-NOT-GREATERP STRING-NOT-LESSP STRING-RIGHT-TRIM
			     STRING-STREAM STRING-TRIM STRING-UPCASE STRING/= STRING< STRING<=
			     STRING= STRING> STRING>= STRINGP STRUCTURE STRUCTURE-CLASS
			     STRUCTURE-OBJECT STYLE-WARNING SUBLIS
			     SUBSEQ SUBSETP SUBST SUBST-IF SUBST-IF-NOT SUBSTITUTE SUBSTITUTE-IF
			     SUBSTITUTE-IF-NOT SUBTYPEP SVREF SXHASH SYMBOL SYMBOL-FUNCTION
			     SYMBOL-MACROLET SYMBOL-NAME SYMBOL-PACKAGE SYMBOL-PLIST
			     SYMBOL-VALUE SYMBOLP SYNONYM-STREAM SYNONYM-STREAM-SYMBOL T TAGBODY
			     TAILP TAN TANH TENTH TERPRI THE THIRD THROW TIME TRACE
			     TRANSLATE-LOGICAL-PATHNAME TRANSLATE-PATHNAME TREE-EQUAL TRUENAME
			     TRUNCATE TWO-WAY-STREAM TWO-WAY-STREAM-INPUT-STREAM
			     TWO-WAY-STREAM-OUTPUT-STREAM TYPE TYPE-ERROR TYPE-ERROR-DATUM
			     TYPE-ERROR-EXPECTED-TYPE TYPE-OF TYPECASE TYPEP UNBOUND-SLOT
			     UNBOUND-SLOT-INSTANCE UNBOUND-VARIABLE UNDEFINED-FUNCTION UNEXPORT
			     UNINTERN UNION UNLESS UNREAD-CHAR UNSIGNED-BYTE UNTRACE
			     UNUSE-PACKAGE UNWIND-PROTECT UPDATE-INSTANCE-FOR-DIFFERENT-CLASS
			     UPDATE-INSTANCE-FOR-REDEFINED-CLASS UPGRADED-ARRAY-ELEMENT-TYPE
			     UPGRADED-COMPLEX-PART-TYPE UPPER-CASE-P USE-PACKAGE USE-VALUE
			     USER-HOMEDIR-PATHNAME VALUES VALUES-LIST VARIABLE
			     VECTOR VECTOR-POP VECTOR-PUSH
			     VECTOR-PUSH-EXTEND VECTORP WARN WARNING WHEN WILD-PATHNAME-P
			     WITH-ACCESSORS WITH-COMPILATION-UNIT
			     WITH-CONDITION-RESTARTS WITH-HASH-TABLE-ITERATOR
			     WITH-INPUT-FROM-STRING WITH-OPEN-FILE WITH-OPEN-STREAM
			     WITH-OUTPUT-TO-STRING WITH-PACKAGE-ITERATOR WITH-SIMPLE-RESTART
			     WITH-SLOTS WITH-STANDARD-IO-SYNTAX WRITE WRITE-BYTE WRITE-CHAR
			     WRITE-LINE WRITE-SEQUENCE WRITE-STRING WRITE-TO-STRING Y-OR-N-P
			     YES-OR-NO-P ZEROP))

(dolist (sym *cl-symbols*)
  (export (intern (symbol-name sym) :host) :host)
  (export (intern (symbol-name sym) :eclipse) :eclipse))
  
