#!/bin/sh
lisp -core hpcmucl.core -eval "(ccq \"$1\" :eclipse)"


# c-pkg common-comp macro-comp pretty-comp prim-decs kernel 
# array character condition equalp file-stream comp-stream circle 
# printer format print-object file describe debug literal c-walk 
# default-pp reader stream pretty directives c pathname temp 
# character file-stream comp-stream evaluation describer walk-top walk-util 